-- SQL Logging Session
-- Session ID: d6b72475-9e96-4e91-9f5d-797774484bd4
-- Started: 2026-02-27T21:33:40.526Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction SQLServerDataProvider

-- Save MJ: Schema Info (core SP call only)
DECLARE @SchemaName_48853663 NVARCHAR(50),
@EntityIDMin_48853663 INT,
@EntityIDMax_48853663 INT,
@Comments_48853663 NVARCHAR(MAX),
@Description_48853663 NVARCHAR(MAX),
@EntityNamePrefix_48853663 NVARCHAR(25),
@EntityNameSuffix_48853663 NVARCHAR(25),
@ID_48853663 UNIQUEIDENTIFIER
SET
  @SchemaName_48853663 = N'__mj_BizAppsCommon'
SET
  @EntityIDMin_48853663 = 1
SET
  @EntityIDMax_48853663 = 1000000
SET
  @Description_48853663 = N'MemberJunction: Common Business App Data'
SET
  @EntityNamePrefix_48853663 = N'MJ.BizApps.Common: '
SET
  @ID_48853663 = '0A9F0FDD-CD4D-4892-BA45-85722B982032'
EXEC [__mj].spUpdateSchemaInfo @SchemaName = @SchemaName_48853663,
  @EntityIDMin = @EntityIDMin_48853663,
  @EntityIDMax = @EntityIDMax_48853663,
  @Comments = @Comments_48853663,
  @Description = @Description_48853663,
  @EntityNamePrefix = @EntityNamePrefix_48853663,
  @EntityNameSuffix = @EntityNameSuffix_48853663,
  @ID = @ID_48853663;

-- Save MJ.BizApps.Common: Address Types (core SP call only)
DECLARE @ID_60c90c87 UNIQUEIDENTIFIER,
@Name_60c90c87 NVARCHAR(100),
@Description_60c90c87 NVARCHAR(MAX),
@IconClass_60c90c87 NVARCHAR(100),
@DefaultRank_60c90c87 INT,
@IsActive_60c90c87 BIT
SET
  @ID_60c90c87 = '49183F91-F101-48F6-B2BE-AEC550B2CA0E'
SET
  @Name_60c90c87 = N'Home'
SET
  @Description_60c90c87 = N'Primary residential address'
SET
  @IconClass_60c90c87 = N'fa-solid fa-house'
SET
  @DefaultRank_60c90c87 = 10
SET
  @IsActive_60c90c87 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_60c90c87,
  @Name = @Name_60c90c87,
  @Description = @Description_60c90c87,
  @IconClass = @IconClass_60c90c87,
  @DefaultRank = @DefaultRank_60c90c87,
  @IsActive = @IsActive_60c90c87;

-- Save MJ.BizApps.Common: Address Types (core SP call only)
DECLARE @ID_74a99f64 UNIQUEIDENTIFIER,
@Name_74a99f64 NVARCHAR(100),
@Description_74a99f64 NVARCHAR(MAX),
@IconClass_74a99f64 NVARCHAR(100),
@DefaultRank_74a99f64 INT,
@IsActive_74a99f64 BIT
SET
  @ID_74a99f64 = '0EFFA181-179B-4B68-ACC8-A57D55C4D73D'
SET
  @Name_74a99f64 = N'Work'
SET
  @Description_74a99f64 = N'Business or office address'
SET
  @IconClass_74a99f64 = N'fa-solid fa-building'
SET
  @DefaultRank_74a99f64 = 20
SET
  @IsActive_74a99f64 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_74a99f64,
  @Name = @Name_74a99f64,
  @Description = @Description_74a99f64,
  @IconClass = @IconClass_74a99f64,
  @DefaultRank = @DefaultRank_74a99f64,
  @IsActive = @IsActive_74a99f64;

-- Save MJ.BizApps.Common: Address Types (core SP call only)
DECLARE @ID_a96db979 UNIQUEIDENTIFIER,
@Name_a96db979 NVARCHAR(100),
@Description_a96db979 NVARCHAR(MAX),
@IconClass_a96db979 NVARCHAR(100),
@DefaultRank_a96db979 INT,
@IsActive_a96db979 BIT
SET
  @ID_a96db979 = '964C05C1-C947-467B-97B9-A7495BDDB7B0'
SET
  @Name_a96db979 = N'Mailing'
SET
  @Description_a96db979 = N'Preferred address for receiving mail and correspondence'
SET
  @IconClass_a96db979 = N'fa-solid fa-mailbox'
SET
  @DefaultRank_a96db979 = 30
SET
  @IsActive_a96db979 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_a96db979,
  @Name = @Name_a96db979,
  @Description = @Description_a96db979,
  @IconClass = @IconClass_a96db979,
  @DefaultRank = @DefaultRank_a96db979,
  @IsActive = @IsActive_a96db979;

-- Save MJ.BizApps.Common: Address Types (core SP call only)
DECLARE @ID_521bcd5d UNIQUEIDENTIFIER,
@Name_521bcd5d NVARCHAR(100),
@Description_521bcd5d NVARCHAR(MAX),
@IconClass_521bcd5d NVARCHAR(100),
@DefaultRank_521bcd5d INT,
@IsActive_521bcd5d BIT
SET
  @ID_521bcd5d = 'E2C28836-F2C2-4590-A519-BCAB0E864974'
SET
  @Name_521bcd5d = N'Billing'
SET
  @Description_521bcd5d = N'Address used for invoices and financial correspondence'
SET
  @IconClass_521bcd5d = N'fa-solid fa-file-invoice-dollar'
SET
  @DefaultRank_521bcd5d = 40
SET
  @IsActive_521bcd5d = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_521bcd5d,
  @Name = @Name_521bcd5d,
  @Description = @Description_521bcd5d,
  @IconClass = @IconClass_521bcd5d,
  @DefaultRank = @DefaultRank_521bcd5d,
  @IsActive = @IsActive_521bcd5d;

-- Save MJ.BizApps.Common: Address Types (core SP call only)
DECLARE @ID_14afec91 UNIQUEIDENTIFIER,
@Name_14afec91 NVARCHAR(100),
@Description_14afec91 NVARCHAR(MAX),
@IconClass_14afec91 NVARCHAR(100),
@DefaultRank_14afec91 INT,
@IsActive_14afec91 BIT
SET
  @ID_14afec91 = 'C466C5B0-35AE-46D6-B95E-88823E2E7EE5'
SET
  @Name_14afec91 = N'Shipping'
SET
  @Description_14afec91 = N'Address for physical deliveries'
SET
  @IconClass_14afec91 = N'fa-solid fa-truck'
SET
  @DefaultRank_14afec91 = 50
SET
  @IsActive_14afec91 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_14afec91,
  @Name = @Name_14afec91,
  @Description = @Description_14afec91,
  @IconClass = @IconClass_14afec91,
  @DefaultRank = @DefaultRank_14afec91,
  @IsActive = @IsActive_14afec91;

-- Save MJ.BizApps.Common: Address Types (core SP call only)
DECLARE @ID_0c66a7f1 UNIQUEIDENTIFIER,
@Name_0c66a7f1 NVARCHAR(100),
@Description_0c66a7f1 NVARCHAR(MAX),
@IconClass_0c66a7f1 NVARCHAR(100),
@DefaultRank_0c66a7f1 INT,
@IsActive_0c66a7f1 BIT
SET
  @ID_0c66a7f1 = '4D1E1A1A-1CD1-4069-BF1E-198F838A0DFF'
SET
  @Name_0c66a7f1 = N'Legal'
SET
  @Description_0c66a7f1 = N'Registered legal or statutory address'
SET
  @IconClass_0c66a7f1 = N'fa-solid fa-scale-balanced'
SET
  @DefaultRank_0c66a7f1 = 60
SET
  @IsActive_0c66a7f1 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_0c66a7f1,
  @Name = @Name_0c66a7f1,
  @Description = @Description_0c66a7f1,
  @IconClass = @IconClass_0c66a7f1,
  @DefaultRank = @DefaultRank_0c66a7f1,
  @IsActive = @IsActive_0c66a7f1;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_cc39671c UNIQUEIDENTIFIER,
@Name_cc39671c NVARCHAR(100),
@Description_cc39671c NVARCHAR(MAX),
@IconClass_cc39671c NVARCHAR(100),
@DisplayRank_cc39671c INT,
@IsActive_cc39671c BIT
SET
  @ID_cc39671c = 'FB4D3737-8479-44E5-AF91-2DB63311D293'
SET
  @Name_cc39671c = N'Email'
SET
  @Description_cc39671c = N'Email address'
SET
  @IconClass_cc39671c = N'fa-solid fa-envelope'
SET
  @DisplayRank_cc39671c = 10
SET
  @IsActive_cc39671c = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_cc39671c,
  @Name = @Name_cc39671c,
  @Description = @Description_cc39671c,
  @IconClass = @IconClass_cc39671c,
  @DisplayRank = @DisplayRank_cc39671c,
  @IsActive = @IsActive_cc39671c;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_ba46e0bc UNIQUEIDENTIFIER,
@Name_ba46e0bc NVARCHAR(100),
@Description_ba46e0bc NVARCHAR(MAX),
@IconClass_ba46e0bc NVARCHAR(100),
@DisplayRank_ba46e0bc INT,
@IsActive_ba46e0bc BIT
SET
  @ID_ba46e0bc = '96421246-0F8F-4CDB-A5C5-BA6B190C1AFE'
SET
  @Name_ba46e0bc = N'Mobile Phone'
SET
  @Description_ba46e0bc = N'Mobile or cell phone number'
SET
  @IconClass_ba46e0bc = N'fa-solid fa-mobile-screen'
SET
  @DisplayRank_ba46e0bc = 20
SET
  @IsActive_ba46e0bc = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_ba46e0bc,
  @Name = @Name_ba46e0bc,
  @Description = @Description_ba46e0bc,
  @IconClass = @IconClass_ba46e0bc,
  @DisplayRank = @DisplayRank_ba46e0bc,
  @IsActive = @IsActive_ba46e0bc;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_166bbfe7 UNIQUEIDENTIFIER,
@Name_166bbfe7 NVARCHAR(100),
@Description_166bbfe7 NVARCHAR(MAX),
@IconClass_166bbfe7 NVARCHAR(100),
@DisplayRank_166bbfe7 INT,
@IsActive_166bbfe7 BIT
SET
  @ID_166bbfe7 = 'BCDA98AC-06A4-40FC-A1CC-E44BB783FBC9'
SET
  @Name_166bbfe7 = N'Work Phone'
SET
  @Description_166bbfe7 = N'Business or office phone number'
SET
  @IconClass_166bbfe7 = N'fa-solid fa-phone-office'
SET
  @DisplayRank_166bbfe7 = 30
SET
  @IsActive_166bbfe7 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_166bbfe7,
  @Name = @Name_166bbfe7,
  @Description = @Description_166bbfe7,
  @IconClass = @IconClass_166bbfe7,
  @DisplayRank = @DisplayRank_166bbfe7,
  @IsActive = @IsActive_166bbfe7;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_46c6c739 UNIQUEIDENTIFIER,
@Name_46c6c739 NVARCHAR(100),
@Description_46c6c739 NVARCHAR(MAX),
@IconClass_46c6c739 NVARCHAR(100),
@DisplayRank_46c6c739 INT,
@IsActive_46c6c739 BIT
SET
  @ID_46c6c739 = 'C3BA9432-8D05-4AFE-BF6D-61F976A466E6'
SET
  @Name_46c6c739 = N'Home Phone'
SET
  @Description_46c6c739 = N'Residential phone number'
SET
  @IconClass_46c6c739 = N'fa-solid fa-phone'
SET
  @DisplayRank_46c6c739 = 40
SET
  @IsActive_46c6c739 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_46c6c739,
  @Name = @Name_46c6c739,
  @Description = @Description_46c6c739,
  @IconClass = @IconClass_46c6c739,
  @DisplayRank = @DisplayRank_46c6c739,
  @IsActive = @IsActive_46c6c739;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_6e712ec8 UNIQUEIDENTIFIER,
@Name_6e712ec8 NVARCHAR(100),
@Description_6e712ec8 NVARCHAR(MAX),
@IconClass_6e712ec8 NVARCHAR(100),
@DisplayRank_6e712ec8 INT,
@IsActive_6e712ec8 BIT
SET
  @ID_6e712ec8 = 'FDBFF502-CE06-456B-BCC3-8A2C23D16D45'
SET
  @Name_6e712ec8 = N'LinkedIn'
SET
  @Description_6e712ec8 = N'LinkedIn profile URL'
SET
  @IconClass_6e712ec8 = N'fa-brands fa-linkedin'
SET
  @DisplayRank_6e712ec8 = 50
SET
  @IsActive_6e712ec8 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_6e712ec8,
  @Name = @Name_6e712ec8,
  @Description = @Description_6e712ec8,
  @IconClass = @IconClass_6e712ec8,
  @DisplayRank = @DisplayRank_6e712ec8,
  @IsActive = @IsActive_6e712ec8;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_b5e16ec1 UNIQUEIDENTIFIER,
@Name_b5e16ec1 NVARCHAR(100),
@Description_b5e16ec1 NVARCHAR(MAX),
@IconClass_b5e16ec1 NVARCHAR(100),
@DisplayRank_b5e16ec1 INT,
@IsActive_b5e16ec1 BIT
SET
  @ID_b5e16ec1 = '02A126F9-ED1B-4BBF-8479-8B10CC916150'
SET
  @Name_b5e16ec1 = N'Twitter / X'
SET
  @Description_b5e16ec1 = N'Twitter / X profile URL or handle'
SET
  @IconClass_b5e16ec1 = N'fa-brands fa-x-twitter'
SET
  @DisplayRank_b5e16ec1 = 60
SET
  @IsActive_b5e16ec1 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_b5e16ec1,
  @Name = @Name_b5e16ec1,
  @Description = @Description_b5e16ec1,
  @IconClass = @IconClass_b5e16ec1,
  @DisplayRank = @DisplayRank_b5e16ec1,
  @IsActive = @IsActive_b5e16ec1;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_84d79e38 UNIQUEIDENTIFIER,
@Name_84d79e38 NVARCHAR(100),
@Description_84d79e38 NVARCHAR(MAX),
@IconClass_84d79e38 NVARCHAR(100),
@DisplayRank_84d79e38 INT,
@IsActive_84d79e38 BIT
SET
  @ID_84d79e38 = 'F2DBF3EA-7ACF-4725-92D3-AB630B613293'
SET
  @Name_84d79e38 = N'Website'
SET
  @Description_84d79e38 = N'Personal or professional website URL'
SET
  @IconClass_84d79e38 = N'fa-solid fa-globe'
SET
  @DisplayRank_84d79e38 = 70
SET
  @IsActive_84d79e38 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_84d79e38,
  @Name = @Name_84d79e38,
  @Description = @Description_84d79e38,
  @IconClass = @IconClass_84d79e38,
  @DisplayRank = @DisplayRank_84d79e38,
  @IsActive = @IsActive_84d79e38;

-- Save MJ.BizApps.Common: Contact Types (core SP call only)
DECLARE @ID_8071494a UNIQUEIDENTIFIER,
@Name_8071494a NVARCHAR(100),
@Description_8071494a NVARCHAR(MAX),
@IconClass_8071494a NVARCHAR(100),
@DisplayRank_8071494a INT,
@IsActive_8071494a BIT
SET
  @ID_8071494a = 'A33D19DB-27FD-400C-A9C9-F3D3C4A12E8F'
SET
  @Name_8071494a = N'Fax'
SET
  @Description_8071494a = N'Fax number'
SET
  @IconClass_8071494a = N'fa-solid fa-fax'
SET
  @DisplayRank_8071494a = 80
SET
  @IsActive_8071494a = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_8071494a,
  @Name = @Name_8071494a,
  @Description = @Description_8071494a,
  @IconClass = @IconClass_8071494a,
  @DisplayRank = @DisplayRank_8071494a,
  @IsActive = @IsActive_8071494a;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_a118dfa9 UNIQUEIDENTIFIER,
@Name_a118dfa9 NVARCHAR(100),
@Description_a118dfa9 NVARCHAR(MAX),
@IconClass_a118dfa9 NVARCHAR(100),
@DisplayRank_a118dfa9 INT,
@IsActive_a118dfa9 BIT
SET
  @ID_a118dfa9 = 'A8DB7343-DCC9-44D1-B99F-9E21024C3C2E'
SET
  @Name_a118dfa9 = N'Corporation'
SET
  @Description_a118dfa9 = N'Incorporated business entity (C-Corp, S-Corp)'
SET
  @IconClass_a118dfa9 = N'fa-solid fa-building'
SET
  @DisplayRank_a118dfa9 = 10
SET
  @IsActive_a118dfa9 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_a118dfa9,
  @Name = @Name_a118dfa9,
  @Description = @Description_a118dfa9,
  @IconClass = @IconClass_a118dfa9,
  @DisplayRank = @DisplayRank_a118dfa9,
  @IsActive = @IsActive_a118dfa9;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_6b4a6c82 UNIQUEIDENTIFIER,
@Name_6b4a6c82 NVARCHAR(100),
@Description_6b4a6c82 NVARCHAR(MAX),
@IconClass_6b4a6c82 NVARCHAR(100),
@DisplayRank_6b4a6c82 INT,
@IsActive_6b4a6c82 BIT
SET
  @ID_6b4a6c82 = '288B017D-60A4-48A7-A845-EF30B99BDBEF'
SET
  @Name_6b4a6c82 = N'LLC'
SET
  @Description_6b4a6c82 = N'Limited liability company'
SET
  @IconClass_6b4a6c82 = N'fa-solid fa-briefcase'
SET
  @DisplayRank_6b4a6c82 = 20
SET
  @IsActive_6b4a6c82 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_6b4a6c82,
  @Name = @Name_6b4a6c82,
  @Description = @Description_6b4a6c82,
  @IconClass = @IconClass_6b4a6c82,
  @DisplayRank = @DisplayRank_6b4a6c82,
  @IsActive = @IsActive_6b4a6c82;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_6f3a272e UNIQUEIDENTIFIER,
@Name_6f3a272e NVARCHAR(100),
@Description_6f3a272e NVARCHAR(MAX),
@IconClass_6f3a272e NVARCHAR(100),
@DisplayRank_6f3a272e INT,
@IsActive_6f3a272e BIT
SET
  @ID_6f3a272e = 'BAAA53F4-A8AA-4EAA-B04E-1BA6F964B341'
SET
  @Name_6f3a272e = N'Non-Profit'
SET
  @Description_6f3a272e = N'Tax-exempt non-profit organization (501(c)(3), etc.)'
SET
  @IconClass_6f3a272e = N'fa-solid fa-hand-holding-heart'
SET
  @DisplayRank_6f3a272e = 30
SET
  @IsActive_6f3a272e = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_6f3a272e,
  @Name = @Name_6f3a272e,
  @Description = @Description_6f3a272e,
  @IconClass = @IconClass_6f3a272e,
  @DisplayRank = @DisplayRank_6f3a272e,
  @IsActive = @IsActive_6f3a272e;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_e503c29d UNIQUEIDENTIFIER,
@Name_e503c29d NVARCHAR(100),
@Description_e503c29d NVARCHAR(MAX),
@IconClass_e503c29d NVARCHAR(100),
@DisplayRank_e503c29d INT,
@IsActive_e503c29d BIT
SET
  @ID_e503c29d = '1E61230B-0F48-458A-811B-66C9CF6B688E'
SET
  @Name_e503c29d = N'Government'
SET
  @Description_e503c29d = N'Government agency or department'
SET
  @IconClass_e503c29d = N'fa-solid fa-landmark'
SET
  @DisplayRank_e503c29d = 40
SET
  @IsActive_e503c29d = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_e503c29d,
  @Name = @Name_e503c29d,
  @Description = @Description_e503c29d,
  @IconClass = @IconClass_e503c29d,
  @DisplayRank = @DisplayRank_e503c29d,
  @IsActive = @IsActive_e503c29d;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_8182a375 UNIQUEIDENTIFIER,
@Name_8182a375 NVARCHAR(100),
@Description_8182a375 NVARCHAR(MAX),
@IconClass_8182a375 NVARCHAR(100),
@DisplayRank_8182a375 INT,
@IsActive_8182a375 BIT
SET
  @ID_8182a375 = '5CAB6265-CB87-4269-A321-2473160BD625'
SET
  @Name_8182a375 = N'Partnership'
SET
  @Description_8182a375 = N'General or limited partnership'
SET
  @IconClass_8182a375 = N'fa-solid fa-handshake'
SET
  @DisplayRank_8182a375 = 50
SET
  @IsActive_8182a375 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_8182a375,
  @Name = @Name_8182a375,
  @Description = @Description_8182a375,
  @IconClass = @IconClass_8182a375,
  @DisplayRank = @DisplayRank_8182a375,
  @IsActive = @IsActive_8182a375;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_2751ffb4 UNIQUEIDENTIFIER,
@Name_2751ffb4 NVARCHAR(100),
@Description_2751ffb4 NVARCHAR(MAX),
@IconClass_2751ffb4 NVARCHAR(100),
@DisplayRank_2751ffb4 INT,
@IsActive_2751ffb4 BIT
SET
  @ID_2751ffb4 = '042C63AF-93EB-4BB4-A469-F3C209F8936E'
SET
  @Name_2751ffb4 = N'Sole Proprietorship'
SET
  @Description_2751ffb4 = N'Unincorporated business owned by a single individual'
SET
  @IconClass_2751ffb4 = N'fa-solid fa-user-tie'
SET
  @DisplayRank_2751ffb4 = 60
SET
  @IsActive_2751ffb4 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_2751ffb4,
  @Name = @Name_2751ffb4,
  @Description = @Description_2751ffb4,
  @IconClass = @IconClass_2751ffb4,
  @DisplayRank = @DisplayRank_2751ffb4,
  @IsActive = @IsActive_2751ffb4;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_29918697 UNIQUEIDENTIFIER,
@Name_29918697 NVARCHAR(100),
@Description_29918697 NVARCHAR(MAX),
@IconClass_29918697 NVARCHAR(100),
@DisplayRank_29918697 INT,
@IsActive_29918697 BIT
SET
  @ID_29918697 = '7D6D1763-3198-42B2-A23C-F0FF76DAD8D2'
SET
  @Name_29918697 = N'Association'
SET
  @Description_29918697 = N'Professional or trade association'
SET
  @IconClass_29918697 = N'fa-solid fa-people-group'
SET
  @DisplayRank_29918697 = 70
SET
  @IsActive_29918697 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_29918697,
  @Name = @Name_29918697,
  @Description = @Description_29918697,
  @IconClass = @IconClass_29918697,
  @DisplayRank = @DisplayRank_29918697,
  @IsActive = @IsActive_29918697;

-- Save MJ.BizApps.Common: Organization Types (core SP call only)
DECLARE @ID_0693f099 UNIQUEIDENTIFIER,
@Name_0693f099 NVARCHAR(100),
@Description_0693f099 NVARCHAR(MAX),
@IconClass_0693f099 NVARCHAR(100),
@DisplayRank_0693f099 INT,
@IsActive_0693f099 BIT
SET
  @ID_0693f099 = '4BE0D87B-EFCB-447D-9410-FEF8EED23BC8'
SET
  @Name_0693f099 = N'Educational Institution'
SET
  @Description_0693f099 = N'School, college, university, or training organization'
SET
  @IconClass_0693f099 = N'fa-solid fa-graduation-cap'
SET
  @DisplayRank_0693f099 = 80
SET
  @IsActive_0693f099 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_0693f099,
  @Name = @Name_0693f099,
  @Description = @Description_0693f099,
  @IconClass = @IconClass_0693f099,
  @DisplayRank = @DisplayRank_0693f099,
  @IsActive = @IsActive_0693f099;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_f33134c7 UNIQUEIDENTIFIER,
@Name_f33134c7 NVARCHAR(100),
@Description_f33134c7 NVARCHAR(MAX),
@Category_f33134c7 NVARCHAR(50),
@IsDirectional_f33134c7 BIT,
@ForwardLabel_f33134c7 NVARCHAR(100),
@ReverseLabel_f33134c7 NVARCHAR(100),
@IsActive_f33134c7 BIT
SET
  @ID_f33134c7 = 'FEB33819-FC85-4309-B1EC-A54EEA91DACF'
SET
  @Name_f33134c7 = N'Spouse'
SET
  @Description_f33134c7 = N'Married or domestic partner relationship'
SET
  @Category_f33134c7 = N'PersonToPerson'
SET
  @IsDirectional_f33134c7 = 0
SET
  @ForwardLabel_f33134c7 = N'is spouse of'
SET
  @ReverseLabel_f33134c7 = N'is spouse of'
SET
  @IsActive_f33134c7 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_f33134c7,
  @Name = @Name_f33134c7,
  @Description = @Description_f33134c7,
  @Category = @Category_f33134c7,
  @IsDirectional = @IsDirectional_f33134c7,
  @ForwardLabel = @ForwardLabel_f33134c7,
  @ReverseLabel = @ReverseLabel_f33134c7,
  @IsActive = @IsActive_f33134c7;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_27c1128c UNIQUEIDENTIFIER,
@Name_27c1128c NVARCHAR(100),
@Description_27c1128c NVARCHAR(MAX),
@Category_27c1128c NVARCHAR(50),
@IsDirectional_27c1128c BIT,
@ForwardLabel_27c1128c NVARCHAR(100),
@ReverseLabel_27c1128c NVARCHAR(100),
@IsActive_27c1128c BIT
SET
  @ID_27c1128c = '431DBAF3-AC1D-47E6-B91E-264E8C76FC57'
SET
  @Name_27c1128c = N'Parent / Child'
SET
  @Description_27c1128c = N'Parent-child family relationship'
SET
  @Category_27c1128c = N'PersonToPerson'
SET
  @IsDirectional_27c1128c = 1
SET
  @ForwardLabel_27c1128c = N'is parent of'
SET
  @ReverseLabel_27c1128c = N'is child of'
SET
  @IsActive_27c1128c = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_27c1128c,
  @Name = @Name_27c1128c,
  @Description = @Description_27c1128c,
  @Category = @Category_27c1128c,
  @IsDirectional = @IsDirectional_27c1128c,
  @ForwardLabel = @ForwardLabel_27c1128c,
  @ReverseLabel = @ReverseLabel_27c1128c,
  @IsActive = @IsActive_27c1128c;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_a8aedd93 UNIQUEIDENTIFIER,
@Name_a8aedd93 NVARCHAR(100),
@Description_a8aedd93 NVARCHAR(MAX),
@Category_a8aedd93 NVARCHAR(50),
@IsDirectional_a8aedd93 BIT,
@ForwardLabel_a8aedd93 NVARCHAR(100),
@ReverseLabel_a8aedd93 NVARCHAR(100),
@IsActive_a8aedd93 BIT
SET
  @ID_a8aedd93 = 'D471B007-0717-493E-AC0D-2F102A32BCC2'
SET
  @Name_a8aedd93 = N'Sibling'
SET
  @Description_a8aedd93 = N'Brother or sister relationship'
SET
  @Category_a8aedd93 = N'PersonToPerson'
SET
  @IsDirectional_a8aedd93 = 0
SET
  @ForwardLabel_a8aedd93 = N'is sibling of'
SET
  @ReverseLabel_a8aedd93 = N'is sibling of'
SET
  @IsActive_a8aedd93 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_a8aedd93,
  @Name = @Name_a8aedd93,
  @Description = @Description_a8aedd93,
  @Category = @Category_a8aedd93,
  @IsDirectional = @IsDirectional_a8aedd93,
  @ForwardLabel = @ForwardLabel_a8aedd93,
  @ReverseLabel = @ReverseLabel_a8aedd93,
  @IsActive = @IsActive_a8aedd93;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_87479e89 UNIQUEIDENTIFIER,
@Name_87479e89 NVARCHAR(100),
@Description_87479e89 NVARCHAR(MAX),
@Category_87479e89 NVARCHAR(50),
@IsDirectional_87479e89 BIT,
@ForwardLabel_87479e89 NVARCHAR(100),
@ReverseLabel_87479e89 NVARCHAR(100),
@IsActive_87479e89 BIT
SET
  @ID_87479e89 = '6A17A929-8B23-4D73-9DF9-A368E7C1C1B9'
SET
  @Name_87479e89 = N'Friend'
SET
  @Description_87479e89 = N'Personal friendship'
SET
  @Category_87479e89 = N'PersonToPerson'
SET
  @IsDirectional_87479e89 = 0
SET
  @ForwardLabel_87479e89 = N'is friend of'
SET
  @ReverseLabel_87479e89 = N'is friend of'
SET
  @IsActive_87479e89 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_87479e89,
  @Name = @Name_87479e89,
  @Description = @Description_87479e89,
  @Category = @Category_87479e89,
  @IsDirectional = @IsDirectional_87479e89,
  @ForwardLabel = @ForwardLabel_87479e89,
  @ReverseLabel = @ReverseLabel_87479e89,
  @IsActive = @IsActive_87479e89;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_a96fa76a UNIQUEIDENTIFIER,
@Name_a96fa76a NVARCHAR(100),
@Description_a96fa76a NVARCHAR(MAX),
@Category_a96fa76a NVARCHAR(50),
@IsDirectional_a96fa76a BIT,
@ForwardLabel_a96fa76a NVARCHAR(100),
@ReverseLabel_a96fa76a NVARCHAR(100),
@IsActive_a96fa76a BIT
SET
  @ID_a96fa76a = '27CFD031-5663-4000-A7AB-8AC87DB88C1D'
SET
  @Name_a96fa76a = N'Employee'
SET
  @Description_a96fa76a = N'Employment relationship between a person and an organization'
SET
  @Category_a96fa76a = N'PersonToOrganization'
SET
  @IsDirectional_a96fa76a = 1
SET
  @ForwardLabel_a96fa76a = N'is employee of'
SET
  @ReverseLabel_a96fa76a = N'employs'
SET
  @IsActive_a96fa76a = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_a96fa76a,
  @Name = @Name_a96fa76a,
  @Description = @Description_a96fa76a,
  @Category = @Category_a96fa76a,
  @IsDirectional = @IsDirectional_a96fa76a,
  @ForwardLabel = @ForwardLabel_a96fa76a,
  @ReverseLabel = @ReverseLabel_a96fa76a,
  @IsActive = @IsActive_a96fa76a;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_50f5fd9c UNIQUEIDENTIFIER,
@Name_50f5fd9c NVARCHAR(100),
@Description_50f5fd9c NVARCHAR(MAX),
@Category_50f5fd9c NVARCHAR(50),
@IsDirectional_50f5fd9c BIT,
@ForwardLabel_50f5fd9c NVARCHAR(100),
@ReverseLabel_50f5fd9c NVARCHAR(100),
@IsActive_50f5fd9c BIT
SET
  @ID_50f5fd9c = '2FE33D05-5FD0-4076-8EF2-A30A640651B4'
SET
  @Name_50f5fd9c = N'Board Member'
SET
  @Description_50f5fd9c = N'Person serves on the board of directors of an organization'
SET
  @Category_50f5fd9c = N'PersonToOrganization'
SET
  @IsDirectional_50f5fd9c = 1
SET
  @ForwardLabel_50f5fd9c = N'is board member of'
SET
  @ReverseLabel_50f5fd9c = N'has board member'
SET
  @IsActive_50f5fd9c = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_50f5fd9c,
  @Name = @Name_50f5fd9c,
  @Description = @Description_50f5fd9c,
  @Category = @Category_50f5fd9c,
  @IsDirectional = @IsDirectional_50f5fd9c,
  @ForwardLabel = @ForwardLabel_50f5fd9c,
  @ReverseLabel = @ReverseLabel_50f5fd9c,
  @IsActive = @IsActive_50f5fd9c;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_1d81f74c UNIQUEIDENTIFIER,
@Name_1d81f74c NVARCHAR(100),
@Description_1d81f74c NVARCHAR(MAX),
@Category_1d81f74c NVARCHAR(50),
@IsDirectional_1d81f74c BIT,
@ForwardLabel_1d81f74c NVARCHAR(100),
@ReverseLabel_1d81f74c NVARCHAR(100),
@IsActive_1d81f74c BIT
SET
  @ID_1d81f74c = '5B8C871C-025B-410A-9D44-4D30C76534C7'
SET
  @Name_1d81f74c = N'Member'
SET
  @Description_1d81f74c = N'Person is a member of an organization or association'
SET
  @Category_1d81f74c = N'PersonToOrganization'
SET
  @IsDirectional_1d81f74c = 1
SET
  @ForwardLabel_1d81f74c = N'is member of'
SET
  @ReverseLabel_1d81f74c = N'has member'
SET
  @IsActive_1d81f74c = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_1d81f74c,
  @Name = @Name_1d81f74c,
  @Description = @Description_1d81f74c,
  @Category = @Category_1d81f74c,
  @IsDirectional = @IsDirectional_1d81f74c,
  @ForwardLabel = @ForwardLabel_1d81f74c,
  @ReverseLabel = @ReverseLabel_1d81f74c,
  @IsActive = @IsActive_1d81f74c;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_65970596 UNIQUEIDENTIFIER,
@Name_65970596 NVARCHAR(100),
@Description_65970596 NVARCHAR(MAX),
@Category_65970596 NVARCHAR(50),
@IsDirectional_65970596 BIT,
@ForwardLabel_65970596 NVARCHAR(100),
@ReverseLabel_65970596 NVARCHAR(100),
@IsActive_65970596 BIT
SET
  @ID_65970596 = 'DF72DDBB-A829-41AC-8698-01FCCD21FEEF'
SET
  @Name_65970596 = N'Volunteer'
SET
  @Description_65970596 = N'Person volunteers for an organization'
SET
  @Category_65970596 = N'PersonToOrganization'
SET
  @IsDirectional_65970596 = 1
SET
  @ForwardLabel_65970596 = N'volunteers for'
SET
  @ReverseLabel_65970596 = N'has volunteer'
SET
  @IsActive_65970596 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_65970596,
  @Name = @Name_65970596,
  @Description = @Description_65970596,
  @Category = @Category_65970596,
  @IsDirectional = @IsDirectional_65970596,
  @ForwardLabel = @ForwardLabel_65970596,
  @ReverseLabel = @ReverseLabel_65970596,
  @IsActive = @IsActive_65970596;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_bea89efa UNIQUEIDENTIFIER,
@Name_bea89efa NVARCHAR(100),
@Description_bea89efa NVARCHAR(MAX),
@Category_bea89efa NVARCHAR(50),
@IsDirectional_bea89efa BIT,
@ForwardLabel_bea89efa NVARCHAR(100),
@ReverseLabel_bea89efa NVARCHAR(100),
@IsActive_bea89efa BIT
SET
  @ID_bea89efa = 'DC06CB0C-A6CE-437C-A19E-F615F949BC51'
SET
  @Name_bea89efa = N'Customer'
SET
  @Description_bea89efa = N'Person is a customer or client of an organization'
SET
  @Category_bea89efa = N'PersonToOrganization'
SET
  @IsDirectional_bea89efa = 1
SET
  @ForwardLabel_bea89efa = N'is customer of'
SET
  @ReverseLabel_bea89efa = N'has customer'
SET
  @IsActive_bea89efa = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_bea89efa,
  @Name = @Name_bea89efa,
  @Description = @Description_bea89efa,
  @Category = @Category_bea89efa,
  @IsDirectional = @IsDirectional_bea89efa,
  @ForwardLabel = @ForwardLabel_bea89efa,
  @ReverseLabel = @ReverseLabel_bea89efa,
  @IsActive = @IsActive_bea89efa;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_a34febf3 UNIQUEIDENTIFIER,
@Name_a34febf3 NVARCHAR(100),
@Description_a34febf3 NVARCHAR(MAX),
@Category_a34febf3 NVARCHAR(50),
@IsDirectional_a34febf3 BIT,
@ForwardLabel_a34febf3 NVARCHAR(100),
@ReverseLabel_a34febf3 NVARCHAR(100),
@IsActive_a34febf3 BIT
SET
  @ID_a34febf3 = '6BF6959D-18B4-4615-AFCE-643963A87C1B'
SET
  @Name_a34febf3 = N'Consultant'
SET
  @Description_a34febf3 = N'Person provides consulting services to an organization'
SET
  @Category_a34febf3 = N'PersonToOrganization'
SET
  @IsDirectional_a34febf3 = 1
SET
  @ForwardLabel_a34febf3 = N'consults for'
SET
  @ReverseLabel_a34febf3 = N'has consultant'
SET
  @IsActive_a34febf3 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_a34febf3,
  @Name = @Name_a34febf3,
  @Description = @Description_a34febf3,
  @Category = @Category_a34febf3,
  @IsDirectional = @IsDirectional_a34febf3,
  @ForwardLabel = @ForwardLabel_a34febf3,
  @ReverseLabel = @ReverseLabel_a34febf3,
  @IsActive = @IsActive_a34febf3;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_73d74097 UNIQUEIDENTIFIER,
@Name_73d74097 NVARCHAR(100),
@Description_73d74097 NVARCHAR(MAX),
@Category_73d74097 NVARCHAR(50),
@IsDirectional_73d74097 BIT,
@ForwardLabel_73d74097 NVARCHAR(100),
@ReverseLabel_73d74097 NVARCHAR(100),
@IsActive_73d74097 BIT
SET
  @ID_73d74097 = '39373681-5C70-4845-896B-4BFE4343751F'
SET
  @Name_73d74097 = N'Subsidiary'
SET
  @Description_73d74097 = N'One organization is a subsidiary or division of another'
SET
  @Category_73d74097 = N'OrganizationToOrganization'
SET
  @IsDirectional_73d74097 = 1
SET
  @ForwardLabel_73d74097 = N'is subsidiary of'
SET
  @ReverseLabel_73d74097 = N'has subsidiary'
SET
  @IsActive_73d74097 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_73d74097,
  @Name = @Name_73d74097,
  @Description = @Description_73d74097,
  @Category = @Category_73d74097,
  @IsDirectional = @IsDirectional_73d74097,
  @ForwardLabel = @ForwardLabel_73d74097,
  @ReverseLabel = @ReverseLabel_73d74097,
  @IsActive = @IsActive_73d74097;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_46664ac9 UNIQUEIDENTIFIER,
@Name_46664ac9 NVARCHAR(100),
@Description_46664ac9 NVARCHAR(MAX),
@Category_46664ac9 NVARCHAR(50),
@IsDirectional_46664ac9 BIT,
@ForwardLabel_46664ac9 NVARCHAR(100),
@ReverseLabel_46664ac9 NVARCHAR(100),
@IsActive_46664ac9 BIT
SET
  @ID_46664ac9 = 'CA9BBDBE-3595-4C3F-80FF-DA78D3389EA7'
SET
  @Name_46664ac9 = N'Partner'
SET
  @Description_46664ac9 = N'Strategic or business partnership between organizations'
SET
  @Category_46664ac9 = N'OrganizationToOrganization'
SET
  @IsDirectional_46664ac9 = 0
SET
  @ForwardLabel_46664ac9 = N'is partner of'
SET
  @ReverseLabel_46664ac9 = N'is partner of'
SET
  @IsActive_46664ac9 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_46664ac9,
  @Name = @Name_46664ac9,
  @Description = @Description_46664ac9,
  @Category = @Category_46664ac9,
  @IsDirectional = @IsDirectional_46664ac9,
  @ForwardLabel = @ForwardLabel_46664ac9,
  @ReverseLabel = @ReverseLabel_46664ac9,
  @IsActive = @IsActive_46664ac9;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_a923187c UNIQUEIDENTIFIER,
@Name_a923187c NVARCHAR(100),
@Description_a923187c NVARCHAR(MAX),
@Category_a923187c NVARCHAR(50),
@IsDirectional_a923187c BIT,
@ForwardLabel_a923187c NVARCHAR(100),
@ReverseLabel_a923187c NVARCHAR(100),
@IsActive_a923187c BIT
SET
  @ID_a923187c = '190A8BBF-771E-4631-980A-84918311E5EC'
SET
  @Name_a923187c = N'Vendor'
SET
  @Description_a923187c = N'One organization supplies goods or services to another'
SET
  @Category_a923187c = N'OrganizationToOrganization'
SET
  @IsDirectional_a923187c = 1
SET
  @ForwardLabel_a923187c = N'is vendor to'
SET
  @ReverseLabel_a923187c = N'has vendor'
SET
  @IsActive_a923187c = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_a923187c,
  @Name = @Name_a923187c,
  @Description = @Description_a923187c,
  @Category = @Category_a923187c,
  @IsDirectional = @IsDirectional_a923187c,
  @ForwardLabel = @ForwardLabel_a923187c,
  @ReverseLabel = @ReverseLabel_a923187c,
  @IsActive = @IsActive_a923187c;

-- Save MJ.BizApps.Common: Relationship Types (core SP call only)
DECLARE @ID_f8560a51 UNIQUEIDENTIFIER,
@Name_f8560a51 NVARCHAR(100),
@Description_f8560a51 NVARCHAR(MAX),
@Category_f8560a51 NVARCHAR(50),
@IsDirectional_f8560a51 BIT,
@ForwardLabel_f8560a51 NVARCHAR(100),
@ReverseLabel_f8560a51 NVARCHAR(100),
@IsActive_f8560a51 BIT
SET
  @ID_f8560a51 = '2DBA78A6-DF6F-4A7E-B126-AE038BD3B6BA'
SET
  @Name_f8560a51 = N'Affiliate'
SET
  @Description_f8560a51 = N'Formal affiliation between two organizations'
SET
  @Category_f8560a51 = N'OrganizationToOrganization'
SET
  @IsDirectional_f8560a51 = 0
SET
  @ForwardLabel_f8560a51 = N'is affiliate of'
SET
  @ReverseLabel_f8560a51 = N'is affiliate of'
SET
  @IsActive_f8560a51 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_f8560a51,
  @Name = @Name_f8560a51,
  @Description = @Description_f8560a51,
  @Category = @Category_f8560a51,
  @IsDirectional = @IsDirectional_f8560a51,
  @ForwardLabel = @ForwardLabel_f8560a51,
  @ReverseLabel = @ReverseLabel_f8560a51,
  @IsActive = @IsActive_f8560a51;

-- Save MJ: Entities (core SP call only)
DECLARE @ParentID_1e165c1a UNIQUEIDENTIFIER,
@Name_1e165c1a NVARCHAR(255),
@NameSuffix_1e165c1a NVARCHAR(255),
@Description_1e165c1a NVARCHAR(MAX),
@AutoUpdateDescription_1e165c1a BIT,
@BaseView_1e165c1a NVARCHAR(255),
@BaseViewGenerated_1e165c1a BIT,
@VirtualEntity_1e165c1a BIT,
@TrackRecordChanges_1e165c1a BIT,
@AuditRecordAccess_1e165c1a BIT,
@AuditViewRuns_1e165c1a BIT,
@IncludeInAPI_1e165c1a BIT,
@AllowAllRowsAPI_1e165c1a BIT,
@AllowUpdateAPI_1e165c1a BIT,
@AllowCreateAPI_1e165c1a BIT,
@AllowDeleteAPI_1e165c1a BIT,
@CustomResolverAPI_1e165c1a BIT,
@AllowUserSearchAPI_1e165c1a BIT,
@FullTextSearchEnabled_1e165c1a BIT,
@FullTextCatalog_1e165c1a NVARCHAR(255),
@FullTextCatalogGenerated_1e165c1a BIT,
@FullTextIndex_1e165c1a NVARCHAR(255),
@FullTextIndexGenerated_1e165c1a BIT,
@FullTextSearchFunction_1e165c1a NVARCHAR(255),
@FullTextSearchFunctionGenerated_1e165c1a BIT,
@UserViewMaxRows_1e165c1a INT,
@spCreate_1e165c1a NVARCHAR(255),
@spUpdate_1e165c1a NVARCHAR(255),
@spDelete_1e165c1a NVARCHAR(255),
@spCreateGenerated_1e165c1a BIT,
@spUpdateGenerated_1e165c1a BIT,
@spDeleteGenerated_1e165c1a BIT,
@CascadeDeletes_1e165c1a BIT,
@DeleteType_1e165c1a NVARCHAR(10),
@AllowRecordMerge_1e165c1a BIT,
@spMatch_1e165c1a NVARCHAR(255),
@RelationshipDefaultDisplayType_1e165c1a NVARCHAR(20),
@UserFormGenerated_1e165c1a BIT,
@EntityObjectSubclassName_1e165c1a NVARCHAR(255),
@EntityObjectSubclassImport_1e165c1a NVARCHAR(255),
@PreferredCommunicationField_1e165c1a NVARCHAR(255),
@Icon_1e165c1a NVARCHAR(500),
@ScopeDefault_1e165c1a NVARCHAR(100),
@RowsToPackWithSchema_1e165c1a NVARCHAR(20),
@RowsToPackSampleMethod_1e165c1a NVARCHAR(20),
@RowsToPackSampleCount_1e165c1a INT,
@RowsToPackSampleOrder_1e165c1a NVARCHAR(MAX),
@AutoRowCountFrequency_1e165c1a INT,
@RowCount_1e165c1a BIGINT,
@RowCountRunAt_1e165c1a DATETIMEOFFSET,
@Status_1e165c1a NVARCHAR(25),
@DisplayName_1e165c1a NVARCHAR(255),
@AllowMultipleSubtypes_1e165c1a BIT,
@ID_1e165c1a UNIQUEIDENTIFIER
SET
  @Name_1e165c1a = N'MJ.BizApps.Common: People'
SET
  @Description_1e165c1a = N'Individual people, optionally linked to MJ system user accounts'
SET
  @AutoUpdateDescription_1e165c1a = 1
SET
  @BaseView_1e165c1a = N'vwPeopleExtended'
SET
  @BaseViewGenerated_1e165c1a = 0
SET
  @VirtualEntity_1e165c1a = 0
SET
  @TrackRecordChanges_1e165c1a = 1
SET
  @AuditRecordAccess_1e165c1a = 0
SET
  @AuditViewRuns_1e165c1a = 0
SET
  @IncludeInAPI_1e165c1a = 1
SET
  @AllowAllRowsAPI_1e165c1a = 0
SET
  @AllowUpdateAPI_1e165c1a = 1
SET
  @AllowCreateAPI_1e165c1a = 1
SET
  @AllowDeleteAPI_1e165c1a = 1
SET
  @CustomResolverAPI_1e165c1a = 0
SET
  @AllowUserSearchAPI_1e165c1a = 0
SET
  @FullTextSearchEnabled_1e165c1a = 0
SET
  @FullTextCatalogGenerated_1e165c1a = 1
SET
  @FullTextIndexGenerated_1e165c1a = 1
SET
  @FullTextSearchFunctionGenerated_1e165c1a = 1
SET
  @UserViewMaxRows_1e165c1a = 1000
SET
  @spCreateGenerated_1e165c1a = 1
SET
  @spUpdateGenerated_1e165c1a = 1
SET
  @spDeleteGenerated_1e165c1a = 1
SET
  @CascadeDeletes_1e165c1a = 0
SET
  @DeleteType_1e165c1a = N'Hard'
SET
  @AllowRecordMerge_1e165c1a = 0
SET
  @RelationshipDefaultDisplayType_1e165c1a = N'Search'
SET
  @UserFormGenerated_1e165c1a = 1
SET
  @Icon_1e165c1a = N'fa fa-users'
SET
  @RowsToPackWithSchema_1e165c1a = N'None'
SET
  @RowsToPackSampleMethod_1e165c1a = N'random'
SET
  @RowsToPackSampleCount_1e165c1a = 0
SET
  @Status_1e165c1a = N'Active'
SET
  @DisplayName_1e165c1a = N'People'
SET
  @AllowMultipleSubtypes_1e165c1a = 0
SET
  @ID_1e165c1a = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
EXEC [__mj].spUpdateEntity @ParentID = @ParentID_1e165c1a,
  @Name = @Name_1e165c1a,
  @NameSuffix = @NameSuffix_1e165c1a,
  @Description = @Description_1e165c1a,
  @AutoUpdateDescription = @AutoUpdateDescription_1e165c1a,
  @BaseView = @BaseView_1e165c1a,
  @BaseViewGenerated = @BaseViewGenerated_1e165c1a,
  @VirtualEntity = @VirtualEntity_1e165c1a,
  @TrackRecordChanges = @TrackRecordChanges_1e165c1a,
  @AuditRecordAccess = @AuditRecordAccess_1e165c1a,
  @AuditViewRuns = @AuditViewRuns_1e165c1a,
  @IncludeInAPI = @IncludeInAPI_1e165c1a,
  @AllowAllRowsAPI = @AllowAllRowsAPI_1e165c1a,
  @AllowUpdateAPI = @AllowUpdateAPI_1e165c1a,
  @AllowCreateAPI = @AllowCreateAPI_1e165c1a,
  @AllowDeleteAPI = @AllowDeleteAPI_1e165c1a,
  @CustomResolverAPI = @CustomResolverAPI_1e165c1a,
  @AllowUserSearchAPI = @AllowUserSearchAPI_1e165c1a,
  @FullTextSearchEnabled = @FullTextSearchEnabled_1e165c1a,
  @FullTextCatalog = @FullTextCatalog_1e165c1a,
  @FullTextCatalogGenerated = @FullTextCatalogGenerated_1e165c1a,
  @FullTextIndex = @FullTextIndex_1e165c1a,
  @FullTextIndexGenerated = @FullTextIndexGenerated_1e165c1a,
  @FullTextSearchFunction = @FullTextSearchFunction_1e165c1a,
  @FullTextSearchFunctionGenerated = @FullTextSearchFunctionGenerated_1e165c1a,
  @UserViewMaxRows = @UserViewMaxRows_1e165c1a,
  @spCreate = @spCreate_1e165c1a,
  @spUpdate = @spUpdate_1e165c1a,
  @spDelete = @spDelete_1e165c1a,
  @spCreateGenerated = @spCreateGenerated_1e165c1a,
  @spUpdateGenerated = @spUpdateGenerated_1e165c1a,
  @spDeleteGenerated = @spDeleteGenerated_1e165c1a,
  @CascadeDeletes = @CascadeDeletes_1e165c1a,
  @DeleteType = @DeleteType_1e165c1a,
  @AllowRecordMerge = @AllowRecordMerge_1e165c1a,
  @spMatch = @spMatch_1e165c1a,
  @RelationshipDefaultDisplayType = @RelationshipDefaultDisplayType_1e165c1a,
  @UserFormGenerated = @UserFormGenerated_1e165c1a,
  @EntityObjectSubclassName = @EntityObjectSubclassName_1e165c1a,
  @EntityObjectSubclassImport = @EntityObjectSubclassImport_1e165c1a,
  @PreferredCommunicationField = @PreferredCommunicationField_1e165c1a,
  @Icon = @Icon_1e165c1a,
  @ScopeDefault = @ScopeDefault_1e165c1a,
  @RowsToPackWithSchema = @RowsToPackWithSchema_1e165c1a,
  @RowsToPackSampleMethod = @RowsToPackSampleMethod_1e165c1a,
  @RowsToPackSampleCount = @RowsToPackSampleCount_1e165c1a,
  @RowsToPackSampleOrder = @RowsToPackSampleOrder_1e165c1a,
  @AutoRowCountFrequency = @AutoRowCountFrequency_1e165c1a,
  @RowCount = @RowCount_1e165c1a,
  @RowCountRunAt = @RowCountRunAt_1e165c1a,
  @Status = @Status_1e165c1a,
  @DisplayName = @DisplayName_1e165c1a,
  @AllowMultipleSubtypes = @AllowMultipleSubtypes_1e165c1a,
  @ID = @ID_1e165c1a;

-- Save MJ: Entities (core SP call only)
DECLARE @ParentID_15513a0a UNIQUEIDENTIFIER,
@Name_15513a0a NVARCHAR(255),
@NameSuffix_15513a0a NVARCHAR(255),
@Description_15513a0a NVARCHAR(MAX),
@AutoUpdateDescription_15513a0a BIT,
@BaseView_15513a0a NVARCHAR(255),
@BaseViewGenerated_15513a0a BIT,
@VirtualEntity_15513a0a BIT,
@TrackRecordChanges_15513a0a BIT,
@AuditRecordAccess_15513a0a BIT,
@AuditViewRuns_15513a0a BIT,
@IncludeInAPI_15513a0a BIT,
@AllowAllRowsAPI_15513a0a BIT,
@AllowUpdateAPI_15513a0a BIT,
@AllowCreateAPI_15513a0a BIT,
@AllowDeleteAPI_15513a0a BIT,
@CustomResolverAPI_15513a0a BIT,
@AllowUserSearchAPI_15513a0a BIT,
@FullTextSearchEnabled_15513a0a BIT,
@FullTextCatalog_15513a0a NVARCHAR(255),
@FullTextCatalogGenerated_15513a0a BIT,
@FullTextIndex_15513a0a NVARCHAR(255),
@FullTextIndexGenerated_15513a0a BIT,
@FullTextSearchFunction_15513a0a NVARCHAR(255),
@FullTextSearchFunctionGenerated_15513a0a BIT,
@UserViewMaxRows_15513a0a INT,
@spCreate_15513a0a NVARCHAR(255),
@spUpdate_15513a0a NVARCHAR(255),
@spDelete_15513a0a NVARCHAR(255),
@spCreateGenerated_15513a0a BIT,
@spUpdateGenerated_15513a0a BIT,
@spDeleteGenerated_15513a0a BIT,
@CascadeDeletes_15513a0a BIT,
@DeleteType_15513a0a NVARCHAR(10),
@AllowRecordMerge_15513a0a BIT,
@spMatch_15513a0a NVARCHAR(255),
@RelationshipDefaultDisplayType_15513a0a NVARCHAR(20),
@UserFormGenerated_15513a0a BIT,
@EntityObjectSubclassName_15513a0a NVARCHAR(255),
@EntityObjectSubclassImport_15513a0a NVARCHAR(255),
@PreferredCommunicationField_15513a0a NVARCHAR(255),
@Icon_15513a0a NVARCHAR(500),
@ScopeDefault_15513a0a NVARCHAR(100),
@RowsToPackWithSchema_15513a0a NVARCHAR(20),
@RowsToPackSampleMethod_15513a0a NVARCHAR(20),
@RowsToPackSampleCount_15513a0a INT,
@RowsToPackSampleOrder_15513a0a NVARCHAR(MAX),
@AutoRowCountFrequency_15513a0a INT,
@RowCount_15513a0a BIGINT,
@RowCountRunAt_15513a0a DATETIMEOFFSET,
@Status_15513a0a NVARCHAR(25),
@DisplayName_15513a0a NVARCHAR(255),
@AllowMultipleSubtypes_15513a0a BIT,
@ID_15513a0a UNIQUEIDENTIFIER
SET
  @Name_15513a0a = N'MJ.BizApps.Common: Organizations'
SET
  @Description_15513a0a = N'Companies, associations, government bodies, and other organizations with hierarchy support'
SET
  @AutoUpdateDescription_15513a0a = 1
SET
  @BaseView_15513a0a = N'vwOrganizationsExtended'
SET
  @BaseViewGenerated_15513a0a = 0
SET
  @VirtualEntity_15513a0a = 0
SET
  @TrackRecordChanges_15513a0a = 1
SET
  @AuditRecordAccess_15513a0a = 0
SET
  @AuditViewRuns_15513a0a = 0
SET
  @IncludeInAPI_15513a0a = 1
SET
  @AllowAllRowsAPI_15513a0a = 0
SET
  @AllowUpdateAPI_15513a0a = 1
SET
  @AllowCreateAPI_15513a0a = 1
SET
  @AllowDeleteAPI_15513a0a = 1
SET
  @CustomResolverAPI_15513a0a = 0
SET
  @AllowUserSearchAPI_15513a0a = 0
SET
  @FullTextSearchEnabled_15513a0a = 0
SET
  @FullTextCatalogGenerated_15513a0a = 1
SET
  @FullTextIndexGenerated_15513a0a = 1
SET
  @FullTextSearchFunctionGenerated_15513a0a = 1
SET
  @UserViewMaxRows_15513a0a = 1000
SET
  @spCreateGenerated_15513a0a = 1
SET
  @spUpdateGenerated_15513a0a = 1
SET
  @spDeleteGenerated_15513a0a = 1
SET
  @CascadeDeletes_15513a0a = 0
SET
  @DeleteType_15513a0a = N'Hard'
SET
  @AllowRecordMerge_15513a0a = 0
SET
  @RelationshipDefaultDisplayType_15513a0a = N'Search'
SET
  @UserFormGenerated_15513a0a = 1
SET
  @Icon_15513a0a = N'fa fa-building'
SET
  @RowsToPackWithSchema_15513a0a = N'None'
SET
  @RowsToPackSampleMethod_15513a0a = N'random'
SET
  @RowsToPackSampleCount_15513a0a = 0
SET
  @Status_15513a0a = N'Active'
SET
  @DisplayName_15513a0a = N'Organizations'
SET
  @AllowMultipleSubtypes_15513a0a = 0
SET
  @ID_15513a0a = 'C70448F9-9792-41D7-A82C-784B66429D54'
EXEC [__mj].spUpdateEntity @ParentID = @ParentID_15513a0a,
  @Name = @Name_15513a0a,
  @NameSuffix = @NameSuffix_15513a0a,
  @Description = @Description_15513a0a,
  @AutoUpdateDescription = @AutoUpdateDescription_15513a0a,
  @BaseView = @BaseView_15513a0a,
  @BaseViewGenerated = @BaseViewGenerated_15513a0a,
  @VirtualEntity = @VirtualEntity_15513a0a,
  @TrackRecordChanges = @TrackRecordChanges_15513a0a,
  @AuditRecordAccess = @AuditRecordAccess_15513a0a,
  @AuditViewRuns = @AuditViewRuns_15513a0a,
  @IncludeInAPI = @IncludeInAPI_15513a0a,
  @AllowAllRowsAPI = @AllowAllRowsAPI_15513a0a,
  @AllowUpdateAPI = @AllowUpdateAPI_15513a0a,
  @AllowCreateAPI = @AllowCreateAPI_15513a0a,
  @AllowDeleteAPI = @AllowDeleteAPI_15513a0a,
  @CustomResolverAPI = @CustomResolverAPI_15513a0a,
  @AllowUserSearchAPI = @AllowUserSearchAPI_15513a0a,
  @FullTextSearchEnabled = @FullTextSearchEnabled_15513a0a,
  @FullTextCatalog = @FullTextCatalog_15513a0a,
  @FullTextCatalogGenerated = @FullTextCatalogGenerated_15513a0a,
  @FullTextIndex = @FullTextIndex_15513a0a,
  @FullTextIndexGenerated = @FullTextIndexGenerated_15513a0a,
  @FullTextSearchFunction = @FullTextSearchFunction_15513a0a,
  @FullTextSearchFunctionGenerated = @FullTextSearchFunctionGenerated_15513a0a,
  @UserViewMaxRows = @UserViewMaxRows_15513a0a,
  @spCreate = @spCreate_15513a0a,
  @spUpdate = @spUpdate_15513a0a,
  @spDelete = @spDelete_15513a0a,
  @spCreateGenerated = @spCreateGenerated_15513a0a,
  @spUpdateGenerated = @spUpdateGenerated_15513a0a,
  @spDeleteGenerated = @spDeleteGenerated_15513a0a,
  @CascadeDeletes = @CascadeDeletes_15513a0a,
  @DeleteType = @DeleteType_15513a0a,
  @AllowRecordMerge = @AllowRecordMerge_15513a0a,
  @spMatch = @spMatch_15513a0a,
  @RelationshipDefaultDisplayType = @RelationshipDefaultDisplayType_15513a0a,
  @UserFormGenerated = @UserFormGenerated_15513a0a,
  @EntityObjectSubclassName = @EntityObjectSubclassName_15513a0a,
  @EntityObjectSubclassImport = @EntityObjectSubclassImport_15513a0a,
  @PreferredCommunicationField = @PreferredCommunicationField_15513a0a,
  @Icon = @Icon_15513a0a,
  @ScopeDefault = @ScopeDefault_15513a0a,
  @RowsToPackWithSchema = @RowsToPackWithSchema_15513a0a,
  @RowsToPackSampleMethod = @RowsToPackSampleMethod_15513a0a,
  @RowsToPackSampleCount = @RowsToPackSampleCount_15513a0a,
  @RowsToPackSampleOrder = @RowsToPackSampleOrder_15513a0a,
  @AutoRowCountFrequency = @AutoRowCountFrequency_15513a0a,
  @RowCount = @RowCount_15513a0a,
  @RowCountRunAt = @RowCountRunAt_15513a0a,
  @Status = @Status_15513a0a,
  @DisplayName = @DisplayName_15513a0a,
  @AllowMultipleSubtypes = @AllowMultipleSubtypes_15513a0a,
  @ID = @ID_15513a0a;


-- End of SQL Logging Session
-- Session ID: d6b72475-9e96-4e91-9f5d-797774484bd4
-- Completed: 2026-02-27T21:33:46.761Z
-- Duration: 6235ms
-- Total Statements: 39
