-- =============================================================================
-- Migration: V202609231303__v5.46.x__Address_Line1_City_Nullable.sql
-- Description: Make Address.Line1 and Address.City nullable so an address row
--              may record a location (country, region, postal code) before a
--              street line and city are known. Additive: existing rows keep
--              their values; types and lengths are unchanged.
--              Hand-authored DDL only. Do NOT UPDATE EntityField here — CodeGen
--              reconciles AllowsNull from the column and regenerates CRUD procs.
--              After CodeGen, this file is completed as:
--                DDL → 50 blank lines → inlined R__RefreshMetadata → 50 blank
--                lines → CODEGEN banner → CodeGen SQL emit.
--              Authoring order: apply DDL, run CodeGen, THEN append R + emit.
--              Replay order: DDL, R (heal metadata), CodeGen emit (SPs).
-- =============================================================================

-- 1) Columns
ALTER TABLE [${flyway:defaultSchema}].[Address] ALTER COLUMN [Line1] NVARCHAR(255) NULL;
GO
ALTER TABLE [${flyway:defaultSchema}].[Address] ALTER COLUMN [City] NVARCHAR(100) NULL;
GO

-- 2) Extended properties (column docs; not EntityField rows)
EXEC sp_updateextendedproperty @name = N'MS_Description', @value = N'Street address line 1. Optional: an address may record only a location (country, region, postal code) before a street line is known.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'Address', @level2type = N'COLUMN', @level2name = N'Line1';
GO
EXEC sp_updateextendedproperty @name = N'MS_Description', @value = N'City or locality name. Optional: an address may record only a location (country, region, postal code) before a city is known.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'Address', @level2type = N'COLUMN', @level2name = N'City';
GO


















































/* ==============================================================================================
   METADATA REFRESH — inlined copy of MJ/migrations/R__RefreshMetadata.sql
   (minus ${flyway:timestamp}, which exists only to churn the repeatable checksum).

   Why this is here: Flyway runs every versioned migration before any R__ script.
   The ALTER COLUMN above lands first. CodeGen (below) was authored against that
   DDL with EntityField.AllowsNull still 0 for Line1/City, so it regenerated the
   Address CRUD procedures. On REPLAY, this refresh runs AFTER the ALTER and BEFORE
   the CodeGen emit so metadata (AllowsNull, views) matches what the emit assumes.

   EXEC target is ${mjSchema} (__mj) — these stored procedures live in MJ core, not
   this app schema. Verbatim R__ bodies minus timestamp; ${flyway:defaultSchema}
   in the original R file is MJ core, here replaced with ${mjSchema}.

   spDeleteUnneededEntityFields is omitted: it is a live reconciler that must not
   run from a replayable versioned migration (check-migration-no-prune.mjs), and
   this change removes no columns, so it has nothing to prune here.
   ============================================================================================== */

/* SQL text to recompile all views (dependency order: inner layered views before g.* wrappers) */
EXEC [${mjSchema}].spRecompileAllViews
GO

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].spUpdateExistingEntitiesFromSchema @ExcludedSchemaNames='sys,staging'
GO

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].spUpdateSchemaInfoFromDatabase @ExcludedSchemaNames='sys,staging'
GO

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].spUpdateExistingEntityFieldsFromSchema @ExcludedSchemaNames='sys,staging'
GO

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].spSetDefaultColumnWidthWhereNeeded @ExcludedSchemaNames='sys,staging'
GO

/* SQL text to recompile all stored procedures in dependency order */
EXEC [${mjSchema}].spRecompileAllProceduresInDependencyOrder @ExcludedSchemaNames='sys,staging', @LogOutput=0, @ContinueOnError=1
GO


















































/* ============================================================================================
   ==== CODEGEN OUTPUT — DO NOT EDIT BELOW THIS LINE ====
   Generated by MJ CLI 6.1.3 / CodeGenLib 6.1.3 (`mj codegen`) with
   includeSchemas ['__mj_BizAppsCommon'] after the DDL above was applied and
   BEFORE this R refresh on authoring. Replay order: DDL, R, then this emit.
   Source: migrations/codegen/CodeGen_Run_2026-09-23_18-33-51.sql
   ============================================================================================ */

/* Index for Foreign Keys for AddressLink */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key AddressID in table AddressLink
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AddressLink_AddressID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[AddressLink]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AddressLink_AddressID ON [${flyway:defaultSchema}].[AddressLink] ([AddressID]);

-- Index for foreign key EntityID in table AddressLink
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AddressLink_EntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[AddressLink]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AddressLink_EntityID ON [${flyway:defaultSchema}].[AddressLink] ([EntityID]);

-- Index for foreign key AddressTypeID in table AddressLink
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AddressLink_AddressTypeID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[AddressLink]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AddressLink_AddressTypeID ON [${flyway:defaultSchema}].[AddressLink] ([AddressTypeID]);

/* Index for Foreign Keys for Address */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Addresses
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------;

/* Base View SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: vwAddressLinks
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Address Links
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  AddressLink
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwAddressLinks]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwAddressLinks];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwAddressLinks]
AS
SELECT
    a.*,
    mjBizAppsCommonAddress_AddressID.[Line1] AS [Address],
    MJEntity_EntityID.[Name] AS [Entity],
    mjBizAppsCommonAddressType_AddressTypeID.[Name] AS [AddressType]
FROM
    [${flyway:defaultSchema}].[AddressLink] AS a
INNER JOIN
    [${flyway:defaultSchema}].[Address] AS mjBizAppsCommonAddress_AddressID
  ON
    [a].[AddressID] = mjBizAppsCommonAddress_AddressID.[ID]
INNER JOIN
    [${mjSchema}].[Entity] AS MJEntity_EntityID
  ON
    [a].[EntityID] = MJEntity_EntityID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[AddressType] AS mjBizAppsCommonAddressType_AddressTypeID
  ON
    [a].[AddressTypeID] = mjBizAppsCommonAddressType_AddressTypeID.[ID]
GO
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: Permissions for vwAddressLinks
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: spCreateAddressLink
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR AddressLink
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateAddressLink]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateAddressLink];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateAddressLink]
    @ID uniqueidentifier = NULL,
    @AddressID uniqueidentifier,
    @EntityID uniqueidentifier,
    @RecordID nvarchar(700),
    @AddressTypeID uniqueidentifier,
    @IsPrimary bit = NULL,
    @Rank_Clear bit = 0,
    @Rank int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[AddressLink]
            (
                [ID],
                [AddressID],
                [EntityID],
                [RecordID],
                [AddressTypeID],
                [IsPrimary],
                [Rank]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @AddressID,
                @EntityID,
                @RecordID,
                @AddressTypeID,
                ISNULL(@IsPrimary, 0),
                CASE WHEN @Rank_Clear = 1 THEN NULL ELSE ISNULL(@Rank, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[AddressLink]
            (
                [AddressID],
                [EntityID],
                [RecordID],
                [AddressTypeID],
                [IsPrimary],
                [Rank]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @AddressID,
                @EntityID,
                @RecordID,
                @AddressTypeID,
                ISNULL(@IsPrimary, 0),
                CASE WHEN @Rank_Clear = 1 THEN NULL ELSE ISNULL(@Rank, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwAddressLinks] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Address Links */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: spUpdateAddressLink
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR AddressLink
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateAddressLink]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateAddressLink];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateAddressLink]
    @ID uniqueidentifier,
    @AddressID uniqueidentifier = NULL,
    @EntityID uniqueidentifier = NULL,
    @RecordID nvarchar(700) = NULL,
    @AddressTypeID uniqueidentifier = NULL,
    @IsPrimary bit = NULL,
    @Rank_Clear bit = 0,
    @Rank int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[AddressLink]
    SET
        [AddressID] = ISNULL(@AddressID, [AddressID]),
        [EntityID] = ISNULL(@EntityID, [EntityID]),
        [RecordID] = ISNULL(@RecordID, [RecordID]),
        [AddressTypeID] = ISNULL(@AddressTypeID, [AddressTypeID]),
        [IsPrimary] = ISNULL(@IsPrimary, [IsPrimary]),
        [Rank] = CASE WHEN @Rank_Clear = 1 THEN NULL ELSE ISNULL(@Rank, [Rank]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwAddressLinks] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwAddressLinks]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the AddressLink table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateAddressLink]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateAddressLink];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateAddressLink
ON [${flyway:defaultSchema}].[AddressLink]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[AddressLink]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[AddressLink] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Address Links */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] TO [cdp_Developer], [cdp_Integration];

/* Base View SQL for MJ_BizApps_Common: Addresses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Addresses
-- Item: vwAddresses
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Addresses
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  Address
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwAddresses]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwAddresses];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwAddresses]
AS
SELECT
    a.*,    [a].[Latitude] AS [${mjSchema}_Latitude],
    [a].[Longitude] AS [${mjSchema}_Longitude]
FROM
    [${flyway:defaultSchema}].[Address] AS a
GO
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddresses] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddresses] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddresses] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwAddresses] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Addresses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Addresses
-- Item: Permissions for vwAddresses
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddresses] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddresses] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwAddresses] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwAddresses] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Addresses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Addresses
-- Item: spCreateAddress
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Address
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateAddress]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateAddress];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateAddress]
    @ID uniqueidentifier = NULL,
    @Line1_Clear bit = 0,
    @Line1 nvarchar(255) = NULL,
    @Line2_Clear bit = 0,
    @Line2 nvarchar(255) = NULL,
    @Line3_Clear bit = 0,
    @Line3 nvarchar(255) = NULL,
    @City_Clear bit = 0,
    @City nvarchar(100) = NULL,
    @StateProvince_Clear bit = 0,
    @StateProvince nvarchar(100) = NULL,
    @PostalCode_Clear bit = 0,
    @PostalCode nvarchar(20) = NULL,
    @Country nvarchar(100) = NULL,
    @Latitude_Clear bit = 0,
    @Latitude decimal(9, 6) = NULL,
    @Longitude_Clear bit = 0,
    @Longitude decimal(9, 6) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Address]
            (
                [ID],
                [Line1],
                [Line2],
                [Line3],
                [City],
                [StateProvince],
                [PostalCode],
                [Country],
                [Latitude],
                [Longitude]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                CASE WHEN @Line1_Clear = 1 THEN NULL ELSE ISNULL(@Line1, NULL) END,
                CASE WHEN @Line2_Clear = 1 THEN NULL ELSE ISNULL(@Line2, NULL) END,
                CASE WHEN @Line3_Clear = 1 THEN NULL ELSE ISNULL(@Line3, NULL) END,
                CASE WHEN @City_Clear = 1 THEN NULL ELSE ISNULL(@City, NULL) END,
                CASE WHEN @StateProvince_Clear = 1 THEN NULL ELSE ISNULL(@StateProvince, NULL) END,
                CASE WHEN @PostalCode_Clear = 1 THEN NULL ELSE ISNULL(@PostalCode, NULL) END,
                ISNULL(@Country, 'US'),
                CASE WHEN @Latitude_Clear = 1 THEN NULL ELSE ISNULL(@Latitude, NULL) END,
                CASE WHEN @Longitude_Clear = 1 THEN NULL ELSE ISNULL(@Longitude, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Address]
            (
                [Line1],
                [Line2],
                [Line3],
                [City],
                [StateProvince],
                [PostalCode],
                [Country],
                [Latitude],
                [Longitude]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                CASE WHEN @Line1_Clear = 1 THEN NULL ELSE ISNULL(@Line1, NULL) END,
                CASE WHEN @Line2_Clear = 1 THEN NULL ELSE ISNULL(@Line2, NULL) END,
                CASE WHEN @Line3_Clear = 1 THEN NULL ELSE ISNULL(@Line3, NULL) END,
                CASE WHEN @City_Clear = 1 THEN NULL ELSE ISNULL(@City, NULL) END,
                CASE WHEN @StateProvince_Clear = 1 THEN NULL ELSE ISNULL(@StateProvince, NULL) END,
                CASE WHEN @PostalCode_Clear = 1 THEN NULL ELSE ISNULL(@PostalCode, NULL) END,
                ISNULL(@Country, 'US'),
                CASE WHEN @Latitude_Clear = 1 THEN NULL ELSE ISNULL(@Latitude, NULL) END,
                CASE WHEN @Longitude_Clear = 1 THEN NULL ELSE ISNULL(@Longitude, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwAddresses] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddress] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddress] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAddress] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Addresses */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddress] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateAddress] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAddress] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Addresses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Addresses
-- Item: spUpdateAddress
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Address
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateAddress]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateAddress];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateAddress]
    @ID uniqueidentifier,
    @Line1_Clear bit = 0,
    @Line1 nvarchar(255) = NULL,
    @Line2_Clear bit = 0,
    @Line2 nvarchar(255) = NULL,
    @Line3_Clear bit = 0,
    @Line3 nvarchar(255) = NULL,
    @City_Clear bit = 0,
    @City nvarchar(100) = NULL,
    @StateProvince_Clear bit = 0,
    @StateProvince nvarchar(100) = NULL,
    @PostalCode_Clear bit = 0,
    @PostalCode nvarchar(20) = NULL,
    @Country nvarchar(100) = NULL,
    @Latitude_Clear bit = 0,
    @Latitude decimal(9, 6) = NULL,
    @Longitude_Clear bit = 0,
    @Longitude decimal(9, 6) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Address]
    SET
        [Line1] = CASE WHEN @Line1_Clear = 1 THEN NULL ELSE ISNULL(@Line1, [Line1]) END,
        [Line2] = CASE WHEN @Line2_Clear = 1 THEN NULL ELSE ISNULL(@Line2, [Line2]) END,
        [Line3] = CASE WHEN @Line3_Clear = 1 THEN NULL ELSE ISNULL(@Line3, [Line3]) END,
        [City] = CASE WHEN @City_Clear = 1 THEN NULL ELSE ISNULL(@City, [City]) END,
        [StateProvince] = CASE WHEN @StateProvince_Clear = 1 THEN NULL ELSE ISNULL(@StateProvince, [StateProvince]) END,
        [PostalCode] = CASE WHEN @PostalCode_Clear = 1 THEN NULL ELSE ISNULL(@PostalCode, [PostalCode]) END,
        [Country] = ISNULL(@Country, [Country]),
        [Latitude] = CASE WHEN @Latitude_Clear = 1 THEN NULL ELSE ISNULL(@Latitude, [Latitude]) END,
        [Longitude] = CASE WHEN @Longitude_Clear = 1 THEN NULL ELSE ISNULL(@Longitude, [Longitude]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwAddresses] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwAddresses]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddress] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddress] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddress] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Address table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateAddress]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateAddress];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateAddress
ON [${flyway:defaultSchema}].[Address]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Address]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[Address] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Addresses */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddress] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddress] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddress] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: spDeleteAddressLink
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR AddressLink
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteAddressLink]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteAddressLink];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteAddressLink]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[AddressLink]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddressLink] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddressLink] TO [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Address Links */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddressLink] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddressLink] TO [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Addresses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Addresses
-- Item: spDeleteAddress
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Address
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteAddress]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteAddress];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteAddress]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[Address]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddress] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddress] TO [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Addresses */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddress] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddress] TO [cdp_Integration];

