-- =====================================================================
-- v5.29 Metadata Sync
-- =====================================================================
--
-- Replays the metadata/ folder state into __mj.Entity, __mj.EntityField,
-- __mj.SchemaInfo, and BAC's seed-data tables (Address Types, Contact
-- Types, Organization Types, Relationship Types).
--
-- Two notable metadata changes ship here:
--   1. Person.DisplayName.IsNameField = 1 (was: LastName)
--      Pairs with the new PERSISTED computed column DisplayName added
--      in V202605131929. Makes Person records display as "John Smith"
--      in dropdowns and FK tooltips instead of just "Smith".
--   2. Person.LastName.IsNameField = 0 (un-set the previous auto-pick)
--
-- Generated by `mj sync push` against a freshly-migrated DB. Schema
-- references are literal `[__mj]` and `[__mj_BizAppsCommon]` (matches
-- BCSaaS's V202602251500__v1.0.x_Metadata_Sync.sql pattern).
--
-- =====================================================================

-- SQL Logging Session
-- Session ID: 134655f8-85d5-43c2-b18d-da8ba5f27c8a
-- Started: 2026-05-14T15:55:51.288Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Schema Info (core SP call only)
DECLARE @SchemaName_008fdd64 NVARCHAR(50),
@EntityIDMin_008fdd64 INT,
@EntityIDMax_008fdd64 INT,
@Comments_008fdd64 NVARCHAR(MAX),
@Description_008fdd64 NVARCHAR(MAX),
@EntityNamePrefix_008fdd64 NVARCHAR(25),
@EntityNameSuffix_008fdd64 NVARCHAR(25),
@ID_008fdd64 UNIQUEIDENTIFIER
SET
  @SchemaName_008fdd64 = N'__mj_BizAppsCommon'
SET
  @EntityIDMin_008fdd64 = 1
SET
  @EntityIDMax_008fdd64 = 1000000
SET
  @Description_008fdd64 = N'MemberJunction: Common Business App Data'
SET
  @EntityNamePrefix_008fdd64 = N'MJ_BizApps_Common: '
SET
  @ID_008fdd64 = '0A9F0FDD-CD4D-4892-BA45-85722B982032' EXEC [__mj].spUpdateSchemaInfo @SchemaName = @SchemaName_008fdd64,
  @EntityIDMin = @EntityIDMin_008fdd64,
  @EntityIDMax = @EntityIDMax_008fdd64,
  @Comments = @Comments_008fdd64,
  @Comments_Clear = 1,
  @Description = @Description_008fdd64,
  @EntityNamePrefix = @EntityNamePrefix_008fdd64,
  @EntityNameSuffix = @EntityNameSuffix_008fdd64,
  @EntityNameSuffix_Clear = 1,
  @ID = @ID_008fdd64;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_d88511b1 UNIQUEIDENTIFIER,
@Name_d88511b1 NVARCHAR(100),
@Description_d88511b1 NVARCHAR(MAX),
@IconClass_d88511b1 NVARCHAR(100),
@DefaultRank_d88511b1 INT,
@IsActive_d88511b1 BIT
SET
  @ID_d88511b1 = '49183F91-F101-48F6-B2BE-AEC550B2CA0E'
SET
  @Name_d88511b1 = N'Home'
SET
  @Description_d88511b1 = N'Primary residential address'
SET
  @IconClass_d88511b1 = N'fa-solid fa-house'
SET
  @DefaultRank_d88511b1 = 10
SET
  @IsActive_d88511b1 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_d88511b1,
  @Name = @Name_d88511b1,
  @Description = @Description_d88511b1,
  @IconClass = @IconClass_d88511b1,
  @DefaultRank = @DefaultRank_d88511b1,
  @IsActive = @IsActive_d88511b1;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_597926f2 UNIQUEIDENTIFIER,
@Name_597926f2 NVARCHAR(100),
@Description_597926f2 NVARCHAR(MAX),
@IconClass_597926f2 NVARCHAR(100),
@DefaultRank_597926f2 INT,
@IsActive_597926f2 BIT
SET
  @ID_597926f2 = '0EFFA181-179B-4B68-ACC8-A57D55C4D73D'
SET
  @Name_597926f2 = N'Work'
SET
  @Description_597926f2 = N'Business or office address'
SET
  @IconClass_597926f2 = N'fa-solid fa-building'
SET
  @DefaultRank_597926f2 = 20
SET
  @IsActive_597926f2 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_597926f2,
  @Name = @Name_597926f2,
  @Description = @Description_597926f2,
  @IconClass = @IconClass_597926f2,
  @DefaultRank = @DefaultRank_597926f2,
  @IsActive = @IsActive_597926f2;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_4c512fdb UNIQUEIDENTIFIER,
@Name_4c512fdb NVARCHAR(100),
@Description_4c512fdb NVARCHAR(MAX),
@IconClass_4c512fdb NVARCHAR(100),
@DefaultRank_4c512fdb INT,
@IsActive_4c512fdb BIT
SET
  @ID_4c512fdb = '964C05C1-C947-467B-97B9-A7495BDDB7B0'
SET
  @Name_4c512fdb = N'Mailing'
SET
  @Description_4c512fdb = N'Preferred address for receiving mail and correspondence'
SET
  @IconClass_4c512fdb = N'fa-solid fa-mailbox'
SET
  @DefaultRank_4c512fdb = 30
SET
  @IsActive_4c512fdb = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_4c512fdb,
  @Name = @Name_4c512fdb,
  @Description = @Description_4c512fdb,
  @IconClass = @IconClass_4c512fdb,
  @DefaultRank = @DefaultRank_4c512fdb,
  @IsActive = @IsActive_4c512fdb;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_b0182678 UNIQUEIDENTIFIER,
@Name_b0182678 NVARCHAR(100),
@Description_b0182678 NVARCHAR(MAX),
@IconClass_b0182678 NVARCHAR(100),
@DefaultRank_b0182678 INT,
@IsActive_b0182678 BIT
SET
  @ID_b0182678 = 'E2C28836-F2C2-4590-A519-BCAB0E864974'
SET
  @Name_b0182678 = N'Billing'
SET
  @Description_b0182678 = N'Address used for invoices and financial correspondence'
SET
  @IconClass_b0182678 = N'fa-solid fa-file-invoice-dollar'
SET
  @DefaultRank_b0182678 = 40
SET
  @IsActive_b0182678 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_b0182678,
  @Name = @Name_b0182678,
  @Description = @Description_b0182678,
  @IconClass = @IconClass_b0182678,
  @DefaultRank = @DefaultRank_b0182678,
  @IsActive = @IsActive_b0182678;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_8ea20fa1 UNIQUEIDENTIFIER,
@Name_8ea20fa1 NVARCHAR(100),
@Description_8ea20fa1 NVARCHAR(MAX),
@IconClass_8ea20fa1 NVARCHAR(100),
@DefaultRank_8ea20fa1 INT,
@IsActive_8ea20fa1 BIT
SET
  @ID_8ea20fa1 = 'C466C5B0-35AE-46D6-B95E-88823E2E7EE5'
SET
  @Name_8ea20fa1 = N'Shipping'
SET
  @Description_8ea20fa1 = N'Address for physical deliveries'
SET
  @IconClass_8ea20fa1 = N'fa-solid fa-truck'
SET
  @DefaultRank_8ea20fa1 = 50
SET
  @IsActive_8ea20fa1 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_8ea20fa1,
  @Name = @Name_8ea20fa1,
  @Description = @Description_8ea20fa1,
  @IconClass = @IconClass_8ea20fa1,
  @DefaultRank = @DefaultRank_8ea20fa1,
  @IsActive = @IsActive_8ea20fa1;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_49f28eee UNIQUEIDENTIFIER,
@Name_49f28eee NVARCHAR(100),
@Description_49f28eee NVARCHAR(MAX),
@IconClass_49f28eee NVARCHAR(100),
@DefaultRank_49f28eee INT,
@IsActive_49f28eee BIT
SET
  @ID_49f28eee = '4D1E1A1A-1CD1-4069-BF1E-198F838A0DFF'
SET
  @Name_49f28eee = N'Legal'
SET
  @Description_49f28eee = N'Registered legal or statutory address'
SET
  @IconClass_49f28eee = N'fa-solid fa-scale-balanced'
SET
  @DefaultRank_49f28eee = 60
SET
  @IsActive_49f28eee = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_49f28eee,
  @Name = @Name_49f28eee,
  @Description = @Description_49f28eee,
  @IconClass = @IconClass_49f28eee,
  @DefaultRank = @DefaultRank_49f28eee,
  @IsActive = @IsActive_49f28eee;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_b2f97eea UNIQUEIDENTIFIER,
@Name_b2f97eea NVARCHAR(100),
@Description_b2f97eea NVARCHAR(MAX),
@IconClass_b2f97eea NVARCHAR(100),
@DisplayRank_b2f97eea INT,
@IsActive_b2f97eea BIT
SET
  @ID_b2f97eea = 'FB4D3737-8479-44E5-AF91-2DB63311D293'
SET
  @Name_b2f97eea = N'Email'
SET
  @Description_b2f97eea = N'Email address'
SET
  @IconClass_b2f97eea = N'fa-solid fa-envelope'
SET
  @DisplayRank_b2f97eea = 10
SET
  @IsActive_b2f97eea = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_b2f97eea,
  @Name = @Name_b2f97eea,
  @Description = @Description_b2f97eea,
  @IconClass = @IconClass_b2f97eea,
  @DisplayRank = @DisplayRank_b2f97eea,
  @IsActive = @IsActive_b2f97eea;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_a3b84db6 UNIQUEIDENTIFIER,
@Name_a3b84db6 NVARCHAR(100),
@Description_a3b84db6 NVARCHAR(MAX),
@IconClass_a3b84db6 NVARCHAR(100),
@DisplayRank_a3b84db6 INT,
@IsActive_a3b84db6 BIT
SET
  @ID_a3b84db6 = '96421246-0F8F-4CDB-A5C5-BA6B190C1AFE'
SET
  @Name_a3b84db6 = N'Mobile Phone'
SET
  @Description_a3b84db6 = N'Mobile or cell phone number'
SET
  @IconClass_a3b84db6 = N'fa-solid fa-mobile-screen'
SET
  @DisplayRank_a3b84db6 = 20
SET
  @IsActive_a3b84db6 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_a3b84db6,
  @Name = @Name_a3b84db6,
  @Description = @Description_a3b84db6,
  @IconClass = @IconClass_a3b84db6,
  @DisplayRank = @DisplayRank_a3b84db6,
  @IsActive = @IsActive_a3b84db6;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_1bfa4816 UNIQUEIDENTIFIER,
@Name_1bfa4816 NVARCHAR(100),
@Description_1bfa4816 NVARCHAR(MAX),
@IconClass_1bfa4816 NVARCHAR(100),
@DisplayRank_1bfa4816 INT,
@IsActive_1bfa4816 BIT
SET
  @ID_1bfa4816 = 'BCDA98AC-06A4-40FC-A1CC-E44BB783FBC9'
SET
  @Name_1bfa4816 = N'Work Phone'
SET
  @Description_1bfa4816 = N'Business or office phone number'
SET
  @IconClass_1bfa4816 = N'fa-solid fa-phone-office'
SET
  @DisplayRank_1bfa4816 = 30
SET
  @IsActive_1bfa4816 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_1bfa4816,
  @Name = @Name_1bfa4816,
  @Description = @Description_1bfa4816,
  @IconClass = @IconClass_1bfa4816,
  @DisplayRank = @DisplayRank_1bfa4816,
  @IsActive = @IsActive_1bfa4816;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_ce15503f UNIQUEIDENTIFIER,
@Name_ce15503f NVARCHAR(100),
@Description_ce15503f NVARCHAR(MAX),
@IconClass_ce15503f NVARCHAR(100),
@DisplayRank_ce15503f INT,
@IsActive_ce15503f BIT
SET
  @ID_ce15503f = 'C3BA9432-8D05-4AFE-BF6D-61F976A466E6'
SET
  @Name_ce15503f = N'Home Phone'
SET
  @Description_ce15503f = N'Residential phone number'
SET
  @IconClass_ce15503f = N'fa-solid fa-phone'
SET
  @DisplayRank_ce15503f = 40
SET
  @IsActive_ce15503f = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_ce15503f,
  @Name = @Name_ce15503f,
  @Description = @Description_ce15503f,
  @IconClass = @IconClass_ce15503f,
  @DisplayRank = @DisplayRank_ce15503f,
  @IsActive = @IsActive_ce15503f;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_f5b6281b UNIQUEIDENTIFIER,
@Name_f5b6281b NVARCHAR(100),
@Description_f5b6281b NVARCHAR(MAX),
@IconClass_f5b6281b NVARCHAR(100),
@DisplayRank_f5b6281b INT,
@IsActive_f5b6281b BIT
SET
  @ID_f5b6281b = 'FDBFF502-CE06-456B-BCC3-8A2C23D16D45'
SET
  @Name_f5b6281b = N'LinkedIn'
SET
  @Description_f5b6281b = N'LinkedIn profile URL'
SET
  @IconClass_f5b6281b = N'fa-brands fa-linkedin'
SET
  @DisplayRank_f5b6281b = 50
SET
  @IsActive_f5b6281b = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_f5b6281b,
  @Name = @Name_f5b6281b,
  @Description = @Description_f5b6281b,
  @IconClass = @IconClass_f5b6281b,
  @DisplayRank = @DisplayRank_f5b6281b,
  @IsActive = @IsActive_f5b6281b;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_d97f75bb UNIQUEIDENTIFIER,
@Name_d97f75bb NVARCHAR(100),
@Description_d97f75bb NVARCHAR(MAX),
@IconClass_d97f75bb NVARCHAR(100),
@DisplayRank_d97f75bb INT,
@IsActive_d97f75bb BIT
SET
  @ID_d97f75bb = '02A126F9-ED1B-4BBF-8479-8B10CC916150'
SET
  @Name_d97f75bb = N'Twitter / X'
SET
  @Description_d97f75bb = N'Twitter / X profile URL or handle'
SET
  @IconClass_d97f75bb = N'fa-brands fa-x-twitter'
SET
  @DisplayRank_d97f75bb = 60
SET
  @IsActive_d97f75bb = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_d97f75bb,
  @Name = @Name_d97f75bb,
  @Description = @Description_d97f75bb,
  @IconClass = @IconClass_d97f75bb,
  @DisplayRank = @DisplayRank_d97f75bb,
  @IsActive = @IsActive_d97f75bb;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_22989bb6 UNIQUEIDENTIFIER,
@Name_22989bb6 NVARCHAR(100),
@Description_22989bb6 NVARCHAR(MAX),
@IconClass_22989bb6 NVARCHAR(100),
@DisplayRank_22989bb6 INT,
@IsActive_22989bb6 BIT
SET
  @ID_22989bb6 = 'F2DBF3EA-7ACF-4725-92D3-AB630B613293'
SET
  @Name_22989bb6 = N'Website'
SET
  @Description_22989bb6 = N'Personal or professional website URL'
SET
  @IconClass_22989bb6 = N'fa-solid fa-globe'
SET
  @DisplayRank_22989bb6 = 70
SET
  @IsActive_22989bb6 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_22989bb6,
  @Name = @Name_22989bb6,
  @Description = @Description_22989bb6,
  @IconClass = @IconClass_22989bb6,
  @DisplayRank = @DisplayRank_22989bb6,
  @IsActive = @IsActive_22989bb6;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_38fe8ea8 UNIQUEIDENTIFIER,
@Name_38fe8ea8 NVARCHAR(100),
@Description_38fe8ea8 NVARCHAR(MAX),
@IconClass_38fe8ea8 NVARCHAR(100),
@DisplayRank_38fe8ea8 INT,
@IsActive_38fe8ea8 BIT
SET
  @ID_38fe8ea8 = 'A33D19DB-27FD-400C-A9C9-F3D3C4A12E8F'
SET
  @Name_38fe8ea8 = N'Fax'
SET
  @Description_38fe8ea8 = N'Fax number'
SET
  @IconClass_38fe8ea8 = N'fa-solid fa-fax'
SET
  @DisplayRank_38fe8ea8 = 80
SET
  @IsActive_38fe8ea8 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_38fe8ea8,
  @Name = @Name_38fe8ea8,
  @Description = @Description_38fe8ea8,
  @IconClass = @IconClass_38fe8ea8,
  @DisplayRank = @DisplayRank_38fe8ea8,
  @IsActive = @IsActive_38fe8ea8;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_8fd097ef UNIQUEIDENTIFIER,
@Name_8fd097ef NVARCHAR(100),
@Description_8fd097ef NVARCHAR(MAX),
@IconClass_8fd097ef NVARCHAR(100),
@DisplayRank_8fd097ef INT,
@IsActive_8fd097ef BIT
SET
  @ID_8fd097ef = 'A8DB7343-DCC9-44D1-B99F-9E21024C3C2E'
SET
  @Name_8fd097ef = N'Corporation'
SET
  @Description_8fd097ef = N'Incorporated business entity (C-Corp, S-Corp)'
SET
  @IconClass_8fd097ef = N'fa-solid fa-building'
SET
  @DisplayRank_8fd097ef = 10
SET
  @IsActive_8fd097ef = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_8fd097ef,
  @Name = @Name_8fd097ef,
  @Description = @Description_8fd097ef,
  @IconClass = @IconClass_8fd097ef,
  @DisplayRank = @DisplayRank_8fd097ef,
  @IsActive = @IsActive_8fd097ef;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_5603028a UNIQUEIDENTIFIER,
@Name_5603028a NVARCHAR(100),
@Description_5603028a NVARCHAR(MAX),
@IconClass_5603028a NVARCHAR(100),
@DisplayRank_5603028a INT,
@IsActive_5603028a BIT
SET
  @ID_5603028a = '288B017D-60A4-48A7-A845-EF30B99BDBEF'
SET
  @Name_5603028a = N'LLC'
SET
  @Description_5603028a = N'Limited liability company'
SET
  @IconClass_5603028a = N'fa-solid fa-briefcase'
SET
  @DisplayRank_5603028a = 20
SET
  @IsActive_5603028a = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_5603028a,
  @Name = @Name_5603028a,
  @Description = @Description_5603028a,
  @IconClass = @IconClass_5603028a,
  @DisplayRank = @DisplayRank_5603028a,
  @IsActive = @IsActive_5603028a;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_c2c16009 UNIQUEIDENTIFIER,
@Name_c2c16009 NVARCHAR(100),
@Description_c2c16009 NVARCHAR(MAX),
@IconClass_c2c16009 NVARCHAR(100),
@DisplayRank_c2c16009 INT,
@IsActive_c2c16009 BIT
SET
  @ID_c2c16009 = 'BAAA53F4-A8AA-4EAA-B04E-1BA6F964B341'
SET
  @Name_c2c16009 = N'Non-Profit'
SET
  @Description_c2c16009 = N'Tax-exempt non-profit organization (501(c)(3), etc.)'
SET
  @IconClass_c2c16009 = N'fa-solid fa-hand-holding-heart'
SET
  @DisplayRank_c2c16009 = 30
SET
  @IsActive_c2c16009 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_c2c16009,
  @Name = @Name_c2c16009,
  @Description = @Description_c2c16009,
  @IconClass = @IconClass_c2c16009,
  @DisplayRank = @DisplayRank_c2c16009,
  @IsActive = @IsActive_c2c16009;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_5041678d UNIQUEIDENTIFIER,
@Name_5041678d NVARCHAR(100),
@Description_5041678d NVARCHAR(MAX),
@IconClass_5041678d NVARCHAR(100),
@DisplayRank_5041678d INT,
@IsActive_5041678d BIT
SET
  @ID_5041678d = '1E61230B-0F48-458A-811B-66C9CF6B688E'
SET
  @Name_5041678d = N'Government'
SET
  @Description_5041678d = N'Government agency or department'
SET
  @IconClass_5041678d = N'fa-solid fa-landmark'
SET
  @DisplayRank_5041678d = 40
SET
  @IsActive_5041678d = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_5041678d,
  @Name = @Name_5041678d,
  @Description = @Description_5041678d,
  @IconClass = @IconClass_5041678d,
  @DisplayRank = @DisplayRank_5041678d,
  @IsActive = @IsActive_5041678d;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_342531e2 UNIQUEIDENTIFIER,
@Name_342531e2 NVARCHAR(100),
@Description_342531e2 NVARCHAR(MAX),
@IconClass_342531e2 NVARCHAR(100),
@DisplayRank_342531e2 INT,
@IsActive_342531e2 BIT
SET
  @ID_342531e2 = '5CAB6265-CB87-4269-A321-2473160BD625'
SET
  @Name_342531e2 = N'Partnership'
SET
  @Description_342531e2 = N'General or limited partnership'
SET
  @IconClass_342531e2 = N'fa-solid fa-handshake'
SET
  @DisplayRank_342531e2 = 50
SET
  @IsActive_342531e2 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_342531e2,
  @Name = @Name_342531e2,
  @Description = @Description_342531e2,
  @IconClass = @IconClass_342531e2,
  @DisplayRank = @DisplayRank_342531e2,
  @IsActive = @IsActive_342531e2;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_e2b3015d UNIQUEIDENTIFIER,
@Name_e2b3015d NVARCHAR(100),
@Description_e2b3015d NVARCHAR(MAX),
@IconClass_e2b3015d NVARCHAR(100),
@DisplayRank_e2b3015d INT,
@IsActive_e2b3015d BIT
SET
  @ID_e2b3015d = '042C63AF-93EB-4BB4-A469-F3C209F8936E'
SET
  @Name_e2b3015d = N'Sole Proprietorship'
SET
  @Description_e2b3015d = N'Unincorporated business owned by a single individual'
SET
  @IconClass_e2b3015d = N'fa-solid fa-user-tie'
SET
  @DisplayRank_e2b3015d = 60
SET
  @IsActive_e2b3015d = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_e2b3015d,
  @Name = @Name_e2b3015d,
  @Description = @Description_e2b3015d,
  @IconClass = @IconClass_e2b3015d,
  @DisplayRank = @DisplayRank_e2b3015d,
  @IsActive = @IsActive_e2b3015d;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_afa4b457 UNIQUEIDENTIFIER,
@Name_afa4b457 NVARCHAR(100),
@Description_afa4b457 NVARCHAR(MAX),
@IconClass_afa4b457 NVARCHAR(100),
@DisplayRank_afa4b457 INT,
@IsActive_afa4b457 BIT
SET
  @ID_afa4b457 = '7D6D1763-3198-42B2-A23C-F0FF76DAD8D2'
SET
  @Name_afa4b457 = N'Association'
SET
  @Description_afa4b457 = N'Professional or trade association'
SET
  @IconClass_afa4b457 = N'fa-solid fa-people-group'
SET
  @DisplayRank_afa4b457 = 70
SET
  @IsActive_afa4b457 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_afa4b457,
  @Name = @Name_afa4b457,
  @Description = @Description_afa4b457,
  @IconClass = @IconClass_afa4b457,
  @DisplayRank = @DisplayRank_afa4b457,
  @IsActive = @IsActive_afa4b457;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_ad167f7c UNIQUEIDENTIFIER,
@Name_ad167f7c NVARCHAR(100),
@Description_ad167f7c NVARCHAR(MAX),
@IconClass_ad167f7c NVARCHAR(100),
@DisplayRank_ad167f7c INT,
@IsActive_ad167f7c BIT
SET
  @ID_ad167f7c = '4BE0D87B-EFCB-447D-9410-FEF8EED23BC8'
SET
  @Name_ad167f7c = N'Educational Institution'
SET
  @Description_ad167f7c = N'School, college, university, or training organization'
SET
  @IconClass_ad167f7c = N'fa-solid fa-graduation-cap'
SET
  @DisplayRank_ad167f7c = 80
SET
  @IsActive_ad167f7c = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_ad167f7c,
  @Name = @Name_ad167f7c,
  @Description = @Description_ad167f7c,
  @IconClass = @IconClass_ad167f7c,
  @DisplayRank = @DisplayRank_ad167f7c,
  @IsActive = @IsActive_ad167f7c;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_cd3b0e64 UNIQUEIDENTIFIER,
@Name_cd3b0e64 NVARCHAR(100),
@Description_cd3b0e64 NVARCHAR(MAX),
@Category_cd3b0e64 NVARCHAR(50),
@IsDirectional_cd3b0e64 BIT,
@ForwardLabel_cd3b0e64 NVARCHAR(100),
@ReverseLabel_cd3b0e64 NVARCHAR(100),
@IsActive_cd3b0e64 BIT
SET
  @ID_cd3b0e64 = 'FEB33819-FC85-4309-B1EC-A54EEA91DACF'
SET
  @Name_cd3b0e64 = N'Spouse'
SET
  @Description_cd3b0e64 = N'Married or domestic partner relationship'
SET
  @Category_cd3b0e64 = N'PersonToPerson'
SET
  @IsDirectional_cd3b0e64 = 0
SET
  @ForwardLabel_cd3b0e64 = N'is spouse of'
SET
  @ReverseLabel_cd3b0e64 = N'is spouse of'
SET
  @IsActive_cd3b0e64 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_cd3b0e64,
  @Name = @Name_cd3b0e64,
  @Description = @Description_cd3b0e64,
  @Category = @Category_cd3b0e64,
  @IsDirectional = @IsDirectional_cd3b0e64,
  @ForwardLabel = @ForwardLabel_cd3b0e64,
  @ReverseLabel = @ReverseLabel_cd3b0e64,
  @IsActive = @IsActive_cd3b0e64;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_1c5f86d5 UNIQUEIDENTIFIER,
@Name_1c5f86d5 NVARCHAR(100),
@Description_1c5f86d5 NVARCHAR(MAX),
@Category_1c5f86d5 NVARCHAR(50),
@IsDirectional_1c5f86d5 BIT,
@ForwardLabel_1c5f86d5 NVARCHAR(100),
@ReverseLabel_1c5f86d5 NVARCHAR(100),
@IsActive_1c5f86d5 BIT
SET
  @ID_1c5f86d5 = '431DBAF3-AC1D-47E6-B91E-264E8C76FC57'
SET
  @Name_1c5f86d5 = N'Parent / Child'
SET
  @Description_1c5f86d5 = N'Parent-child family relationship'
SET
  @Category_1c5f86d5 = N'PersonToPerson'
SET
  @IsDirectional_1c5f86d5 = 1
SET
  @ForwardLabel_1c5f86d5 = N'is parent of'
SET
  @ReverseLabel_1c5f86d5 = N'is child of'
SET
  @IsActive_1c5f86d5 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_1c5f86d5,
  @Name = @Name_1c5f86d5,
  @Description = @Description_1c5f86d5,
  @Category = @Category_1c5f86d5,
  @IsDirectional = @IsDirectional_1c5f86d5,
  @ForwardLabel = @ForwardLabel_1c5f86d5,
  @ReverseLabel = @ReverseLabel_1c5f86d5,
  @IsActive = @IsActive_1c5f86d5;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_9dad4904 UNIQUEIDENTIFIER,
@Name_9dad4904 NVARCHAR(100),
@Description_9dad4904 NVARCHAR(MAX),
@Category_9dad4904 NVARCHAR(50),
@IsDirectional_9dad4904 BIT,
@ForwardLabel_9dad4904 NVARCHAR(100),
@ReverseLabel_9dad4904 NVARCHAR(100),
@IsActive_9dad4904 BIT
SET
  @ID_9dad4904 = 'D471B007-0717-493E-AC0D-2F102A32BCC2'
SET
  @Name_9dad4904 = N'Sibling'
SET
  @Description_9dad4904 = N'Brother or sister relationship'
SET
  @Category_9dad4904 = N'PersonToPerson'
SET
  @IsDirectional_9dad4904 = 0
SET
  @ForwardLabel_9dad4904 = N'is sibling of'
SET
  @ReverseLabel_9dad4904 = N'is sibling of'
SET
  @IsActive_9dad4904 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_9dad4904,
  @Name = @Name_9dad4904,
  @Description = @Description_9dad4904,
  @Category = @Category_9dad4904,
  @IsDirectional = @IsDirectional_9dad4904,
  @ForwardLabel = @ForwardLabel_9dad4904,
  @ReverseLabel = @ReverseLabel_9dad4904,
  @IsActive = @IsActive_9dad4904;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_f474b23e UNIQUEIDENTIFIER,
@Name_f474b23e NVARCHAR(100),
@Description_f474b23e NVARCHAR(MAX),
@Category_f474b23e NVARCHAR(50),
@IsDirectional_f474b23e BIT,
@ForwardLabel_f474b23e NVARCHAR(100),
@ReverseLabel_f474b23e NVARCHAR(100),
@IsActive_f474b23e BIT
SET
  @ID_f474b23e = '6A17A929-8B23-4D73-9DF9-A368E7C1C1B9'
SET
  @Name_f474b23e = N'Friend'
SET
  @Description_f474b23e = N'Personal friendship'
SET
  @Category_f474b23e = N'PersonToPerson'
SET
  @IsDirectional_f474b23e = 0
SET
  @ForwardLabel_f474b23e = N'is friend of'
SET
  @ReverseLabel_f474b23e = N'is friend of'
SET
  @IsActive_f474b23e = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_f474b23e,
  @Name = @Name_f474b23e,
  @Description = @Description_f474b23e,
  @Category = @Category_f474b23e,
  @IsDirectional = @IsDirectional_f474b23e,
  @ForwardLabel = @ForwardLabel_f474b23e,
  @ReverseLabel = @ReverseLabel_f474b23e,
  @IsActive = @IsActive_f474b23e;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_ba101160 UNIQUEIDENTIFIER,
@Name_ba101160 NVARCHAR(100),
@Description_ba101160 NVARCHAR(MAX),
@Category_ba101160 NVARCHAR(50),
@IsDirectional_ba101160 BIT,
@ForwardLabel_ba101160 NVARCHAR(100),
@ReverseLabel_ba101160 NVARCHAR(100),
@IsActive_ba101160 BIT
SET
  @ID_ba101160 = '27CFD031-5663-4000-A7AB-8AC87DB88C1D'
SET
  @Name_ba101160 = N'Employee'
SET
  @Description_ba101160 = N'Employment relationship between a person and an organization'
SET
  @Category_ba101160 = N'PersonToOrganization'
SET
  @IsDirectional_ba101160 = 1
SET
  @ForwardLabel_ba101160 = N'is employee of'
SET
  @ReverseLabel_ba101160 = N'employs'
SET
  @IsActive_ba101160 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_ba101160,
  @Name = @Name_ba101160,
  @Description = @Description_ba101160,
  @Category = @Category_ba101160,
  @IsDirectional = @IsDirectional_ba101160,
  @ForwardLabel = @ForwardLabel_ba101160,
  @ReverseLabel = @ReverseLabel_ba101160,
  @IsActive = @IsActive_ba101160;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_335a03dc UNIQUEIDENTIFIER,
@Name_335a03dc NVARCHAR(100),
@Description_335a03dc NVARCHAR(MAX),
@Category_335a03dc NVARCHAR(50),
@IsDirectional_335a03dc BIT,
@ForwardLabel_335a03dc NVARCHAR(100),
@ReverseLabel_335a03dc NVARCHAR(100),
@IsActive_335a03dc BIT
SET
  @ID_335a03dc = '2FE33D05-5FD0-4076-8EF2-A30A640651B4'
SET
  @Name_335a03dc = N'Board Member'
SET
  @Description_335a03dc = N'Person serves on the board of directors of an organization'
SET
  @Category_335a03dc = N'PersonToOrganization'
SET
  @IsDirectional_335a03dc = 1
SET
  @ForwardLabel_335a03dc = N'is board member of'
SET
  @ReverseLabel_335a03dc = N'has board member'
SET
  @IsActive_335a03dc = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_335a03dc,
  @Name = @Name_335a03dc,
  @Description = @Description_335a03dc,
  @Category = @Category_335a03dc,
  @IsDirectional = @IsDirectional_335a03dc,
  @ForwardLabel = @ForwardLabel_335a03dc,
  @ReverseLabel = @ReverseLabel_335a03dc,
  @IsActive = @IsActive_335a03dc;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_72a30637 UNIQUEIDENTIFIER,
@Name_72a30637 NVARCHAR(100),
@Description_72a30637 NVARCHAR(MAX),
@Category_72a30637 NVARCHAR(50),
@IsDirectional_72a30637 BIT,
@ForwardLabel_72a30637 NVARCHAR(100),
@ReverseLabel_72a30637 NVARCHAR(100),
@IsActive_72a30637 BIT
SET
  @ID_72a30637 = '5B8C871C-025B-410A-9D44-4D30C76534C7'
SET
  @Name_72a30637 = N'Member'
SET
  @Description_72a30637 = N'Person is a member of an organization or association'
SET
  @Category_72a30637 = N'PersonToOrganization'
SET
  @IsDirectional_72a30637 = 1
SET
  @ForwardLabel_72a30637 = N'is member of'
SET
  @ReverseLabel_72a30637 = N'has member'
SET
  @IsActive_72a30637 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_72a30637,
  @Name = @Name_72a30637,
  @Description = @Description_72a30637,
  @Category = @Category_72a30637,
  @IsDirectional = @IsDirectional_72a30637,
  @ForwardLabel = @ForwardLabel_72a30637,
  @ReverseLabel = @ReverseLabel_72a30637,
  @IsActive = @IsActive_72a30637;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_3fef8317 UNIQUEIDENTIFIER,
@Name_3fef8317 NVARCHAR(100),
@Description_3fef8317 NVARCHAR(MAX),
@Category_3fef8317 NVARCHAR(50),
@IsDirectional_3fef8317 BIT,
@ForwardLabel_3fef8317 NVARCHAR(100),
@ReverseLabel_3fef8317 NVARCHAR(100),
@IsActive_3fef8317 BIT
SET
  @ID_3fef8317 = 'DF72DDBB-A829-41AC-8698-01FCCD21FEEF'
SET
  @Name_3fef8317 = N'Volunteer'
SET
  @Description_3fef8317 = N'Person volunteers for an organization'
SET
  @Category_3fef8317 = N'PersonToOrganization'
SET
  @IsDirectional_3fef8317 = 1
SET
  @ForwardLabel_3fef8317 = N'volunteers for'
SET
  @ReverseLabel_3fef8317 = N'has volunteer'
SET
  @IsActive_3fef8317 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_3fef8317,
  @Name = @Name_3fef8317,
  @Description = @Description_3fef8317,
  @Category = @Category_3fef8317,
  @IsDirectional = @IsDirectional_3fef8317,
  @ForwardLabel = @ForwardLabel_3fef8317,
  @ReverseLabel = @ReverseLabel_3fef8317,
  @IsActive = @IsActive_3fef8317;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_0e0a063a UNIQUEIDENTIFIER,
@Name_0e0a063a NVARCHAR(100),
@Description_0e0a063a NVARCHAR(MAX),
@Category_0e0a063a NVARCHAR(50),
@IsDirectional_0e0a063a BIT,
@ForwardLabel_0e0a063a NVARCHAR(100),
@ReverseLabel_0e0a063a NVARCHAR(100),
@IsActive_0e0a063a BIT
SET
  @ID_0e0a063a = 'DC06CB0C-A6CE-437C-A19E-F615F949BC51'
SET
  @Name_0e0a063a = N'Customer'
SET
  @Description_0e0a063a = N'Person is a customer or client of an organization'
SET
  @Category_0e0a063a = N'PersonToOrganization'
SET
  @IsDirectional_0e0a063a = 1
SET
  @ForwardLabel_0e0a063a = N'is customer of'
SET
  @ReverseLabel_0e0a063a = N'has customer'
SET
  @IsActive_0e0a063a = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_0e0a063a,
  @Name = @Name_0e0a063a,
  @Description = @Description_0e0a063a,
  @Category = @Category_0e0a063a,
  @IsDirectional = @IsDirectional_0e0a063a,
  @ForwardLabel = @ForwardLabel_0e0a063a,
  @ReverseLabel = @ReverseLabel_0e0a063a,
  @IsActive = @IsActive_0e0a063a;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_4a8be5ec UNIQUEIDENTIFIER,
@Name_4a8be5ec NVARCHAR(100),
@Description_4a8be5ec NVARCHAR(MAX),
@Category_4a8be5ec NVARCHAR(50),
@IsDirectional_4a8be5ec BIT,
@ForwardLabel_4a8be5ec NVARCHAR(100),
@ReverseLabel_4a8be5ec NVARCHAR(100),
@IsActive_4a8be5ec BIT
SET
  @ID_4a8be5ec = '6BF6959D-18B4-4615-AFCE-643963A87C1B'
SET
  @Name_4a8be5ec = N'Consultant'
SET
  @Description_4a8be5ec = N'Person provides consulting services to an organization'
SET
  @Category_4a8be5ec = N'PersonToOrganization'
SET
  @IsDirectional_4a8be5ec = 1
SET
  @ForwardLabel_4a8be5ec = N'consults for'
SET
  @ReverseLabel_4a8be5ec = N'has consultant'
SET
  @IsActive_4a8be5ec = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_4a8be5ec,
  @Name = @Name_4a8be5ec,
  @Description = @Description_4a8be5ec,
  @Category = @Category_4a8be5ec,
  @IsDirectional = @IsDirectional_4a8be5ec,
  @ForwardLabel = @ForwardLabel_4a8be5ec,
  @ReverseLabel = @ReverseLabel_4a8be5ec,
  @IsActive = @IsActive_4a8be5ec;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_f66e2095 UNIQUEIDENTIFIER,
@Name_f66e2095 NVARCHAR(100),
@Description_f66e2095 NVARCHAR(MAX),
@Category_f66e2095 NVARCHAR(50),
@IsDirectional_f66e2095 BIT,
@ForwardLabel_f66e2095 NVARCHAR(100),
@ReverseLabel_f66e2095 NVARCHAR(100),
@IsActive_f66e2095 BIT
SET
  @ID_f66e2095 = '39373681-5C70-4845-896B-4BFE4343751F'
SET
  @Name_f66e2095 = N'Subsidiary'
SET
  @Description_f66e2095 = N'One organization is a subsidiary or division of another'
SET
  @Category_f66e2095 = N'OrganizationToOrganization'
SET
  @IsDirectional_f66e2095 = 1
SET
  @ForwardLabel_f66e2095 = N'is subsidiary of'
SET
  @ReverseLabel_f66e2095 = N'has subsidiary'
SET
  @IsActive_f66e2095 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_f66e2095,
  @Name = @Name_f66e2095,
  @Description = @Description_f66e2095,
  @Category = @Category_f66e2095,
  @IsDirectional = @IsDirectional_f66e2095,
  @ForwardLabel = @ForwardLabel_f66e2095,
  @ReverseLabel = @ReverseLabel_f66e2095,
  @IsActive = @IsActive_f66e2095;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_ae051323 UNIQUEIDENTIFIER,
@Name_ae051323 NVARCHAR(100),
@Description_ae051323 NVARCHAR(MAX),
@Category_ae051323 NVARCHAR(50),
@IsDirectional_ae051323 BIT,
@ForwardLabel_ae051323 NVARCHAR(100),
@ReverseLabel_ae051323 NVARCHAR(100),
@IsActive_ae051323 BIT
SET
  @ID_ae051323 = 'CA9BBDBE-3595-4C3F-80FF-DA78D3389EA7'
SET
  @Name_ae051323 = N'Partner'
SET
  @Description_ae051323 = N'Strategic or business partnership between organizations'
SET
  @Category_ae051323 = N'OrganizationToOrganization'
SET
  @IsDirectional_ae051323 = 0
SET
  @ForwardLabel_ae051323 = N'is partner of'
SET
  @ReverseLabel_ae051323 = N'is partner of'
SET
  @IsActive_ae051323 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_ae051323,
  @Name = @Name_ae051323,
  @Description = @Description_ae051323,
  @Category = @Category_ae051323,
  @IsDirectional = @IsDirectional_ae051323,
  @ForwardLabel = @ForwardLabel_ae051323,
  @ReverseLabel = @ReverseLabel_ae051323,
  @IsActive = @IsActive_ae051323;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_3d8acb76 UNIQUEIDENTIFIER,
@Name_3d8acb76 NVARCHAR(100),
@Description_3d8acb76 NVARCHAR(MAX),
@Category_3d8acb76 NVARCHAR(50),
@IsDirectional_3d8acb76 BIT,
@ForwardLabel_3d8acb76 NVARCHAR(100),
@ReverseLabel_3d8acb76 NVARCHAR(100),
@IsActive_3d8acb76 BIT
SET
  @ID_3d8acb76 = '190A8BBF-771E-4631-980A-84918311E5EC'
SET
  @Name_3d8acb76 = N'Vendor'
SET
  @Description_3d8acb76 = N'One organization supplies goods or services to another'
SET
  @Category_3d8acb76 = N'OrganizationToOrganization'
SET
  @IsDirectional_3d8acb76 = 1
SET
  @ForwardLabel_3d8acb76 = N'is vendor to'
SET
  @ReverseLabel_3d8acb76 = N'has vendor'
SET
  @IsActive_3d8acb76 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_3d8acb76,
  @Name = @Name_3d8acb76,
  @Description = @Description_3d8acb76,
  @Category = @Category_3d8acb76,
  @IsDirectional = @IsDirectional_3d8acb76,
  @ForwardLabel = @ForwardLabel_3d8acb76,
  @ReverseLabel = @ReverseLabel_3d8acb76,
  @IsActive = @IsActive_3d8acb76;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_61ce548b UNIQUEIDENTIFIER,
@Name_61ce548b NVARCHAR(100),
@Description_61ce548b NVARCHAR(MAX),
@Category_61ce548b NVARCHAR(50),
@IsDirectional_61ce548b BIT,
@ForwardLabel_61ce548b NVARCHAR(100),
@ReverseLabel_61ce548b NVARCHAR(100),
@IsActive_61ce548b BIT
SET
  @ID_61ce548b = '2DBA78A6-DF6F-4A7E-B126-AE038BD3B6BA'
SET
  @Name_61ce548b = N'Affiliate'
SET
  @Description_61ce548b = N'Formal affiliation between two organizations'
SET
  @Category_61ce548b = N'OrganizationToOrganization'
SET
  @IsDirectional_61ce548b = 0
SET
  @ForwardLabel_61ce548b = N'is affiliate of'
SET
  @ReverseLabel_61ce548b = N'is affiliate of'
SET
  @IsActive_61ce548b = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_61ce548b,
  @Name = @Name_61ce548b,
  @Description = @Description_61ce548b,
  @Category = @Category_61ce548b,
  @IsDirectional = @IsDirectional_61ce548b,
  @ForwardLabel = @ForwardLabel_61ce548b,
  @ReverseLabel = @ReverseLabel_61ce548b,
  @IsActive = @IsActive_61ce548b;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_ab3c9c28 NVARCHAR(255),
@Description_ab3c9c28 NVARCHAR(MAX),
@AutoUpdateDescription_ab3c9c28 BIT,
@IsPrimaryKey_ab3c9c28 BIT,
@IsUnique_ab3c9c28 BIT,
@Category_ab3c9c28 NVARCHAR(255),
@ValueListType_ab3c9c28 NVARCHAR(20),
@ExtendedType_ab3c9c28 NVARCHAR(50),
@CodeType_ab3c9c28 NVARCHAR(50),
@DefaultInView_ab3c9c28 BIT,
@ViewCellTemplate_ab3c9c28 NVARCHAR(MAX),
@DefaultColumnWidth_ab3c9c28 INT,
@AllowUpdateAPI_ab3c9c28 BIT,
@AllowUpdateInView_ab3c9c28 BIT,
@IncludeInUserSearchAPI_ab3c9c28 BIT,
@FullTextSearchEnabled_ab3c9c28 BIT,
@UserSearchParamFormatAPI_ab3c9c28 NVARCHAR(500),
@IncludeInGeneratedForm_ab3c9c28 BIT,
@GeneratedFormSection_ab3c9c28 NVARCHAR(10),
@IsNameField_ab3c9c28 BIT,
@RelatedEntityID_ab3c9c28 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_ab3c9c28 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_ab3c9c28 BIT,
@RelatedEntityNameFieldMap_ab3c9c28 NVARCHAR(255),
@RelatedEntityDisplayType_ab3c9c28 NVARCHAR(20),
@EntityIDFieldName_ab3c9c28 NVARCHAR(100),
@ScopeDefault_ab3c9c28 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_ab3c9c28 BIT,
@ValuesToPackWithSchema_ab3c9c28 NVARCHAR(10),
@Status_ab3c9c28 NVARCHAR(25),
@AutoUpdateIsNameField_ab3c9c28 BIT,
@AutoUpdateDefaultInView_ab3c9c28 BIT,
@AutoUpdateCategory_ab3c9c28 BIT,
@AutoUpdateDisplayName_ab3c9c28 BIT,
@AutoUpdateIncludeInUserSearchAPI_ab3c9c28 BIT,
@Encrypt_ab3c9c28 BIT,
@EncryptionKeyID_ab3c9c28 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_ab3c9c28 BIT,
@SendEncryptedValue_ab3c9c28 BIT,
@IsSoftPrimaryKey_ab3c9c28 BIT,
@IsSoftForeignKey_ab3c9c28 BIT,
@RelatedEntityJoinFields_ab3c9c28 NVARCHAR(MAX),
@JSONType_ab3c9c28 NVARCHAR(255),
@JSONTypeIsArray_ab3c9c28 BIT,
@JSONTypeDefinition_ab3c9c28 NVARCHAR(MAX),
@UserSearchPredicateAPI_ab3c9c28 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_ab3c9c28 BIT,
@AutoUpdateFullTextSearch_ab3c9c28 BIT,
@AutoUpdateExtendedType_ab3c9c28 BIT,
@ID_ab3c9c28 UNIQUEIDENTIFIER
SET
  @DisplayName_ab3c9c28 = N'Display Name'
SET
  @AutoUpdateDescription_ab3c9c28 = 1
SET
  @IsPrimaryKey_ab3c9c28 = 0
SET
  @IsUnique_ab3c9c28 = 0
SET
  @ValueListType_ab3c9c28 = N'None'
SET
  @DefaultInView_ab3c9c28 = 0
SET
  @DefaultColumnWidth_ab3c9c28 = 150
SET
  @AllowUpdateAPI_ab3c9c28 = 0
SET
  @AllowUpdateInView_ab3c9c28 = 1
SET
  @IncludeInUserSearchAPI_ab3c9c28 = 0
SET
  @FullTextSearchEnabled_ab3c9c28 = 0
SET
  @IncludeInGeneratedForm_ab3c9c28 = 1
SET
  @GeneratedFormSection_ab3c9c28 = N'Details'
SET
  @IsNameField_ab3c9c28 = 1
SET
  @IncludeRelatedEntityNameFieldInBaseView_ab3c9c28 = 0
SET
  @RelatedEntityDisplayType_ab3c9c28 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_ab3c9c28 = 1
SET
  @ValuesToPackWithSchema_ab3c9c28 = N'Auto'
SET
  @Status_ab3c9c28 = N'Active'
SET
  @AutoUpdateIsNameField_ab3c9c28 = 0
SET
  @AutoUpdateDefaultInView_ab3c9c28 = 1
SET
  @AutoUpdateCategory_ab3c9c28 = 1
SET
  @AutoUpdateDisplayName_ab3c9c28 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_ab3c9c28 = 1
SET
  @Encrypt_ab3c9c28 = 0
SET
  @AllowDecryptInAPI_ab3c9c28 = 0
SET
  @SendEncryptedValue_ab3c9c28 = 0
SET
  @IsSoftPrimaryKey_ab3c9c28 = 0
SET
  @IsSoftForeignKey_ab3c9c28 = 0
SET
  @JSONTypeIsArray_ab3c9c28 = 0
SET
  @UserSearchPredicateAPI_ab3c9c28 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_ab3c9c28 = 1
SET
  @AutoUpdateFullTextSearch_ab3c9c28 = 1
SET
  @AutoUpdateExtendedType_ab3c9c28 = 1
SET
  @ID_ab3c9c28 = '76D49448-C586-4701-9FFF-63F390EC78C0' EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_ab3c9c28,
  @Description = @Description_ab3c9c28,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_ab3c9c28,
  @IsPrimaryKey = @IsPrimaryKey_ab3c9c28,
  @IsUnique = @IsUnique_ab3c9c28,
  @Category = @Category_ab3c9c28,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_ab3c9c28,
  @ExtendedType = @ExtendedType_ab3c9c28,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_ab3c9c28,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_ab3c9c28,
  @ViewCellTemplate = @ViewCellTemplate_ab3c9c28,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_ab3c9c28,
  @AllowUpdateAPI = @AllowUpdateAPI_ab3c9c28,
  @AllowUpdateInView = @AllowUpdateInView_ab3c9c28,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_ab3c9c28,
  @FullTextSearchEnabled = @FullTextSearchEnabled_ab3c9c28,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_ab3c9c28,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_ab3c9c28,
  @GeneratedFormSection = @GeneratedFormSection_ab3c9c28,
  @IsNameField = @IsNameField_ab3c9c28,
  @RelatedEntityID = @RelatedEntityID_ab3c9c28,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_ab3c9c28,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_ab3c9c28,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_ab3c9c28,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_ab3c9c28,
  @EntityIDFieldName = @EntityIDFieldName_ab3c9c28,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_ab3c9c28,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_ab3c9c28,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_ab3c9c28,
  @Status = @Status_ab3c9c28,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_ab3c9c28,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_ab3c9c28,
  @AutoUpdateCategory = @AutoUpdateCategory_ab3c9c28,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_ab3c9c28,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_ab3c9c28,
  @Encrypt = @Encrypt_ab3c9c28,
  @EncryptionKeyID = @EncryptionKeyID_ab3c9c28,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_ab3c9c28,
  @SendEncryptedValue = @SendEncryptedValue_ab3c9c28,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_ab3c9c28,
  @IsSoftForeignKey = @IsSoftForeignKey_ab3c9c28,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_ab3c9c28,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_ab3c9c28,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_ab3c9c28,
  @JSONTypeDefinition = @JSONTypeDefinition_ab3c9c28,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_ab3c9c28,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_ab3c9c28,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_ab3c9c28,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_ab3c9c28,
  @ID = @ID_ab3c9c28;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_2bdbcdff NVARCHAR(255),
@Description_2bdbcdff NVARCHAR(MAX),
@AutoUpdateDescription_2bdbcdff BIT,
@IsPrimaryKey_2bdbcdff BIT,
@IsUnique_2bdbcdff BIT,
@Category_2bdbcdff NVARCHAR(255),
@ValueListType_2bdbcdff NVARCHAR(20),
@ExtendedType_2bdbcdff NVARCHAR(50),
@CodeType_2bdbcdff NVARCHAR(50),
@DefaultInView_2bdbcdff BIT,
@ViewCellTemplate_2bdbcdff NVARCHAR(MAX),
@DefaultColumnWidth_2bdbcdff INT,
@AllowUpdateAPI_2bdbcdff BIT,
@AllowUpdateInView_2bdbcdff BIT,
@IncludeInUserSearchAPI_2bdbcdff BIT,
@FullTextSearchEnabled_2bdbcdff BIT,
@UserSearchParamFormatAPI_2bdbcdff NVARCHAR(500),
@IncludeInGeneratedForm_2bdbcdff BIT,
@GeneratedFormSection_2bdbcdff NVARCHAR(10),
@IsNameField_2bdbcdff BIT,
@RelatedEntityID_2bdbcdff UNIQUEIDENTIFIER,
@RelatedEntityFieldName_2bdbcdff NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_2bdbcdff BIT,
@RelatedEntityNameFieldMap_2bdbcdff NVARCHAR(255),
@RelatedEntityDisplayType_2bdbcdff NVARCHAR(20),
@EntityIDFieldName_2bdbcdff NVARCHAR(100),
@ScopeDefault_2bdbcdff NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_2bdbcdff BIT,
@ValuesToPackWithSchema_2bdbcdff NVARCHAR(10),
@Status_2bdbcdff NVARCHAR(25),
@AutoUpdateIsNameField_2bdbcdff BIT,
@AutoUpdateDefaultInView_2bdbcdff BIT,
@AutoUpdateCategory_2bdbcdff BIT,
@AutoUpdateDisplayName_2bdbcdff BIT,
@AutoUpdateIncludeInUserSearchAPI_2bdbcdff BIT,
@Encrypt_2bdbcdff BIT,
@EncryptionKeyID_2bdbcdff UNIQUEIDENTIFIER,
@AllowDecryptInAPI_2bdbcdff BIT,
@SendEncryptedValue_2bdbcdff BIT,
@IsSoftPrimaryKey_2bdbcdff BIT,
@IsSoftForeignKey_2bdbcdff BIT,
@RelatedEntityJoinFields_2bdbcdff NVARCHAR(MAX),
@JSONType_2bdbcdff NVARCHAR(255),
@JSONTypeIsArray_2bdbcdff BIT,
@JSONTypeDefinition_2bdbcdff NVARCHAR(MAX),
@UserSearchPredicateAPI_2bdbcdff NVARCHAR(20),
@AutoUpdateUserSearchPredicate_2bdbcdff BIT,
@AutoUpdateFullTextSearch_2bdbcdff BIT,
@AutoUpdateExtendedType_2bdbcdff BIT,
@ID_2bdbcdff UNIQUEIDENTIFIER
SET
  @DisplayName_2bdbcdff = N'Last Name'
SET
  @Description_2bdbcdff = N'Last (family) name'
SET
  @AutoUpdateDescription_2bdbcdff = 1
SET
  @IsPrimaryKey_2bdbcdff = 0
SET
  @IsUnique_2bdbcdff = 0
SET
  @Category_2bdbcdff = N'Personal Identity'
SET
  @ValueListType_2bdbcdff = N'None'
SET
  @DefaultInView_2bdbcdff = 1
SET
  @DefaultColumnWidth_2bdbcdff = 150
SET
  @AllowUpdateAPI_2bdbcdff = 1
SET
  @AllowUpdateInView_2bdbcdff = 1
SET
  @IncludeInUserSearchAPI_2bdbcdff = 1
SET
  @FullTextSearchEnabled_2bdbcdff = 0
SET
  @IncludeInGeneratedForm_2bdbcdff = 1
SET
  @GeneratedFormSection_2bdbcdff = N'Category'
SET
  @IsNameField_2bdbcdff = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_2bdbcdff = 0
SET
  @RelatedEntityDisplayType_2bdbcdff = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_2bdbcdff = 1
SET
  @ValuesToPackWithSchema_2bdbcdff = N'Auto'
SET
  @Status_2bdbcdff = N'Active'
SET
  @AutoUpdateIsNameField_2bdbcdff = 0
SET
  @AutoUpdateDefaultInView_2bdbcdff = 1
SET
  @AutoUpdateCategory_2bdbcdff = 1
SET
  @AutoUpdateDisplayName_2bdbcdff = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_2bdbcdff = 1
SET
  @Encrypt_2bdbcdff = 0
SET
  @AllowDecryptInAPI_2bdbcdff = 0
SET
  @SendEncryptedValue_2bdbcdff = 0
SET
  @IsSoftPrimaryKey_2bdbcdff = 0
SET
  @IsSoftForeignKey_2bdbcdff = 0
SET
  @JSONTypeIsArray_2bdbcdff = 0
SET
  @UserSearchPredicateAPI_2bdbcdff = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_2bdbcdff = 1
SET
  @AutoUpdateFullTextSearch_2bdbcdff = 1
SET
  @AutoUpdateExtendedType_2bdbcdff = 1
SET
  @ID_2bdbcdff = '09AD91DA-42C7-44F4-AE71-5AC6E50D7657' EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_2bdbcdff,
  @Description = @Description_2bdbcdff,
  @AutoUpdateDescription = @AutoUpdateDescription_2bdbcdff,
  @IsPrimaryKey = @IsPrimaryKey_2bdbcdff,
  @IsUnique = @IsUnique_2bdbcdff,
  @Category = @Category_2bdbcdff,
  @ValueListType = @ValueListType_2bdbcdff,
  @ExtendedType = @ExtendedType_2bdbcdff,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_2bdbcdff,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_2bdbcdff,
  @ViewCellTemplate = @ViewCellTemplate_2bdbcdff,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_2bdbcdff,
  @AllowUpdateAPI = @AllowUpdateAPI_2bdbcdff,
  @AllowUpdateInView = @AllowUpdateInView_2bdbcdff,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_2bdbcdff,
  @FullTextSearchEnabled = @FullTextSearchEnabled_2bdbcdff,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_2bdbcdff,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_2bdbcdff,
  @GeneratedFormSection = @GeneratedFormSection_2bdbcdff,
  @IsNameField = @IsNameField_2bdbcdff,
  @RelatedEntityID = @RelatedEntityID_2bdbcdff,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_2bdbcdff,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_2bdbcdff,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_2bdbcdff,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_2bdbcdff,
  @EntityIDFieldName = @EntityIDFieldName_2bdbcdff,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_2bdbcdff,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_2bdbcdff,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_2bdbcdff,
  @Status = @Status_2bdbcdff,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_2bdbcdff,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_2bdbcdff,
  @AutoUpdateCategory = @AutoUpdateCategory_2bdbcdff,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_2bdbcdff,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_2bdbcdff,
  @Encrypt = @Encrypt_2bdbcdff,
  @EncryptionKeyID = @EncryptionKeyID_2bdbcdff,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_2bdbcdff,
  @SendEncryptedValue = @SendEncryptedValue_2bdbcdff,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_2bdbcdff,
  @IsSoftForeignKey = @IsSoftForeignKey_2bdbcdff,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_2bdbcdff,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_2bdbcdff,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_2bdbcdff,
  @JSONTypeDefinition = @JSONTypeDefinition_2bdbcdff,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_2bdbcdff,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_2bdbcdff,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_2bdbcdff,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_2bdbcdff,
  @ID = @ID_2bdbcdff;

GO


-- End of SQL Logging Session
-- Session ID: 134655f8-85d5-43c2-b18d-da8ba5f27c8a
-- Completed: 2026-05-14T15:55:52.304Z
-- Duration: 1016ms
-- Total Statements: 39
