-- =============================================================================================
-- BizApps Common v5.48.x -- Metadata_Sync (one per release, generated by the build engineer)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --exclude users --ci` (MJ CLI 6.1.4) against a
-- database built from migrations ONLY: MJ core 6.1.4, then this app's migrations at `next`
-- (5.47.0's seed included; nothing unreleased held back). Checked column by column against a copy
-- of the database taken before the push.
--
-- SHIPS (2 updates) -- the People / Organization lookup fix (#199):
--   * People.PrimaryEmail     IncludeInUserSearchAPI 1 -> 0  (computed in vwPeople; no index can
--     serve it -- the 15-19 s Bill To Person lookups)
--   * Organizations.Website   IncludeInUserSearchAPI 1 -> 0  (stored with a scheme on most rows, so
--     BeginsWith missed them; an unindexed OR leg scans Organization)
-- spUpdateEntityField has the same parameters from MJ 6.1.0-edge.6 (the declared floor) to 6.1.4.
--
-- HELD BACK -- field-level security for People (#186). metadata/ declares EnableFieldLevelSecurity
-- on People, but hosts upgrade by migration only and never run the reconcile that writes
-- MJ: Entity Field Permissions rows; on an FLS-enabled entity a field with no row is denied to every
-- user. Shipping the flag needs (a) an MJ floor of 6.1.4 -- the column arrives in 6.1.0-edge.7 --
-- and (b) a host-side INSERT ... SELECT that applies MJ's snapshot rule to each host's own
-- EntityPermission rows. Both are tracked for the next release; until then the flag stays off on
-- hosts and People access is unchanged.
--
-- TRANSFORM: `EXEC [${flyway:defaultSchema}]` -> `EXEC [${mjSchema}]` (2). String values untouched.
-- Updates by fixed EntityField ID; re-running is a no-op.
-- =============================================================================================
-- SQL Logging Session
-- Session ID: b2af8cba-a9e1-42db-b61d-7ce56cf49ef2
-- Started: 2026-09-30T19:12:49.698Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_cf59da6c6440 NVARCHAR(255),
@Description_cf59da6c6440 NVARCHAR(MAX),
@AutoUpdateDescription_cf59da6c6440 BIT,
@IsPrimaryKey_cf59da6c6440 BIT,
@IsUnique_cf59da6c6440 BIT,
@Category_cf59da6c6440 NVARCHAR(255),
@ValueListType_cf59da6c6440 NVARCHAR(20),
@ExtendedType_cf59da6c6440 NVARCHAR(50),
@CodeType_cf59da6c6440 NVARCHAR(50),
@DefaultInView_cf59da6c6440 BIT,
@ViewCellTemplate_cf59da6c6440 NVARCHAR(MAX),
@DefaultColumnWidth_cf59da6c6440 INT,
@AllowUpdateAPI_cf59da6c6440 BIT,
@AllowUpdateInView_cf59da6c6440 BIT,
@IncludeInUserSearchAPI_cf59da6c6440 BIT,
@FullTextSearchEnabled_cf59da6c6440 BIT,
@UserSearchParamFormatAPI_cf59da6c6440 NVARCHAR(500),
@IncludeInGeneratedForm_cf59da6c6440 BIT,
@GeneratedFormSection_cf59da6c6440 NVARCHAR(10),
@IsNameField_cf59da6c6440 BIT,
@RelatedEntityID_cf59da6c6440 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_cf59da6c6440 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_cf59da6c6440 BIT,
@RelatedEntityNameFieldMap_cf59da6c6440 NVARCHAR(255),
@RelatedEntityDisplayType_cf59da6c6440 NVARCHAR(20),
@EntityIDFieldName_cf59da6c6440 NVARCHAR(100),
@ScopeDefault_cf59da6c6440 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_cf59da6c6440 BIT,
@ValuesToPackWithSchema_cf59da6c6440 NVARCHAR(10),
@Status_cf59da6c6440 NVARCHAR(25),
@AutoUpdateIsNameField_cf59da6c6440 BIT,
@AutoUpdateDefaultInView_cf59da6c6440 BIT,
@AutoUpdateCategory_cf59da6c6440 BIT,
@AutoUpdateDisplayName_cf59da6c6440 BIT,
@AutoUpdateIncludeInUserSearchAPI_cf59da6c6440 BIT,
@Encrypt_cf59da6c6440 BIT,
@EncryptionKeyID_cf59da6c6440 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_cf59da6c6440 BIT,
@SendEncryptedValue_cf59da6c6440 BIT,
@IsSoftPrimaryKey_cf59da6c6440 BIT,
@IsSoftForeignKey_cf59da6c6440 BIT,
@RelatedEntityJoinFields_cf59da6c6440 NVARCHAR(MAX),
@JSONType_cf59da6c6440 NVARCHAR(255),
@JSONTypeIsArray_cf59da6c6440 BIT,
@JSONTypeDefinition_cf59da6c6440 NVARCHAR(MAX),
@UserSearchPredicateAPI_cf59da6c6440 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_cf59da6c6440 BIT,
@AutoUpdateFullTextSearch_cf59da6c6440 BIT,
@AutoUpdateExtendedType_cf59da6c6440 BIT,
@IsComputed_cf59da6c6440 BIT,
@EmbeddedRecord_cf59da6c6440 NVARCHAR(MAX),
@Configuration_cf59da6c6440 NVARCHAR(MAX),
@ID_cf59da6c6440 UNIQUEIDENTIFIER
SET
  @DisplayName_cf59da6c6440 = N'Primary Email'
SET
  @AutoUpdateDescription_cf59da6c6440 = 1
SET
  @IsPrimaryKey_cf59da6c6440 = 0
SET
  @IsUnique_cf59da6c6440 = 0
SET
  @Category_cf59da6c6440 = N'Professional and Profile'
SET
  @ValueListType_cf59da6c6440 = N'None'
SET
  @ExtendedType_cf59da6c6440 = N'Email'
SET
  @DefaultInView_cf59da6c6440 = 1
SET
  @DefaultColumnWidth_cf59da6c6440 = 150
SET
  @AllowUpdateAPI_cf59da6c6440 = 0
SET
  @AllowUpdateInView_cf59da6c6440 = 1
SET
  @IncludeInUserSearchAPI_cf59da6c6440 = 0
SET
  @FullTextSearchEnabled_cf59da6c6440 = 0
SET
  @IncludeInGeneratedForm_cf59da6c6440 = 1
SET
  @GeneratedFormSection_cf59da6c6440 = N'Category'
SET
  @IsNameField_cf59da6c6440 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_cf59da6c6440 = 0
SET
  @RelatedEntityDisplayType_cf59da6c6440 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_cf59da6c6440 = 1
SET
  @ValuesToPackWithSchema_cf59da6c6440 = N'Auto'
SET
  @Status_cf59da6c6440 = N'Active'
SET
  @AutoUpdateIsNameField_cf59da6c6440 = 1
SET
  @AutoUpdateDefaultInView_cf59da6c6440 = 1
SET
  @AutoUpdateCategory_cf59da6c6440 = 1
SET
  @AutoUpdateDisplayName_cf59da6c6440 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_cf59da6c6440 = 0
SET
  @Encrypt_cf59da6c6440 = 0
SET
  @AllowDecryptInAPI_cf59da6c6440 = 0
SET
  @SendEncryptedValue_cf59da6c6440 = 0
SET
  @IsSoftPrimaryKey_cf59da6c6440 = 0
SET
  @IsSoftForeignKey_cf59da6c6440 = 0
SET
  @JSONTypeIsArray_cf59da6c6440 = 0
SET
  @UserSearchPredicateAPI_cf59da6c6440 = N'Exact'
SET
  @AutoUpdateUserSearchPredicate_cf59da6c6440 = 0
SET
  @AutoUpdateFullTextSearch_cf59da6c6440 = 1
SET
  @AutoUpdateExtendedType_cf59da6c6440 = 1
SET
  @IsComputed_cf59da6c6440 = 0
SET
  @ID_cf59da6c6440 = '2C5F0735-BCCE-4FFE-A225-DF937DACE682' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_cf59da6c6440,
  @Description = @Description_cf59da6c6440,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_cf59da6c6440,
  @IsPrimaryKey = @IsPrimaryKey_cf59da6c6440,
  @IsUnique = @IsUnique_cf59da6c6440,
  @Category = @Category_cf59da6c6440,
  @ValueListType = @ValueListType_cf59da6c6440,
  @ExtendedType = @ExtendedType_cf59da6c6440,
  @CodeType = @CodeType_cf59da6c6440,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_cf59da6c6440,
  @ViewCellTemplate = @ViewCellTemplate_cf59da6c6440,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_cf59da6c6440,
  @AllowUpdateAPI = @AllowUpdateAPI_cf59da6c6440,
  @AllowUpdateInView = @AllowUpdateInView_cf59da6c6440,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_cf59da6c6440,
  @FullTextSearchEnabled = @FullTextSearchEnabled_cf59da6c6440,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_cf59da6c6440,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_cf59da6c6440,
  @GeneratedFormSection = @GeneratedFormSection_cf59da6c6440,
  @IsNameField = @IsNameField_cf59da6c6440,
  @RelatedEntityID = @RelatedEntityID_cf59da6c6440,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_cf59da6c6440,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_cf59da6c6440,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_cf59da6c6440,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_cf59da6c6440,
  @EntityIDFieldName = @EntityIDFieldName_cf59da6c6440,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_cf59da6c6440,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_cf59da6c6440,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_cf59da6c6440,
  @Status = @Status_cf59da6c6440,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_cf59da6c6440,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_cf59da6c6440,
  @AutoUpdateCategory = @AutoUpdateCategory_cf59da6c6440,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_cf59da6c6440,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_cf59da6c6440,
  @Encrypt = @Encrypt_cf59da6c6440,
  @EncryptionKeyID = @EncryptionKeyID_cf59da6c6440,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_cf59da6c6440,
  @SendEncryptedValue = @SendEncryptedValue_cf59da6c6440,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_cf59da6c6440,
  @IsSoftForeignKey = @IsSoftForeignKey_cf59da6c6440,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_cf59da6c6440,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_cf59da6c6440,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_cf59da6c6440,
  @JSONTypeDefinition = @JSONTypeDefinition_cf59da6c6440,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_cf59da6c6440,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_cf59da6c6440,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_cf59da6c6440,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_cf59da6c6440,
  @IsComputed = @IsComputed_cf59da6c6440,
  @EmbeddedRecord = @EmbeddedRecord_cf59da6c6440,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_cf59da6c6440,
  @Configuration_Clear = 1,
  @ID = @ID_cf59da6c6440;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_f90efe6d7c1f NVARCHAR(255),
@Description_f90efe6d7c1f NVARCHAR(MAX),
@AutoUpdateDescription_f90efe6d7c1f BIT,
@IsPrimaryKey_f90efe6d7c1f BIT,
@IsUnique_f90efe6d7c1f BIT,
@Category_f90efe6d7c1f NVARCHAR(255),
@ValueListType_f90efe6d7c1f NVARCHAR(20),
@ExtendedType_f90efe6d7c1f NVARCHAR(50),
@CodeType_f90efe6d7c1f NVARCHAR(50),
@DefaultInView_f90efe6d7c1f BIT,
@ViewCellTemplate_f90efe6d7c1f NVARCHAR(MAX),
@DefaultColumnWidth_f90efe6d7c1f INT,
@AllowUpdateAPI_f90efe6d7c1f BIT,
@AllowUpdateInView_f90efe6d7c1f BIT,
@IncludeInUserSearchAPI_f90efe6d7c1f BIT,
@FullTextSearchEnabled_f90efe6d7c1f BIT,
@UserSearchParamFormatAPI_f90efe6d7c1f NVARCHAR(500),
@IncludeInGeneratedForm_f90efe6d7c1f BIT,
@GeneratedFormSection_f90efe6d7c1f NVARCHAR(10),
@IsNameField_f90efe6d7c1f BIT,
@RelatedEntityID_f90efe6d7c1f UNIQUEIDENTIFIER,
@RelatedEntityFieldName_f90efe6d7c1f NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_f90efe6d7c1f BIT,
@RelatedEntityNameFieldMap_f90efe6d7c1f NVARCHAR(255),
@RelatedEntityDisplayType_f90efe6d7c1f NVARCHAR(20),
@EntityIDFieldName_f90efe6d7c1f NVARCHAR(100),
@ScopeDefault_f90efe6d7c1f NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_f90efe6d7c1f BIT,
@ValuesToPackWithSchema_f90efe6d7c1f NVARCHAR(10),
@Status_f90efe6d7c1f NVARCHAR(25),
@AutoUpdateIsNameField_f90efe6d7c1f BIT,
@AutoUpdateDefaultInView_f90efe6d7c1f BIT,
@AutoUpdateCategory_f90efe6d7c1f BIT,
@AutoUpdateDisplayName_f90efe6d7c1f BIT,
@AutoUpdateIncludeInUserSearchAPI_f90efe6d7c1f BIT,
@Encrypt_f90efe6d7c1f BIT,
@EncryptionKeyID_f90efe6d7c1f UNIQUEIDENTIFIER,
@AllowDecryptInAPI_f90efe6d7c1f BIT,
@SendEncryptedValue_f90efe6d7c1f BIT,
@IsSoftPrimaryKey_f90efe6d7c1f BIT,
@IsSoftForeignKey_f90efe6d7c1f BIT,
@RelatedEntityJoinFields_f90efe6d7c1f NVARCHAR(MAX),
@JSONType_f90efe6d7c1f NVARCHAR(255),
@JSONTypeIsArray_f90efe6d7c1f BIT,
@JSONTypeDefinition_f90efe6d7c1f NVARCHAR(MAX),
@UserSearchPredicateAPI_f90efe6d7c1f NVARCHAR(20),
@AutoUpdateUserSearchPredicate_f90efe6d7c1f BIT,
@AutoUpdateFullTextSearch_f90efe6d7c1f BIT,
@AutoUpdateExtendedType_f90efe6d7c1f BIT,
@IsComputed_f90efe6d7c1f BIT,
@EmbeddedRecord_f90efe6d7c1f NVARCHAR(MAX),
@Configuration_f90efe6d7c1f NVARCHAR(MAX),
@ID_f90efe6d7c1f UNIQUEIDENTIFIER
SET
  @DisplayName_f90efe6d7c1f = N'Website'
SET
  @Description_f90efe6d7c1f = N'Primary website URL'
SET
  @AutoUpdateDescription_f90efe6d7c1f = 1
SET
  @IsPrimaryKey_f90efe6d7c1f = 0
SET
  @IsUnique_f90efe6d7c1f = 0
SET
  @Category_f90efe6d7c1f = N'Contact Information'
SET
  @ValueListType_f90efe6d7c1f = N'None'
SET
  @ExtendedType_f90efe6d7c1f = N'URL'
SET
  @DefaultInView_f90efe6d7c1f = 0
SET
  @DefaultColumnWidth_f90efe6d7c1f = 150
SET
  @AllowUpdateAPI_f90efe6d7c1f = 1
SET
  @AllowUpdateInView_f90efe6d7c1f = 1
SET
  @IncludeInUserSearchAPI_f90efe6d7c1f = 0
SET
  @FullTextSearchEnabled_f90efe6d7c1f = 0
SET
  @IncludeInGeneratedForm_f90efe6d7c1f = 1
SET
  @GeneratedFormSection_f90efe6d7c1f = N'Category'
SET
  @IsNameField_f90efe6d7c1f = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_f90efe6d7c1f = 0
SET
  @RelatedEntityDisplayType_f90efe6d7c1f = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_f90efe6d7c1f = 1
SET
  @ValuesToPackWithSchema_f90efe6d7c1f = N'Auto'
SET
  @Status_f90efe6d7c1f = N'Active'
SET
  @AutoUpdateIsNameField_f90efe6d7c1f = 1
SET
  @AutoUpdateDefaultInView_f90efe6d7c1f = 1
SET
  @AutoUpdateCategory_f90efe6d7c1f = 1
SET
  @AutoUpdateDisplayName_f90efe6d7c1f = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_f90efe6d7c1f = 0
SET
  @Encrypt_f90efe6d7c1f = 0
SET
  @AllowDecryptInAPI_f90efe6d7c1f = 0
SET
  @SendEncryptedValue_f90efe6d7c1f = 0
SET
  @IsSoftPrimaryKey_f90efe6d7c1f = 0
SET
  @IsSoftForeignKey_f90efe6d7c1f = 0
SET
  @JSONTypeIsArray_f90efe6d7c1f = 0
SET
  @UserSearchPredicateAPI_f90efe6d7c1f = N'BeginsWith'
SET
  @AutoUpdateUserSearchPredicate_f90efe6d7c1f = 0
SET
  @AutoUpdateFullTextSearch_f90efe6d7c1f = 1
SET
  @AutoUpdateExtendedType_f90efe6d7c1f = 1
SET
  @IsComputed_f90efe6d7c1f = 0
SET
  @ID_f90efe6d7c1f = 'C8C255E3-D3C1-4F3D-84AA-07B30981FB3E' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_f90efe6d7c1f,
  @Description = @Description_f90efe6d7c1f,
  @AutoUpdateDescription = @AutoUpdateDescription_f90efe6d7c1f,
  @IsPrimaryKey = @IsPrimaryKey_f90efe6d7c1f,
  @IsUnique = @IsUnique_f90efe6d7c1f,
  @Category = @Category_f90efe6d7c1f,
  @ValueListType = @ValueListType_f90efe6d7c1f,
  @ExtendedType = @ExtendedType_f90efe6d7c1f,
  @CodeType = @CodeType_f90efe6d7c1f,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_f90efe6d7c1f,
  @ViewCellTemplate = @ViewCellTemplate_f90efe6d7c1f,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_f90efe6d7c1f,
  @AllowUpdateAPI = @AllowUpdateAPI_f90efe6d7c1f,
  @AllowUpdateInView = @AllowUpdateInView_f90efe6d7c1f,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_f90efe6d7c1f,
  @FullTextSearchEnabled = @FullTextSearchEnabled_f90efe6d7c1f,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_f90efe6d7c1f,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_f90efe6d7c1f,
  @GeneratedFormSection = @GeneratedFormSection_f90efe6d7c1f,
  @IsNameField = @IsNameField_f90efe6d7c1f,
  @RelatedEntityID = @RelatedEntityID_f90efe6d7c1f,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_f90efe6d7c1f,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_f90efe6d7c1f,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_f90efe6d7c1f,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_f90efe6d7c1f,
  @EntityIDFieldName = @EntityIDFieldName_f90efe6d7c1f,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_f90efe6d7c1f,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_f90efe6d7c1f,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_f90efe6d7c1f,
  @Status = @Status_f90efe6d7c1f,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_f90efe6d7c1f,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_f90efe6d7c1f,
  @AutoUpdateCategory = @AutoUpdateCategory_f90efe6d7c1f,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_f90efe6d7c1f,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_f90efe6d7c1f,
  @Encrypt = @Encrypt_f90efe6d7c1f,
  @EncryptionKeyID = @EncryptionKeyID_f90efe6d7c1f,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_f90efe6d7c1f,
  @SendEncryptedValue = @SendEncryptedValue_f90efe6d7c1f,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_f90efe6d7c1f,
  @IsSoftForeignKey = @IsSoftForeignKey_f90efe6d7c1f,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_f90efe6d7c1f,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_f90efe6d7c1f,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_f90efe6d7c1f,
  @JSONTypeDefinition = @JSONTypeDefinition_f90efe6d7c1f,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_f90efe6d7c1f,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_f90efe6d7c1f,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_f90efe6d7c1f,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_f90efe6d7c1f,
  @IsComputed = @IsComputed_f90efe6d7c1f,
  @EmbeddedRecord = @EmbeddedRecord_f90efe6d7c1f,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_f90efe6d7c1f,
  @Configuration_Clear = 1,
  @ID = @ID_f90efe6d7c1f;

GO


-- End of SQL Logging Session
-- Session ID: b2af8cba-a9e1-42db-b61d-7ce56cf49ef2
-- Completed: 2026-09-30T19:13:19.395Z
-- Duration: 29697ms
-- Total Statements: 108
