-- =============================================================================
-- Activity: add SentimentScore column and CodeGen objects (FP-7 / P2-1)
-- =============================================================================

ALTER TABLE [${flyway:defaultSchema}].[Activity] ADD [SentimentScore] DECIMAL(4,3) NULL;
GO

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'Derived sentiment score for this activity, bounded between -1.000 (most negative) and +1.000 (most positive). Populated by the Activity Tagging and Sentiment feature pipeline.', 
    @level0type = N'SCHEMA', @level0name = '${flyway:defaultSchema}', 
    @level1type = N'TABLE', @level1name = 'Activity', 
    @level2type = N'COLUMN', @level2name = 'SentimentScore';
GO




















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Activities
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  Activity
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwActivities]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwActivities];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwActivities]
AS
SELECT
    a.*,
    mjBizAppsCommonActivityType_ActivityTypeID.[Name] AS [ActivityType],
    mjBizAppsCommonActivity_ParentActivityID.[Title] AS [ParentActivity],
    MJUser_LoggedByUserID.[Name] AS [LoggedByUser],
    mjBizAppsCommonAddress_AddressID.[Line1] AS [Address],
    mjBizAppsCommonActivitySyncConnection_ActivitySyncConnectionID.[Name] AS [ActivitySyncConnection],
    ${mjSchema}_rgc.[Latitude] AS [${mjSchema}_Latitude],
    ${mjSchema}_rgc.[Longitude] AS [${mjSchema}_Longitude],
    hier_ParentActivityID.RootID AS [RootParentActivityID],
    hier_ParentActivityID.Depth AS [ParentActivityIDDepth],
    hier_ParentActivityID.Path AS [ParentActivityIDPath],
    hier_ParentActivityID.IsLeaf AS [ParentActivityIDIsLeaf],
    hier_ParentActivityID.ChildCount AS [ParentActivityIDChildCount]
FROM
    [${flyway:defaultSchema}].[Activity] AS a
INNER JOIN
    [${flyway:defaultSchema}].[ActivityType] AS mjBizAppsCommonActivityType_ActivityTypeID
  ON
    [a].[ActivityTypeID] = mjBizAppsCommonActivityType_ActivityTypeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Activity] AS mjBizAppsCommonActivity_ParentActivityID
  ON
    [a].[ParentActivityID] = mjBizAppsCommonActivity_ParentActivityID.[ID]
INNER JOIN
    [${mjSchema}].[User] AS MJUser_LoggedByUserID
  ON
    [a].[LoggedByUserID] = MJUser_LoggedByUserID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Address] AS mjBizAppsCommonAddress_AddressID
  ON
    [a].[AddressID] = mjBizAppsCommonAddress_AddressID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ActivitySyncConnection] AS mjBizAppsCommonActivitySyncConnection_ActivitySyncConnectionID
  ON
    [a].[ActivitySyncConnectionID] = mjBizAppsCommonActivitySyncConnection_ActivitySyncConnectionID.[ID]
LEFT OUTER JOIN
    [${mjSchema}].[vwRecordGeoCodes] AS ${mjSchema}_rgc
  ON
    ${mjSchema}_rgc.[EntityID] = '72E55425-8822-4E70-A075-116219CA5A5D'
    AND ${mjSchema}_rgc.[RecordID] = CAST([a].[ID] AS NVARCHAR(450))
    AND ${mjSchema}_rgc.[LocationType] = 'Primary'
OUTER APPLY
    [${flyway:defaultSchema}].[fnActivityParentActivityID_GetHierarchyMeta]([a].[ID], [a].[ParentActivityID]) AS hier_ParentActivityID
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwActivities] TO [cdp_UI], [cdp_Developer], [cdp_Integration];
GO

------------------------------------------------------------
----- CREATE PROCEDURE FOR Activity
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateActivity]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateActivity];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateActivity]
    @ID uniqueidentifier = NULL,
    @ActivityTypeID uniqueidentifier,
    @StartedAt datetimeoffset,
    @EndedAt_Clear bit = 0,
    @EndedAt datetimeoffset = NULL,
    @Title nvarchar(500),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @Direction nvarchar(20),
    @Status nvarchar(20) = NULL,
    @Outcome_Clear bit = 0,
    @Outcome nvarchar(40) = NULL,
    @Visibility nvarchar(20) = NULL,
    @Source nvarchar(20) = NULL,
    @SourceSystem_Clear bit = 0,
    @SourceSystem nvarchar(80) = NULL,
    @ExternalID_Clear bit = 0,
    @ExternalID nvarchar(400) = NULL,
    @ExternalThreadID_Clear bit = 0,
    @ExternalThreadID nvarchar(400) = NULL,
    @ParentActivityID_Clear bit = 0,
    @ParentActivityID uniqueidentifier = NULL,
    @LoggedByUserID uniqueidentifier,
    @Location_Clear bit = 0,
    @Location nvarchar(500) = NULL,
    @AddressID_Clear bit = 0,
    @AddressID uniqueidentifier = NULL,
    @ActivitySyncConnectionID_Clear bit = 0,
    @ActivitySyncConnectionID uniqueidentifier = NULL,
    @Details_Clear bit = 0,
    @Details nvarchar(MAX) = NULL,
    @SentimentScore_Clear bit = 0,
    @SentimentScore decimal(4,3) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Activity]
            (
                [ID],
                [ActivityTypeID],
                [StartedAt],
                [EndedAt],
                [Title],
                [Description],
                [Direction],
                [Status],
                [Outcome],
                [Visibility],
                [Source],
                [SourceSystem],
                [ExternalID],
                [ExternalThreadID],
                [ParentActivityID],
                [LoggedByUserID],
                [Location],
                [AddressID],
                [ActivitySyncConnectionID],
                [Details],
                [SentimentScore]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ActivityTypeID,
                @StartedAt,
                CASE WHEN @EndedAt_Clear = 1 THEN NULL ELSE ISNULL(@EndedAt, NULL) END,
                @Title,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @Direction,
                ISNULL(@Status, 'Logged'),
                CASE WHEN @Outcome_Clear = 1 THEN NULL ELSE ISNULL(@Outcome, NULL) END,
                ISNULL(@Visibility, 'Internal'),
                ISNULL(@Source, 'Manual'),
                CASE WHEN @SourceSystem_Clear = 1 THEN NULL ELSE ISNULL(@SourceSystem, NULL) END,
                CASE WHEN @ExternalID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalID, NULL) END,
                CASE WHEN @ExternalThreadID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalThreadID, NULL) END,
                CASE WHEN @ParentActivityID_Clear = 1 THEN NULL ELSE ISNULL(@ParentActivityID, NULL) END,
                @LoggedByUserID,
                CASE WHEN @Location_Clear = 1 THEN NULL ELSE ISNULL(@Location, NULL) END,
                CASE WHEN @AddressID_Clear = 1 THEN NULL ELSE ISNULL(@AddressID, NULL) END,
                CASE WHEN @ActivitySyncConnectionID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncConnectionID, NULL) END,
                CASE WHEN @Details_Clear = 1 THEN NULL ELSE ISNULL(@Details, NULL) END,
                CASE WHEN @SentimentScore_Clear = 1 THEN NULL ELSE ISNULL(@SentimentScore, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Activity]
            (
                [ActivityTypeID],
                [StartedAt],
                [EndedAt],
                [Title],
                [Description],
                [Direction],
                [Status],
                [Outcome],
                [Visibility],
                [Source],
                [SourceSystem],
                [ExternalID],
                [ExternalThreadID],
                [ParentActivityID],
                [LoggedByUserID],
                [Location],
                [AddressID],
                [ActivitySyncConnectionID],
                [Details],
                [SentimentScore]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ActivityTypeID,
                @StartedAt,
                CASE WHEN @EndedAt_Clear = 1 THEN NULL ELSE ISNULL(@EndedAt, NULL) END,
                @Title,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @Direction,
                ISNULL(@Status, 'Logged'),
                CASE WHEN @Outcome_Clear = 1 THEN NULL ELSE ISNULL(@Outcome, NULL) END,
                ISNULL(@Visibility, 'Internal'),
                ISNULL(@Source, 'Manual'),
                CASE WHEN @SourceSystem_Clear = 1 THEN NULL ELSE ISNULL(@SourceSystem, NULL) END,
                CASE WHEN @ExternalID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalID, NULL) END,
                CASE WHEN @ExternalThreadID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalThreadID, NULL) END,
                CASE WHEN @ParentActivityID_Clear = 1 THEN NULL ELSE ISNULL(@ParentActivityID, NULL) END,
                @LoggedByUserID,
                CASE WHEN @Location_Clear = 1 THEN NULL ELSE ISNULL(@Location, NULL) END,
                CASE WHEN @AddressID_Clear = 1 THEN NULL ELSE ISNULL(@AddressID, NULL) END,
                CASE WHEN @ActivitySyncConnectionID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncConnectionID, NULL) END,
                CASE WHEN @Details_Clear = 1 THEN NULL ELSE ISNULL(@Details, NULL) END,
                CASE WHEN @SentimentScore_Clear = 1 THEN NULL ELSE ISNULL(@SentimentScore, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwActivities] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateActivity] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateActivity] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateActivity] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Activity
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateActivity]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateActivity];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateActivity]
    @ID uniqueidentifier,
    @ActivityTypeID uniqueidentifier = NULL,
    @StartedAt datetimeoffset = NULL,
    @EndedAt_Clear bit = 0,
    @EndedAt datetimeoffset = NULL,
    @Title nvarchar(500) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @Direction nvarchar(20) = NULL,
    @Status nvarchar(20) = NULL,
    @Outcome_Clear bit = 0,
    @Outcome nvarchar(40) = NULL,
    @Visibility nvarchar(20) = NULL,
    @Source nvarchar(20) = NULL,
    @SourceSystem_Clear bit = 0,
    @SourceSystem nvarchar(80) = NULL,
    @ExternalID_Clear bit = 0,
    @ExternalID nvarchar(400) = NULL,
    @ExternalThreadID_Clear bit = 0,
    @ExternalThreadID nvarchar(400) = NULL,
    @ParentActivityID_Clear bit = 0,
    @ParentActivityID uniqueidentifier = NULL,
    @LoggedByUserID uniqueidentifier = NULL,
    @Location_Clear bit = 0,
    @Location nvarchar(500) = NULL,
    @AddressID_Clear bit = 0,
    @AddressID uniqueidentifier = NULL,
    @ActivitySyncConnectionID_Clear bit = 0,
    @ActivitySyncConnectionID uniqueidentifier = NULL,
    @Details_Clear bit = 0,
    @Details nvarchar(MAX) = NULL,
    @SentimentScore_Clear bit = 0,
    @SentimentScore decimal(4,3) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Activity]
    SET
        [ActivityTypeID] = ISNULL(@ActivityTypeID, [ActivityTypeID]),
        [StartedAt] = ISNULL(@StartedAt, [StartedAt]),
        [EndedAt] = CASE WHEN @EndedAt_Clear = 1 THEN NULL ELSE ISNULL(@EndedAt, [EndedAt]) END,
        [Title] = ISNULL(@Title, [Title]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [Direction] = ISNULL(@Direction, [Direction]),
        [Status] = ISNULL(@Status, [Status]),
        [Outcome] = CASE WHEN @Outcome_Clear = 1 THEN NULL ELSE ISNULL(@Outcome, [Outcome]) END,
        [Visibility] = ISNULL(@Visibility, [Visibility]),
        [Source] = ISNULL(@Source, [Source]),
        [SourceSystem] = CASE WHEN @SourceSystem_Clear = 1 THEN NULL ELSE ISNULL(@SourceSystem, [SourceSystem]) END,
        [ExternalID] = CASE WHEN @ExternalID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalID, [ExternalID]) END,
        [ExternalThreadID] = CASE WHEN @ExternalThreadID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalThreadID, [ExternalThreadID]) END,
        [ParentActivityID] = CASE WHEN @ParentActivityID_Clear = 1 THEN NULL ELSE ISNULL(@ParentActivityID, [ParentActivityID]) END,
        [LoggedByUserID] = ISNULL(@LoggedByUserID, [LoggedByUserID]),
        [Location] = CASE WHEN @Location_Clear = 1 THEN NULL ELSE ISNULL(@Location, [Location]) END,
        [AddressID] = CASE WHEN @AddressID_Clear = 1 THEN NULL ELSE ISNULL(@AddressID, [AddressID]) END,
        [ActivitySyncConnectionID] = CASE WHEN @ActivitySyncConnectionID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncConnectionID, [ActivitySyncConnectionID]) END,
        [Details] = CASE WHEN @Details_Clear = 1 THEN NULL ELSE ISNULL(@Details, [Details]) END,
        [SentimentScore] = CASE WHEN @SentimentScore_Clear = 1 THEN NULL ELSE ISNULL(@SentimentScore, [SentimentScore]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwActivities] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
            *
        FROM
            [${flyway:defaultSchema}].[vwActivities]
        WHERE
            [ID] = @ID
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivity] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivity] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivity] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- DELETE PROCEDURE FOR Activity
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteActivity]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteActivity];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteActivity]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[Activity]
    WHERE
        [ID] = @ID

    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteActivity] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteActivity] TO [cdp_Integration]
GO

---------------------------------------------------------------------------
-- EntityField registration for Activity.SentimentScore
---------------------------------------------------------------------------
DECLARE @ActivityEntityID UNIQUEIDENTIFIER;
SELECT @ActivityEntityID = [ID]
  FROM [${mjSchema}].[Entity]
 WHERE [SchemaName] = '${flyway:defaultSchema}' AND [BaseTable] = 'Activity';
SET @ActivityEntityID = COALESCE(@ActivityEntityID, '72E55425-8822-4E70-A075-116219CA5A5D');

IF NOT EXISTS (
    SELECT 1 FROM [${mjSchema}].[EntityField]
     WHERE [EntityID] = @ActivityEntityID AND [Name] = 'SentimentScore'
)
BEGIN
    INSERT INTO [${mjSchema}].[EntityField] (
        [ID], [EntityID], [Sequence], [Name], [DisplayName],
        [Description], [Type], [Length], [Precision], [Scale],
        [AllowsNull], [DefaultValue], [AutoIncrement], [AllowUpdateAPI],
        [IsVirtual], [IsComputed], [RelatedEntityID], [RelatedEntityFieldName],
        [IsNameField], [IncludeInUserSearchAPI], [IncludeRelatedEntityNameFieldInBaseView],
        [DefaultInView], [IsPrimaryKey], [IsUnique], [RelatedEntityDisplayType],
        [__mj_CreatedAt], [__mj_UpdatedAt]
    ) VALUES (
        'f482a17c-2b9a-4d76-96a8-a3f12462e08d',
        @ActivityEntityID,
        (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = @ActivityEntityID),
        'SentimentScore', 'Sentiment Score',
        'Derived sentiment score for this activity, bounded between -1.000 and +1.000.', 'decimal', 5, 4, 3,
        1, NULL, 0, 1,
        0, 0, NULL, NULL,
        0, 0, 0,
        0, 0, 0, 'Search',
        GETUTCDATE(), GETUTCDATE()
    );
END
GO

-- Assert no missing EntityFields for Activity
IF EXISTS (
    SELECT 1
      FROM [${mjSchema}].[Entity] e
      JOIN INFORMATION_SCHEMA.COLUMNS c
        ON c.TABLE_SCHEMA = e.SchemaName AND c.TABLE_NAME = e.BaseView
      LEFT JOIN [${mjSchema}].[EntityField] ef
        ON ef.EntityID = e.ID AND ef.Name = c.COLUMN_NAME
     WHERE e.SchemaName = '${flyway:defaultSchema}'
       AND e.BaseTable = 'Activity'
       AND ef.ID IS NULL
)
BEGIN
    THROW 50001, 'Missing EntityField detected on Activity after migration', 1;
END

-- Assert no phantom EntityFields for Activity
IF EXISTS (
    SELECT 1
      FROM [${mjSchema}].[Entity] e
      JOIN [${mjSchema}].[EntityField] ef
        ON ef.EntityID = e.ID
      LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
        ON c.TABLE_SCHEMA = e.SchemaName AND c.TABLE_NAME = e.BaseView
       AND c.COLUMN_NAME = ef.Name
     WHERE e.SchemaName = '${flyway:defaultSchema}'
       AND e.BaseTable = 'Activity'
       AND c.COLUMN_NAME IS NULL
)
BEGIN
    THROW 50001, 'Phantom EntityField detected on Activity after migration', 1;
END
GO
