-- Companion calendar surface is data on ActivitySyncProviderType, not a literal on
-- the deprecated ActivitySyncConnection.Provider column (dropped as a CHECK in
-- V202608291500). A connection created the documented way — type FK set, Provider
-- NULL — must still get a calendar pass. The engine resolves CalendarDriverClass
-- through ClassFactory; it does not `new` the Graph calendar provider.
--
-- Hand-authored DDL only below. The Microsoft365 CalendarDriverClass value lives in
-- metadata/activity-sync-provider-types/ (devs: mj sync push; release: Metadata_Sync).
-- CodeGen output is appended after the banner; do not hand-edit below that line.

ALTER TABLE [${flyway:defaultSchema}].[ActivitySyncProviderType]
ADD [CalendarDriverClass] NVARCHAR(200) NULL;
GO

IF OBJECT_ID('[${flyway:defaultSchema}].[vwActivitySyncProviderTypes]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwActivitySyncProviderTypes];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwActivitySyncProviderTypes]
AS
SELECT
    a.*,
    MJEncryptionKey_DefaultEncryptionKeyID.[Name] AS [DefaultEncryptionKey],
    MJFileStorageProvider_DefaultStorageProviderID.[Name] AS [DefaultStorageProvider]
FROM
    [${flyway:defaultSchema}].[ActivitySyncProviderType] AS a
LEFT OUTER JOIN
    [${mjSchema}].[EncryptionKey] AS MJEncryptionKey_DefaultEncryptionKeyID
  ON
    [a].[DefaultEncryptionKeyID] = MJEncryptionKey_DefaultEncryptionKeyID.[ID]
LEFT OUTER JOIN
    [${mjSchema}].[FileStorageProvider] AS MJFileStorageProvider_DefaultStorageProviderID
  ON
    [a].[DefaultStorageProviderID] = MJFileStorageProvider_DefaultStorageProviderID.[ID]
GO


















































/**************************************************************************************************
 **************************************************************************************************
 **                                                                                              **
 **                 CODEGEN OUTPUT — ActivitySyncProviderType.CalendarDriverClass (v5.37.x)      **
 **                                                                                              **
 **  Everything below this banner is generated by `mj codegen` AFTER the hand-authored DDL above **
 **  was applied and the schema introspected. DO NOT hand-edit below this line.                   **
 **                                                                                              **
 **  Source: migrations/codegen/CodeGen_Run_2026-08-31_03-09-00.sql (not a Flyway migration).     **
 **                                                                                              **
 **************************************************************************************************
 **************************************************************************************************/
/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to insert 2 new entity field(s) */
      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '5868a298-8684-456b-ad63-5fec4af750d4' OR (EntityID = 'AD8B1485-8BE1-4E5C-8EFB-3B4FEA363F75' AND Name = 'CalendarDriverClass')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '5868a298-8684-456b-ad63-5fec4af750d4',
            'AD8B1485-8BE1-4E5C-8EFB-3B4FEA363F75', -- Entity: MJ_BizApps_Common: Activity Sync Provider Types
            (SELECT COALESCE(MAX([Sequence]), 0) FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'AD8B1485-8BE1-4E5C-8EFB-3B4FEA363F75') + 1,
            'CalendarDriverClass',
            'Calendar Driver Class',
            NULL,
            'nvarchar',
            400,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Index for Foreign Keys for ActivitySyncProviderType */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Provider Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key DefaultEncryptionKeyID in table ActivitySyncProviderType
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ActivitySyncProviderType_DefaultEncryptionKeyID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ActivitySyncProviderType]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ActivitySyncProviderType_DefaultEncryptionKeyID ON [${flyway:defaultSchema}].[ActivitySyncProviderType] ([DefaultEncryptionKeyID]);

-- Index for foreign key DefaultStorageProviderID in table ActivitySyncProviderType
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ActivitySyncProviderType_DefaultStorageProviderID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ActivitySyncProviderType]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ActivitySyncProviderType_DefaultStorageProviderID ON [${flyway:defaultSchema}].[ActivitySyncProviderType] ([DefaultStorageProviderID]);

/* Base View SQL for MJ_BizApps_Common: Activity Sync Provider Types */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Provider Types
-- Item: vwActivitySyncProviderTypes
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Activity Sync Provider Types
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ActivitySyncProviderType
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwActivitySyncProviderTypes]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwActivitySyncProviderTypes];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwActivitySyncProviderTypes]
AS
SELECT
    a.*,
    MJEncryptionKey_DefaultEncryptionKeyID.[Name] AS [DefaultEncryptionKey],
    MJFileStorageProvider_DefaultStorageProviderID.[Name] AS [DefaultStorageProvider]
FROM
    [${flyway:defaultSchema}].[ActivitySyncProviderType] AS a
LEFT OUTER JOIN
    [${mjSchema}].[EncryptionKey] AS MJEncryptionKey_DefaultEncryptionKeyID
  ON
    [a].[DefaultEncryptionKeyID] = MJEncryptionKey_DefaultEncryptionKeyID.[ID]
LEFT OUTER JOIN
    [${mjSchema}].[FileStorageProvider] AS MJFileStorageProvider_DefaultStorageProviderID
  ON
    [a].[DefaultStorageProviderID] = MJFileStorageProvider_DefaultStorageProviderID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwActivitySyncProviderTypes] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Activity Sync Provider Types */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Provider Types
-- Item: Permissions for vwActivitySyncProviderTypes
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwActivitySyncProviderTypes] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Activity Sync Provider Types */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Provider Types
-- Item: spCreateActivitySyncProviderType
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ActivitySyncProviderType
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateActivitySyncProviderType]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateActivitySyncProviderType];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateActivitySyncProviderType]
    @ID uniqueidentifier = NULL,
    @Code nvarchar(60),
    @Name nvarchar(100),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @DriverClass_Clear bit = 0,
    @DriverClass nvarchar(200) = NULL,
    @IconClass_Clear bit = 0,
    @IconClass nvarchar(100) = NULL,
    @SupportedKinds_Clear bit = 0,
    @SupportedKinds nvarchar(MAX) = NULL,
    @DefaultQualificationPolicy nvarchar(20) = NULL,
    @DefaultSkippedContentPolicy nvarchar(20) = NULL,
    @DefaultEncryptionKeyID_Clear bit = 0,
    @DefaultEncryptionKeyID uniqueidentifier = NULL,
    @DefaultStorageProviderID_Clear bit = 0,
    @DefaultStorageProviderID uniqueidentifier = NULL,
    @DefaultMaxAttachmentBytes_Clear bit = 0,
    @DefaultMaxAttachmentBytes bigint = NULL,
    @Sequence int = NULL,
    @IsSystem bit = NULL,
    @IsActive bit = NULL,
    @CalendarDriverClass_Clear bit = 0,
    @CalendarDriverClass nvarchar(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ActivitySyncProviderType]
            (
                [ID],
                [Code],
                [Name],
                [Description],
                [DriverClass],
                [IconClass],
                [SupportedKinds],
                [DefaultQualificationPolicy],
                [DefaultSkippedContentPolicy],
                [DefaultEncryptionKeyID],
                [DefaultStorageProviderID],
                [DefaultMaxAttachmentBytes],
                [Sequence],
                [IsSystem],
                [IsActive],
                [CalendarDriverClass]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Code,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                CASE WHEN @DriverClass_Clear = 1 THEN NULL ELSE ISNULL(@DriverClass, NULL) END,
                CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, NULL) END,
                CASE WHEN @SupportedKinds_Clear = 1 THEN NULL ELSE ISNULL(@SupportedKinds, NULL) END,
                ISNULL(@DefaultQualificationPolicy, 'Exclude'),
                ISNULL(@DefaultSkippedContentPolicy, 'None'),
                CASE WHEN @DefaultEncryptionKeyID_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEncryptionKeyID, NULL) END,
                CASE WHEN @DefaultStorageProviderID_Clear = 1 THEN NULL ELSE ISNULL(@DefaultStorageProviderID, NULL) END,
                CASE WHEN @DefaultMaxAttachmentBytes_Clear = 1 THEN NULL ELSE ISNULL(@DefaultMaxAttachmentBytes, NULL) END,
                ISNULL(@Sequence, 0),
                ISNULL(@IsSystem, 0),
                ISNULL(@IsActive, 1),
                CASE WHEN @CalendarDriverClass_Clear = 1 THEN NULL ELSE ISNULL(@CalendarDriverClass, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ActivitySyncProviderType]
            (
                [Code],
                [Name],
                [Description],
                [DriverClass],
                [IconClass],
                [SupportedKinds],
                [DefaultQualificationPolicy],
                [DefaultSkippedContentPolicy],
                [DefaultEncryptionKeyID],
                [DefaultStorageProviderID],
                [DefaultMaxAttachmentBytes],
                [Sequence],
                [IsSystem],
                [IsActive],
                [CalendarDriverClass]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Code,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                CASE WHEN @DriverClass_Clear = 1 THEN NULL ELSE ISNULL(@DriverClass, NULL) END,
                CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, NULL) END,
                CASE WHEN @SupportedKinds_Clear = 1 THEN NULL ELSE ISNULL(@SupportedKinds, NULL) END,
                ISNULL(@DefaultQualificationPolicy, 'Exclude'),
                ISNULL(@DefaultSkippedContentPolicy, 'None'),
                CASE WHEN @DefaultEncryptionKeyID_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEncryptionKeyID, NULL) END,
                CASE WHEN @DefaultStorageProviderID_Clear = 1 THEN NULL ELSE ISNULL(@DefaultStorageProviderID, NULL) END,
                CASE WHEN @DefaultMaxAttachmentBytes_Clear = 1 THEN NULL ELSE ISNULL(@DefaultMaxAttachmentBytes, NULL) END,
                ISNULL(@Sequence, 0),
                ISNULL(@IsSystem, 0),
                ISNULL(@IsActive, 1),
                CASE WHEN @CalendarDriverClass_Clear = 1 THEN NULL ELSE ISNULL(@CalendarDriverClass, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwActivitySyncProviderTypes] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateActivitySyncProviderType] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Activity Sync Provider Types */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateActivitySyncProviderType] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Activity Sync Provider Types */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Provider Types
-- Item: spUpdateActivitySyncProviderType
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ActivitySyncProviderType
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateActivitySyncProviderType]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateActivitySyncProviderType];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateActivitySyncProviderType]
    @ID uniqueidentifier,
    @Code nvarchar(60) = NULL,
    @Name nvarchar(100) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @DriverClass_Clear bit = 0,
    @DriverClass nvarchar(200) = NULL,
    @IconClass_Clear bit = 0,
    @IconClass nvarchar(100) = NULL,
    @SupportedKinds_Clear bit = 0,
    @SupportedKinds nvarchar(MAX) = NULL,
    @DefaultQualificationPolicy nvarchar(20) = NULL,
    @DefaultSkippedContentPolicy nvarchar(20) = NULL,
    @DefaultEncryptionKeyID_Clear bit = 0,
    @DefaultEncryptionKeyID uniqueidentifier = NULL,
    @DefaultStorageProviderID_Clear bit = 0,
    @DefaultStorageProviderID uniqueidentifier = NULL,
    @DefaultMaxAttachmentBytes_Clear bit = 0,
    @DefaultMaxAttachmentBytes bigint = NULL,
    @Sequence int = NULL,
    @IsSystem bit = NULL,
    @IsActive bit = NULL,
    @CalendarDriverClass_Clear bit = 0,
    @CalendarDriverClass nvarchar(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ActivitySyncProviderType]
    SET
        [Code] = ISNULL(@Code, [Code]),
        [Name] = ISNULL(@Name, [Name]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [DriverClass] = CASE WHEN @DriverClass_Clear = 1 THEN NULL ELSE ISNULL(@DriverClass, [DriverClass]) END,
        [IconClass] = CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, [IconClass]) END,
        [SupportedKinds] = CASE WHEN @SupportedKinds_Clear = 1 THEN NULL ELSE ISNULL(@SupportedKinds, [SupportedKinds]) END,
        [DefaultQualificationPolicy] = ISNULL(@DefaultQualificationPolicy, [DefaultQualificationPolicy]),
        [DefaultSkippedContentPolicy] = ISNULL(@DefaultSkippedContentPolicy, [DefaultSkippedContentPolicy]),
        [DefaultEncryptionKeyID] = CASE WHEN @DefaultEncryptionKeyID_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEncryptionKeyID, [DefaultEncryptionKeyID]) END,
        [DefaultStorageProviderID] = CASE WHEN @DefaultStorageProviderID_Clear = 1 THEN NULL ELSE ISNULL(@DefaultStorageProviderID, [DefaultStorageProviderID]) END,
        [DefaultMaxAttachmentBytes] = CASE WHEN @DefaultMaxAttachmentBytes_Clear = 1 THEN NULL ELSE ISNULL(@DefaultMaxAttachmentBytes, [DefaultMaxAttachmentBytes]) END,
        [Sequence] = ISNULL(@Sequence, [Sequence]),
        [IsSystem] = ISNULL(@IsSystem, [IsSystem]),
        [IsActive] = ISNULL(@IsActive, [IsActive]),
        [CalendarDriverClass] = CASE WHEN @CalendarDriverClass_Clear = 1 THEN NULL ELSE ISNULL(@CalendarDriverClass, [CalendarDriverClass]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwActivitySyncProviderTypes] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwActivitySyncProviderTypes]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivitySyncProviderType] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ActivitySyncProviderType table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateActivitySyncProviderType]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateActivitySyncProviderType];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateActivitySyncProviderType
ON [${flyway:defaultSchema}].[ActivitySyncProviderType]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ActivitySyncProviderType]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ActivitySyncProviderType] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Activity Sync Provider Types */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivitySyncProviderType] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Activity Sync Provider Types */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Provider Types
-- Item: spDeleteActivitySyncProviderType
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ActivitySyncProviderType
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteActivitySyncProviderType]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteActivitySyncProviderType];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteActivitySyncProviderType]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ActivitySyncProviderType]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteActivitySyncProviderType] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Activity Sync Provider Types */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteActivitySyncProviderType] TO [cdp_Developer], [cdp_Integration];

/* SQL text to update entity field related entity name field map for entity field ID B7BE5C0E-E4D5-42FC-9B82-C0FD25DE4B2A */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='B7BE5C0E-E4D5-42FC-9B82-C0FD25DE4B2A', @RelatedEntityNameFieldMap='ActivitySyncExclusion';

/* Base View SQL for MJ_BizApps_Common: Activity Sync Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Run Details
-- Item: vwActivitySyncRunDetails
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Activity Sync Run Details
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ActivitySyncRunDetail
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwActivitySyncRunDetails]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwActivitySyncRunDetails];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwActivitySyncRunDetails]
AS
SELECT
    a.*,
    mjBizAppsCommonActivitySyncRule_ActivitySyncRuleID.[Name] AS [ActivitySyncRule],
    mjBizAppsCommonActivitySyncExclusion_ActivitySyncExclusionID.[IdentityValue] AS [ActivitySyncExclusion],
    mjBizAppsCommonActivity_ActivityID.[Title] AS [Activity],
    MJEncryptionKey_EncryptionKeyID.[Name] AS [EncryptionKey]
FROM
    [${flyway:defaultSchema}].[ActivitySyncRunDetail] AS a
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ActivitySyncRule] AS mjBizAppsCommonActivitySyncRule_ActivitySyncRuleID
  ON
    [a].[ActivitySyncRuleID] = mjBizAppsCommonActivitySyncRule_ActivitySyncRuleID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ActivitySyncExclusion] AS mjBizAppsCommonActivitySyncExclusion_ActivitySyncExclusionID
  ON
    [a].[ActivitySyncExclusionID] = mjBizAppsCommonActivitySyncExclusion_ActivitySyncExclusionID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Activity] AS mjBizAppsCommonActivity_ActivityID
  ON
    [a].[ActivityID] = mjBizAppsCommonActivity_ActivityID.[ID]
LEFT OUTER JOIN
    [${mjSchema}].[EncryptionKey] AS MJEncryptionKey_EncryptionKeyID
  ON
    [a].[EncryptionKeyID] = MJEncryptionKey_EncryptionKeyID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwActivitySyncRunDetails] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Activity Sync Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Run Details
-- Item: Permissions for vwActivitySyncRunDetails
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwActivitySyncRunDetails] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Activity Sync Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Run Details
-- Item: spCreateActivitySyncRunDetail
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ActivitySyncRunDetail
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateActivitySyncRunDetail]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateActivitySyncRunDetail];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateActivitySyncRunDetail]
    @ID uniqueidentifier = NULL,
    @ActivitySyncRunID uniqueidentifier,
    @ExternalID nvarchar(400),
    @ExternalThreadID_Clear bit = 0,
    @ExternalThreadID nvarchar(400) = NULL,
    @OccurredAt_Clear bit = 0,
    @OccurredAt datetimeoffset = NULL,
    @Decision nvarchar(20),
    @DecidedByStage_Clear bit = 0,
    @DecidedByStage nvarchar(100) = NULL,
    @ActivitySyncRuleID_Clear bit = 0,
    @ActivitySyncRuleID uniqueidentifier = NULL,
    @ActivitySyncExclusionID_Clear bit = 0,
    @ActivitySyncExclusionID uniqueidentifier = NULL,
    @Reason_Clear bit = 0,
    @Reason nvarchar(MAX) = NULL,
    @Confidence_Clear bit = 0,
    @Confidence decimal(5, 4) = NULL,
    @AIPromptRunID_Clear bit = 0,
    @AIPromptRunID uniqueidentifier = NULL,
    @ActivityID_Clear bit = 0,
    @ActivityID uniqueidentifier = NULL,
    @CapturedContent_Clear bit = 0,
    @CapturedContent nvarchar(MAX) = NULL,
    @EncryptionKeyID_Clear bit = 0,
    @EncryptionKeyID uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ActivitySyncRunDetail]
            (
                [ID],
                [ActivitySyncRunID],
                [ExternalID],
                [ExternalThreadID],
                [OccurredAt],
                [Decision],
                [DecidedByStage],
                [ActivitySyncRuleID],
                [ActivitySyncExclusionID],
                [Reason],
                [Confidence],
                [AIPromptRunID],
                [ActivityID],
                [CapturedContent],
                [EncryptionKeyID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ActivitySyncRunID,
                @ExternalID,
                CASE WHEN @ExternalThreadID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalThreadID, NULL) END,
                CASE WHEN @OccurredAt_Clear = 1 THEN NULL ELSE ISNULL(@OccurredAt, NULL) END,
                @Decision,
                CASE WHEN @DecidedByStage_Clear = 1 THEN NULL ELSE ISNULL(@DecidedByStage, NULL) END,
                CASE WHEN @ActivitySyncRuleID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncRuleID, NULL) END,
                CASE WHEN @ActivitySyncExclusionID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncExclusionID, NULL) END,
                CASE WHEN @Reason_Clear = 1 THEN NULL ELSE ISNULL(@Reason, NULL) END,
                CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, NULL) END,
                CASE WHEN @AIPromptRunID_Clear = 1 THEN NULL ELSE ISNULL(@AIPromptRunID, NULL) END,
                CASE WHEN @ActivityID_Clear = 1 THEN NULL ELSE ISNULL(@ActivityID, NULL) END,
                CASE WHEN @CapturedContent_Clear = 1 THEN NULL ELSE ISNULL(@CapturedContent, NULL) END,
                CASE WHEN @EncryptionKeyID_Clear = 1 THEN NULL ELSE ISNULL(@EncryptionKeyID, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ActivitySyncRunDetail]
            (
                [ActivitySyncRunID],
                [ExternalID],
                [ExternalThreadID],
                [OccurredAt],
                [Decision],
                [DecidedByStage],
                [ActivitySyncRuleID],
                [ActivitySyncExclusionID],
                [Reason],
                [Confidence],
                [AIPromptRunID],
                [ActivityID],
                [CapturedContent],
                [EncryptionKeyID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ActivitySyncRunID,
                @ExternalID,
                CASE WHEN @ExternalThreadID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalThreadID, NULL) END,
                CASE WHEN @OccurredAt_Clear = 1 THEN NULL ELSE ISNULL(@OccurredAt, NULL) END,
                @Decision,
                CASE WHEN @DecidedByStage_Clear = 1 THEN NULL ELSE ISNULL(@DecidedByStage, NULL) END,
                CASE WHEN @ActivitySyncRuleID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncRuleID, NULL) END,
                CASE WHEN @ActivitySyncExclusionID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncExclusionID, NULL) END,
                CASE WHEN @Reason_Clear = 1 THEN NULL ELSE ISNULL(@Reason, NULL) END,
                CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, NULL) END,
                CASE WHEN @AIPromptRunID_Clear = 1 THEN NULL ELSE ISNULL(@AIPromptRunID, NULL) END,
                CASE WHEN @ActivityID_Clear = 1 THEN NULL ELSE ISNULL(@ActivityID, NULL) END,
                CASE WHEN @CapturedContent_Clear = 1 THEN NULL ELSE ISNULL(@CapturedContent, NULL) END,
                CASE WHEN @EncryptionKeyID_Clear = 1 THEN NULL ELSE ISNULL(@EncryptionKeyID, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwActivitySyncRunDetails] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateActivitySyncRunDetail] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Activity Sync Run Details */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateActivitySyncRunDetail] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Activity Sync Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Run Details
-- Item: spUpdateActivitySyncRunDetail
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ActivitySyncRunDetail
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateActivitySyncRunDetail]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateActivitySyncRunDetail];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateActivitySyncRunDetail]
    @ID uniqueidentifier,
    @ActivitySyncRunID uniqueidentifier = NULL,
    @ExternalID nvarchar(400) = NULL,
    @ExternalThreadID_Clear bit = 0,
    @ExternalThreadID nvarchar(400) = NULL,
    @OccurredAt_Clear bit = 0,
    @OccurredAt datetimeoffset = NULL,
    @Decision nvarchar(20) = NULL,
    @DecidedByStage_Clear bit = 0,
    @DecidedByStage nvarchar(100) = NULL,
    @ActivitySyncRuleID_Clear bit = 0,
    @ActivitySyncRuleID uniqueidentifier = NULL,
    @ActivitySyncExclusionID_Clear bit = 0,
    @ActivitySyncExclusionID uniqueidentifier = NULL,
    @Reason_Clear bit = 0,
    @Reason nvarchar(MAX) = NULL,
    @Confidence_Clear bit = 0,
    @Confidence decimal(5, 4) = NULL,
    @AIPromptRunID_Clear bit = 0,
    @AIPromptRunID uniqueidentifier = NULL,
    @ActivityID_Clear bit = 0,
    @ActivityID uniqueidentifier = NULL,
    @CapturedContent_Clear bit = 0,
    @CapturedContent nvarchar(MAX) = NULL,
    @EncryptionKeyID_Clear bit = 0,
    @EncryptionKeyID uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ActivitySyncRunDetail]
    SET
        [ActivitySyncRunID] = ISNULL(@ActivitySyncRunID, [ActivitySyncRunID]),
        [ExternalID] = ISNULL(@ExternalID, [ExternalID]),
        [ExternalThreadID] = CASE WHEN @ExternalThreadID_Clear = 1 THEN NULL ELSE ISNULL(@ExternalThreadID, [ExternalThreadID]) END,
        [OccurredAt] = CASE WHEN @OccurredAt_Clear = 1 THEN NULL ELSE ISNULL(@OccurredAt, [OccurredAt]) END,
        [Decision] = ISNULL(@Decision, [Decision]),
        [DecidedByStage] = CASE WHEN @DecidedByStage_Clear = 1 THEN NULL ELSE ISNULL(@DecidedByStage, [DecidedByStage]) END,
        [ActivitySyncRuleID] = CASE WHEN @ActivitySyncRuleID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncRuleID, [ActivitySyncRuleID]) END,
        [ActivitySyncExclusionID] = CASE WHEN @ActivitySyncExclusionID_Clear = 1 THEN NULL ELSE ISNULL(@ActivitySyncExclusionID, [ActivitySyncExclusionID]) END,
        [Reason] = CASE WHEN @Reason_Clear = 1 THEN NULL ELSE ISNULL(@Reason, [Reason]) END,
        [Confidence] = CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, [Confidence]) END,
        [AIPromptRunID] = CASE WHEN @AIPromptRunID_Clear = 1 THEN NULL ELSE ISNULL(@AIPromptRunID, [AIPromptRunID]) END,
        [ActivityID] = CASE WHEN @ActivityID_Clear = 1 THEN NULL ELSE ISNULL(@ActivityID, [ActivityID]) END,
        [CapturedContent] = CASE WHEN @CapturedContent_Clear = 1 THEN NULL ELSE ISNULL(@CapturedContent, [CapturedContent]) END,
        [EncryptionKeyID] = CASE WHEN @EncryptionKeyID_Clear = 1 THEN NULL ELSE ISNULL(@EncryptionKeyID, [EncryptionKeyID]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwActivitySyncRunDetails] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwActivitySyncRunDetails]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivitySyncRunDetail] TO [cdp_Developer]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ActivitySyncRunDetail table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateActivitySyncRunDetail]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateActivitySyncRunDetail];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateActivitySyncRunDetail
ON [${flyway:defaultSchema}].[ActivitySyncRunDetail]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ActivitySyncRunDetail]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ActivitySyncRunDetail] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Activity Sync Run Details */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateActivitySyncRunDetail] TO [cdp_Developer];

/* spDelete SQL for MJ_BizApps_Common: Activity Sync Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Activity Sync Run Details
-- Item: spDeleteActivitySyncRunDetail
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ActivitySyncRunDetail
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteActivitySyncRunDetail]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteActivitySyncRunDetail];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteActivitySyncRunDetail]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ActivitySyncRunDetail]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteActivitySyncRunDetail] TO [cdp_Developer];

/* spDelete Permissions for MJ_BizApps_Common: Activity Sync Run Details */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteActivitySyncRunDetail] TO [cdp_Developer];

/* SQL text to delete unneeded entity fields (1 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='', @EntityIDs='AD8B1485-8BE1-4E5C-8EFB-3B4FEA363F75', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to update existing entity fields from schema (1 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='', @EntityIDs='AD8B1485-8BE1-4E5C-8EFB-3B4FEA363F75', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Set categories for 20 fields */

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.ID 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '57A720BD-8CB1-4429-95DD-150C529FF1DD' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.__mj_CreatedAt 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5E0546DD-7EA6-48ED-81DF-3B9BFAE705CD' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.__mj_UpdatedAt 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'FFCD695A-8745-44BA-AF76-B532F8BD5DB5' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.Code 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '52553D7E-79DA-4DFD-9CC3-5F551E411DE5' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.Name 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'E3A328E8-5B81-48D7-9021-21EF3E67E3C2' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.Description 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B4BA9BC4-5776-424B-B009-5EBB50CA712F' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.Sequence 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '8F863005-AA6E-40A3-8EDE-5601E45281E0' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DriverClass 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B89E3F6E-BEDB-4CE4-82F8-29C1FF23B809' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.IconClass 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '43042F34-0DD3-4789-BD19-F3AE56CC733C' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.SupportedKinds 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2C86F25A-3816-4EC0-8885-06E4399313E0' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.IsSystem 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'F609014D-E4D4-41A9-B26C-A12871CC782C' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.IsActive 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D6351250-3C56-41CB-A5C1-003DF4812FC3' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.CalendarDriverClass 
UPDATE [${mjSchema}].[EntityField]
SET 
   Category = 'Provider Configuration',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5868A298-8684-456B-AD63-5FEC4AF750D4' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultQualificationPolicy 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2B27DE14-383F-4D07-9DCF-050237CEC7C7' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultSkippedContentPolicy 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '10FDAF3A-2042-41F1-B148-BEFFC8FCB001' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultEncryptionKeyID 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5E2EFFE9-2376-454D-8F8C-7E967E27E485' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultStorageProviderID 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D1C50585-1359-49B7-A011-6D590570B9E1' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultMaxAttachmentBytes 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '827D6B7C-BA37-446C-A9C1-912320C1AFF3' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultEncryptionKey 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'AE2C135E-282F-485C-947B-396CC6E36548' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info MJ_BizApps_Common: Activity Sync Provider Types.DefaultStorageProvider 
UPDATE [${mjSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '51369D06-BCEE-4156-93BB-E8C09BF0D7F1' AND AutoUpdateCategory = 1;

