-- =====================================================================
-- v5.29 Person DisplayName Wireup
-- =====================================================================
--
-- Regenerates BAC's views and stored procedures now that
-- Person.DisplayName.IsNameField=1 (flipped by the immediately-prior
-- V202605141056__v5.29.x__Metadata_Sync migration).
--
-- The earlier V202605131929 (Add Person DisplayName Computed Column)
-- migration installed views/sprocs that read Person.LastName for the
-- FromPerson/ToPerson virtual columns on vwRelationships (because at
-- that point LastName was still the auto-picked IsNameField).
-- Now that DisplayName is the registered IsNameField, this migration
-- re-emits those artifacts to reference Person.DisplayName instead.
--
-- Generated by `mj codegen` against a DB where all prior migrations
-- AND the Metadata_Sync had been applied. The trailing-semicolon
-- bug after CREATE TRIGGER blocks (`GO;` -> `GO`) is fixed here
-- inline; this is a CodeGen template bug that should be patched
-- upstream in MJ.
--
-- =====================================================================

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'dc5ebc38-46d2-414c-ac64-fa81b7efc19a' OR (EntityID = '32C45078-D33B-4760-9BE5-0DF7F483F591' AND Name = 'Person')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'dc5ebc38-46d2-414c-ac64-fa81b7efc19a',
            '32C45078-D33B-4760-9BE5-0DF7F483F591', -- Entity: MJ_BizApps_Common: Contact Methods
            100021,
            'Person',
            'Person',
            NULL,
            'nvarchar',
            200,
            0,
            0,
            1,
            NULL,
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '99d4fe49-bc0b-4d9d-b7ec-84e04f7281ee' OR (EntityID = 'F2FC2E85-B210-43A9-8565-290AD9D0C6E7' AND Name = 'Address')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '99d4fe49-bc0b-4d9d-b7ec-84e04f7281ee',
            'F2FC2E85-B210-43A9-8565-290AD9D0C6E7', -- Entity: MJ_BizApps_Common: Address Links
            100021,
            'Address',
            'Address',
            NULL,
            'nvarchar',
            510,
            0,
            0,
            0,
            NULL,
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '0f3e3c98-748b-4b54-9604-27f16e69b5b3' OR (EntityID = '709CA9DA-B124-4155-BE39-E857EF672D82' AND Name = 'FromPerson')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '0f3e3c98-748b-4b54-9604-27f16e69b5b3',
            '709CA9DA-B124-4155-BE39-E857EF672D82', -- Entity: MJ_BizApps_Common: Relationships
            100031,
            'FromPerson',
            'From Person',
            NULL,
            'nvarchar',
            200,
            0,
            0,
            1,
            NULL,
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '045230a0-3fed-4fec-94bd-cfc3dbf18245' OR (EntityID = '709CA9DA-B124-4155-BE39-E857EF672D82' AND Name = 'ToPerson')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '045230a0-3fed-4fec-94bd-cfc3dbf18245',
            '709CA9DA-B124-4155-BE39-E857EF672D82', -- Entity: MJ_BizApps_Common: Relationships
            100033,
            'ToPerson',
            'To Person',
            NULL,
            'nvarchar',
            200,
            0,
            0,
            1,
            NULL,
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* Index for Foreign Keys for AddressLink */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key AddressID in table AddressLink
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AddressLink_AddressID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[AddressLink]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AddressLink_AddressID ON [${flyway:defaultSchema}].[AddressLink] ([AddressID]);

-- Index for foreign key EntityID in table AddressLink
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AddressLink_EntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[AddressLink]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AddressLink_EntityID ON [${flyway:defaultSchema}].[AddressLink] ([EntityID]);

-- Index for foreign key AddressTypeID in table AddressLink
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AddressLink_AddressTypeID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[AddressLink]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AddressLink_AddressTypeID ON [${flyway:defaultSchema}].[AddressLink] ([AddressTypeID]);

/* Index for Foreign Keys for ContactMethod */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Contact Methods
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key PersonID in table ContactMethod
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ContactMethod_PersonID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ContactMethod]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ContactMethod_PersonID ON [${flyway:defaultSchema}].[ContactMethod] ([PersonID]);

-- Index for foreign key OrganizationID in table ContactMethod
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ContactMethod_OrganizationID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ContactMethod]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ContactMethod_OrganizationID ON [${flyway:defaultSchema}].[ContactMethod] ([OrganizationID]);

-- Index for foreign key ContactTypeID in table ContactMethod
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ContactMethod_ContactTypeID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ContactMethod]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ContactMethod_ContactTypeID ON [${flyway:defaultSchema}].[ContactMethod] ([ContactTypeID]);

/* Base View SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: vwAddressLinks
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Address Links
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  AddressLink
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwAddressLinks]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwAddressLinks];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwAddressLinks]
AS
SELECT
    a.*,
    mjBizAppsCommonAddress_AddressID.[Line1] AS [Address],
    MJEntity_EntityID.[Name] AS [Entity],
    mjBizAppsCommonAddressType_AddressTypeID.[Name] AS [AddressType]
FROM
    [${flyway:defaultSchema}].[AddressLink] AS a
INNER JOIN
    [${flyway:defaultSchema}].[Address] AS mjBizAppsCommonAddress_AddressID
  ON
    [a].[AddressID] = mjBizAppsCommonAddress_AddressID.[ID]
INNER JOIN
    [${mjSchema}].[Entity] AS MJEntity_EntityID
  ON
    [a].[EntityID] = MJEntity_EntityID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[AddressType] AS mjBizAppsCommonAddressType_AddressTypeID
  ON
    [a].[AddressTypeID] = mjBizAppsCommonAddressType_AddressTypeID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: Permissions for vwAddressLinks
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwAddressLinks] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: spCreateAddressLink
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR AddressLink
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateAddressLink]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateAddressLink];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateAddressLink]
    @ID uniqueidentifier = NULL,
    @AddressID uniqueidentifier,
    @EntityID uniqueidentifier,
    @RecordID nvarchar(700),
    @AddressTypeID uniqueidentifier,
    @IsPrimary bit = NULL,
    @Rank_Clear bit = 0,
    @Rank int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[AddressLink]
            (
                [ID],
                [AddressID],
                [EntityID],
                [RecordID],
                [AddressTypeID],
                [IsPrimary],
                [Rank]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @AddressID,
                @EntityID,
                @RecordID,
                @AddressTypeID,
                ISNULL(@IsPrimary, 0),
                CASE WHEN @Rank_Clear = 1 THEN NULL ELSE ISNULL(@Rank, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[AddressLink]
            (
                [AddressID],
                [EntityID],
                [RecordID],
                [AddressTypeID],
                [IsPrimary],
                [Rank]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @AddressID,
                @EntityID,
                @RecordID,
                @AddressTypeID,
                ISNULL(@IsPrimary, 0),
                CASE WHEN @Rank_Clear = 1 THEN NULL ELSE ISNULL(@Rank, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwAddressLinks] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Address Links */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAddressLink] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: spUpdateAddressLink
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR AddressLink
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateAddressLink]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateAddressLink];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateAddressLink]
    @ID uniqueidentifier,
    @AddressID uniqueidentifier = NULL,
    @EntityID uniqueidentifier = NULL,
    @RecordID nvarchar(700) = NULL,
    @AddressTypeID uniqueidentifier = NULL,
    @IsPrimary bit = NULL,
    @Rank_Clear bit = 0,
    @Rank int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[AddressLink]
    SET
        [AddressID] = ISNULL(@AddressID, [AddressID]),
        [EntityID] = ISNULL(@EntityID, [EntityID]),
        [RecordID] = ISNULL(@RecordID, [RecordID]),
        [AddressTypeID] = ISNULL(@AddressTypeID, [AddressTypeID]),
        [IsPrimary] = ISNULL(@IsPrimary, [IsPrimary]),
        [Rank] = CASE WHEN @Rank_Clear = 1 THEN NULL ELSE ISNULL(@Rank, [Rank]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwAddressLinks] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwAddressLinks]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the AddressLink table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateAddressLink]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateAddressLink];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateAddressLink
ON [${flyway:defaultSchema}].[AddressLink]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[AddressLink]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[AddressLink] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Address Links */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAddressLink] TO [cdp_Developer], [cdp_Integration];

/* Base View SQL for MJ_BizApps_Common: Contact Methods */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Contact Methods
-- Item: vwContactMethods
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Contact Methods
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ContactMethod
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwContactMethods]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwContactMethods];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwContactMethods]
AS
SELECT
    c.*,
    mjBizAppsCommonPerson_PersonID.[DisplayName] AS [Person],
    mjBizAppsCommonOrganization_OrganizationID.[Name] AS [Organization],
    mjBizAppsCommonContactType_ContactTypeID.[Name] AS [ContactType]
FROM
    [${flyway:defaultSchema}].[ContactMethod] AS c
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[vwPeople] AS mjBizAppsCommonPerson_PersonID
  ON
    [c].[PersonID] = mjBizAppsCommonPerson_PersonID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Organization] AS mjBizAppsCommonOrganization_OrganizationID
  ON
    [c].[OrganizationID] = mjBizAppsCommonOrganization_OrganizationID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[ContactType] AS mjBizAppsCommonContactType_ContactTypeID
  ON
    [c].[ContactTypeID] = mjBizAppsCommonContactType_ContactTypeID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwContactMethods] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Contact Methods */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Contact Methods
-- Item: Permissions for vwContactMethods
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwContactMethods] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Contact Methods */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Contact Methods
-- Item: spCreateContactMethod
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ContactMethod
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateContactMethod]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateContactMethod];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateContactMethod]
    @ID uniqueidentifier = NULL,
    @PersonID_Clear bit = 0,
    @PersonID uniqueidentifier = NULL,
    @OrganizationID_Clear bit = 0,
    @OrganizationID uniqueidentifier = NULL,
    @ContactTypeID uniqueidentifier,
    @Value nvarchar(500),
    @Label_Clear bit = 0,
    @Label nvarchar(100) = NULL,
    @IsPrimary bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ContactMethod]
            (
                [ID],
                [PersonID],
                [OrganizationID],
                [ContactTypeID],
                [Value],
                [Label],
                [IsPrimary]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                CASE WHEN @PersonID_Clear = 1 THEN NULL ELSE ISNULL(@PersonID, NULL) END,
                CASE WHEN @OrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@OrganizationID, NULL) END,
                @ContactTypeID,
                @Value,
                CASE WHEN @Label_Clear = 1 THEN NULL ELSE ISNULL(@Label, NULL) END,
                ISNULL(@IsPrimary, 0)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ContactMethod]
            (
                [PersonID],
                [OrganizationID],
                [ContactTypeID],
                [Value],
                [Label],
                [IsPrimary]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                CASE WHEN @PersonID_Clear = 1 THEN NULL ELSE ISNULL(@PersonID, NULL) END,
                CASE WHEN @OrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@OrganizationID, NULL) END,
                @ContactTypeID,
                @Value,
                CASE WHEN @Label_Clear = 1 THEN NULL ELSE ISNULL(@Label, NULL) END,
                ISNULL(@IsPrimary, 0)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwContactMethods] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateContactMethod] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Contact Methods */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateContactMethod] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Contact Methods */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Contact Methods
-- Item: spUpdateContactMethod
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ContactMethod
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateContactMethod]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateContactMethod];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateContactMethod]
    @ID uniqueidentifier,
    @PersonID_Clear bit = 0,
    @PersonID uniqueidentifier = NULL,
    @OrganizationID_Clear bit = 0,
    @OrganizationID uniqueidentifier = NULL,
    @ContactTypeID uniqueidentifier = NULL,
    @Value nvarchar(500) = NULL,
    @Label_Clear bit = 0,
    @Label nvarchar(100) = NULL,
    @IsPrimary bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ContactMethod]
    SET
        [PersonID] = CASE WHEN @PersonID_Clear = 1 THEN NULL ELSE ISNULL(@PersonID, [PersonID]) END,
        [OrganizationID] = CASE WHEN @OrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@OrganizationID, [OrganizationID]) END,
        [ContactTypeID] = ISNULL(@ContactTypeID, [ContactTypeID]),
        [Value] = ISNULL(@Value, [Value]),
        [Label] = CASE WHEN @Label_Clear = 1 THEN NULL ELSE ISNULL(@Label, [Label]) END,
        [IsPrimary] = ISNULL(@IsPrimary, [IsPrimary])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwContactMethods] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwContactMethods]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateContactMethod] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ContactMethod table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateContactMethod]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateContactMethod];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateContactMethod
ON [${flyway:defaultSchema}].[ContactMethod]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ContactMethod]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ContactMethod] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Contact Methods */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateContactMethod] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Address Links */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Address Links
-- Item: spDeleteAddressLink
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR AddressLink
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteAddressLink]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteAddressLink];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteAddressLink]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[AddressLink]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddressLink] TO [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Address Links */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAddressLink] TO [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Contact Methods */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Contact Methods
-- Item: spDeleteContactMethod
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ContactMethod
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteContactMethod]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteContactMethod];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteContactMethod]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ContactMethod]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteContactMethod] TO [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Contact Methods */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteContactMethod] TO [cdp_Integration];

/* Index for Foreign Keys for Relationship */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Relationships
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key RelationshipTypeID in table Relationship
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Relationship_RelationshipTypeID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Relationship]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Relationship_RelationshipTypeID ON [${flyway:defaultSchema}].[Relationship] ([RelationshipTypeID]);

-- Index for foreign key FromPersonID in table Relationship
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Relationship_FromPersonID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Relationship]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Relationship_FromPersonID ON [${flyway:defaultSchema}].[Relationship] ([FromPersonID]);

-- Index for foreign key FromOrganizationID in table Relationship
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Relationship_FromOrganizationID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Relationship]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Relationship_FromOrganizationID ON [${flyway:defaultSchema}].[Relationship] ([FromOrganizationID]);

-- Index for foreign key ToPersonID in table Relationship
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Relationship_ToPersonID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Relationship]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Relationship_ToPersonID ON [${flyway:defaultSchema}].[Relationship] ([ToPersonID]);

-- Index for foreign key ToOrganizationID in table Relationship
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Relationship_ToOrganizationID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Relationship]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Relationship_ToOrganizationID ON [${flyway:defaultSchema}].[Relationship] ([ToOrganizationID]);

/* Base View SQL for MJ_BizApps_Common: Relationships */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Relationships
-- Item: vwRelationships
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Common: Relationships
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  Relationship
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwRelationships]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwRelationships];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwRelationships]
AS
SELECT
    r.*,
    mjBizAppsCommonRelationshipType_RelationshipTypeID.[Name] AS [RelationshipType],
    mjBizAppsCommonPerson_FromPersonID.[DisplayName] AS [FromPerson],
    mjBizAppsCommonOrganization_FromOrganizationID.[Name] AS [FromOrganization],
    mjBizAppsCommonPerson_ToPersonID.[DisplayName] AS [ToPerson],
    mjBizAppsCommonOrganization_ToOrganizationID.[Name] AS [ToOrganization]
FROM
    [${flyway:defaultSchema}].[Relationship] AS r
INNER JOIN
    [${flyway:defaultSchema}].[RelationshipType] AS mjBizAppsCommonRelationshipType_RelationshipTypeID
  ON
    [r].[RelationshipTypeID] = mjBizAppsCommonRelationshipType_RelationshipTypeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[vwPeople] AS mjBizAppsCommonPerson_FromPersonID
  ON
    [r].[FromPersonID] = mjBizAppsCommonPerson_FromPersonID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Organization] AS mjBizAppsCommonOrganization_FromOrganizationID
  ON
    [r].[FromOrganizationID] = mjBizAppsCommonOrganization_FromOrganizationID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[vwPeople] AS mjBizAppsCommonPerson_ToPersonID
  ON
    [r].[ToPersonID] = mjBizAppsCommonPerson_ToPersonID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Organization] AS mjBizAppsCommonOrganization_ToOrganizationID
  ON
    [r].[ToOrganizationID] = mjBizAppsCommonOrganization_ToOrganizationID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwRelationships] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Common: Relationships */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Relationships
-- Item: Permissions for vwRelationships
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwRelationships] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Common: Relationships */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Relationships
-- Item: spCreateRelationship
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Relationship
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateRelationship]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateRelationship];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateRelationship]
    @ID uniqueidentifier = NULL,
    @RelationshipTypeID uniqueidentifier,
    @FromPersonID_Clear bit = 0,
    @FromPersonID uniqueidentifier = NULL,
    @FromOrganizationID_Clear bit = 0,
    @FromOrganizationID uniqueidentifier = NULL,
    @ToPersonID_Clear bit = 0,
    @ToPersonID uniqueidentifier = NULL,
    @ToOrganizationID_Clear bit = 0,
    @ToOrganizationID uniqueidentifier = NULL,
    @Title_Clear bit = 0,
    @Title nvarchar(255) = NULL,
    @StartDate_Clear bit = 0,
    @StartDate date = NULL,
    @EndDate_Clear bit = 0,
    @EndDate date = NULL,
    @Status nvarchar(50) = NULL,
    @Notes_Clear bit = 0,
    @Notes nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Relationship]
            (
                [ID],
                [RelationshipTypeID],
                [FromPersonID],
                [FromOrganizationID],
                [ToPersonID],
                [ToOrganizationID],
                [Title],
                [StartDate],
                [EndDate],
                [Status],
                [Notes]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @RelationshipTypeID,
                CASE WHEN @FromPersonID_Clear = 1 THEN NULL ELSE ISNULL(@FromPersonID, NULL) END,
                CASE WHEN @FromOrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@FromOrganizationID, NULL) END,
                CASE WHEN @ToPersonID_Clear = 1 THEN NULL ELSE ISNULL(@ToPersonID, NULL) END,
                CASE WHEN @ToOrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@ToOrganizationID, NULL) END,
                CASE WHEN @Title_Clear = 1 THEN NULL ELSE ISNULL(@Title, NULL) END,
                CASE WHEN @StartDate_Clear = 1 THEN NULL ELSE ISNULL(@StartDate, NULL) END,
                CASE WHEN @EndDate_Clear = 1 THEN NULL ELSE ISNULL(@EndDate, NULL) END,
                ISNULL(@Status, 'Active'),
                CASE WHEN @Notes_Clear = 1 THEN NULL ELSE ISNULL(@Notes, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Relationship]
            (
                [RelationshipTypeID],
                [FromPersonID],
                [FromOrganizationID],
                [ToPersonID],
                [ToOrganizationID],
                [Title],
                [StartDate],
                [EndDate],
                [Status],
                [Notes]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @RelationshipTypeID,
                CASE WHEN @FromPersonID_Clear = 1 THEN NULL ELSE ISNULL(@FromPersonID, NULL) END,
                CASE WHEN @FromOrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@FromOrganizationID, NULL) END,
                CASE WHEN @ToPersonID_Clear = 1 THEN NULL ELSE ISNULL(@ToPersonID, NULL) END,
                CASE WHEN @ToOrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@ToOrganizationID, NULL) END,
                CASE WHEN @Title_Clear = 1 THEN NULL ELSE ISNULL(@Title, NULL) END,
                CASE WHEN @StartDate_Clear = 1 THEN NULL ELSE ISNULL(@StartDate, NULL) END,
                CASE WHEN @EndDate_Clear = 1 THEN NULL ELSE ISNULL(@EndDate, NULL) END,
                ISNULL(@Status, 'Active'),
                CASE WHEN @Notes_Clear = 1 THEN NULL ELSE ISNULL(@Notes, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwRelationships] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateRelationship] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Common: Relationships */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateRelationship] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Common: Relationships */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Relationships
-- Item: spUpdateRelationship
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Relationship
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateRelationship]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateRelationship];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateRelationship]
    @ID uniqueidentifier,
    @RelationshipTypeID uniqueidentifier = NULL,
    @FromPersonID_Clear bit = 0,
    @FromPersonID uniqueidentifier = NULL,
    @FromOrganizationID_Clear bit = 0,
    @FromOrganizationID uniqueidentifier = NULL,
    @ToPersonID_Clear bit = 0,
    @ToPersonID uniqueidentifier = NULL,
    @ToOrganizationID_Clear bit = 0,
    @ToOrganizationID uniqueidentifier = NULL,
    @Title_Clear bit = 0,
    @Title nvarchar(255) = NULL,
    @StartDate_Clear bit = 0,
    @StartDate date = NULL,
    @EndDate_Clear bit = 0,
    @EndDate date = NULL,
    @Status nvarchar(50) = NULL,
    @Notes_Clear bit = 0,
    @Notes nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Relationship]
    SET
        [RelationshipTypeID] = ISNULL(@RelationshipTypeID, [RelationshipTypeID]),
        [FromPersonID] = CASE WHEN @FromPersonID_Clear = 1 THEN NULL ELSE ISNULL(@FromPersonID, [FromPersonID]) END,
        [FromOrganizationID] = CASE WHEN @FromOrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@FromOrganizationID, [FromOrganizationID]) END,
        [ToPersonID] = CASE WHEN @ToPersonID_Clear = 1 THEN NULL ELSE ISNULL(@ToPersonID, [ToPersonID]) END,
        [ToOrganizationID] = CASE WHEN @ToOrganizationID_Clear = 1 THEN NULL ELSE ISNULL(@ToOrganizationID, [ToOrganizationID]) END,
        [Title] = CASE WHEN @Title_Clear = 1 THEN NULL ELSE ISNULL(@Title, [Title]) END,
        [StartDate] = CASE WHEN @StartDate_Clear = 1 THEN NULL ELSE ISNULL(@StartDate, [StartDate]) END,
        [EndDate] = CASE WHEN @EndDate_Clear = 1 THEN NULL ELSE ISNULL(@EndDate, [EndDate]) END,
        [Status] = ISNULL(@Status, [Status]),
        [Notes] = CASE WHEN @Notes_Clear = 1 THEN NULL ELSE ISNULL(@Notes, [Notes]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwRelationships] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwRelationships]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateRelationship] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Relationship table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateRelationship]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateRelationship];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateRelationship
ON [${flyway:defaultSchema}].[Relationship]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Relationship]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[Relationship] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Common: Relationships */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateRelationship] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Relationships */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Relationships
-- Item: spDeleteRelationship
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Relationship
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteRelationship]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteRelationship];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteRelationship]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[Relationship]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteRelationship] TO [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Relationships */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteRelationship] TO [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Common: Organizations */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Common: Organizations
-- Item: spDeleteOrganization
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Organization
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteOrganization]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteOrganization];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteOrganization]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    -- Cascade update on ContactMethod using cursor to call spUpdateContactMethod
    DECLARE @mjBizAppsCommonContactMethods_OrganizationIDID uniqueidentifier
    DECLARE @mjBizAppsCommonContactMethods_OrganizationID_PersonID uniqueidentifier
    DECLARE @mjBizAppsCommonContactMethods_OrganizationID_OrganizationID uniqueidentifier
    DECLARE @mjBizAppsCommonContactMethods_OrganizationID_ContactTypeID uniqueidentifier
    DECLARE @mjBizAppsCommonContactMethods_OrganizationID_Value nvarchar(500)
    DECLARE @mjBizAppsCommonContactMethods_OrganizationID_Label nvarchar(100)
    DECLARE @mjBizAppsCommonContactMethods_OrganizationID_IsPrimary bit
    DECLARE cascade_update_mjBizAppsCommonContactMethods_OrganizationID_cursor CURSOR FOR
        SELECT [ID], [PersonID], [OrganizationID], [ContactTypeID], [Value], [Label], [IsPrimary]
        FROM [${flyway:defaultSchema}].[ContactMethod]
        WHERE [OrganizationID] = @ID

    OPEN cascade_update_mjBizAppsCommonContactMethods_OrganizationID_cursor
    FETCH NEXT FROM cascade_update_mjBizAppsCommonContactMethods_OrganizationID_cursor INTO @mjBizAppsCommonContactMethods_OrganizationIDID, @mjBizAppsCommonContactMethods_OrganizationID_PersonID, @mjBizAppsCommonContactMethods_OrganizationID_OrganizationID, @mjBizAppsCommonContactMethods_OrganizationID_ContactTypeID, @mjBizAppsCommonContactMethods_OrganizationID_Value, @mjBizAppsCommonContactMethods_OrganizationID_Label, @mjBizAppsCommonContactMethods_OrganizationID_IsPrimary

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Set the FK field to NULL
        SET @mjBizAppsCommonContactMethods_OrganizationID_OrganizationID = NULL

        -- Call the update SP for the related entity
        EXEC [${flyway:defaultSchema}].[spUpdateContactMethod] @ID = @mjBizAppsCommonContactMethods_OrganizationIDID, @PersonID = @mjBizAppsCommonContactMethods_OrganizationID_PersonID, @OrganizationID_Clear = 1, @OrganizationID = @mjBizAppsCommonContactMethods_OrganizationID_OrganizationID, @ContactTypeID = @mjBizAppsCommonContactMethods_OrganizationID_ContactTypeID, @Value = @mjBizAppsCommonContactMethods_OrganizationID_Value, @Label = @mjBizAppsCommonContactMethods_OrganizationID_Label, @IsPrimary = @mjBizAppsCommonContactMethods_OrganizationID_IsPrimary

        FETCH NEXT FROM cascade_update_mjBizAppsCommonContactMethods_OrganizationID_cursor INTO @mjBizAppsCommonContactMethods_OrganizationIDID, @mjBizAppsCommonContactMethods_OrganizationID_PersonID, @mjBizAppsCommonContactMethods_OrganizationID_OrganizationID, @mjBizAppsCommonContactMethods_OrganizationID_ContactTypeID, @mjBizAppsCommonContactMethods_OrganizationID_Value, @mjBizAppsCommonContactMethods_OrganizationID_Label, @mjBizAppsCommonContactMethods_OrganizationID_IsPrimary
    END

    CLOSE cascade_update_mjBizAppsCommonContactMethods_OrganizationID_cursor
    DEALLOCATE cascade_update_mjBizAppsCommonContactMethods_OrganizationID_cursor
    
    -- Cascade update on Organization using cursor to call spUpdateOrganization
    DECLARE @mjBizAppsCommonOrganizations_ParentIDID uniqueidentifier
    DECLARE @mjBizAppsCommonOrganizations_ParentID_Name nvarchar(255)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_LegalName nvarchar(255)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_OrganizationTypeID uniqueidentifier
    DECLARE @mjBizAppsCommonOrganizations_ParentID_ParentID uniqueidentifier
    DECLARE @mjBizAppsCommonOrganizations_ParentID_Website nvarchar(1000)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_LogoURL nvarchar(1000)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_Description nvarchar(MAX)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_Email nvarchar(255)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_Phone nvarchar(50)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_FoundedDate date
    DECLARE @mjBizAppsCommonOrganizations_ParentID_TaxID nvarchar(50)
    DECLARE @mjBizAppsCommonOrganizations_ParentID_Status nvarchar(50)
    DECLARE cascade_update_mjBizAppsCommonOrganizations_ParentID_cursor CURSOR FOR
        SELECT [ID], [Name], [LegalName], [OrganizationTypeID], [ParentID], [Website], [LogoURL], [Description], [Email], [Phone], [FoundedDate], [TaxID], [Status]
        FROM [${flyway:defaultSchema}].[Organization]
        WHERE [ParentID] = @ID

    OPEN cascade_update_mjBizAppsCommonOrganizations_ParentID_cursor
    FETCH NEXT FROM cascade_update_mjBizAppsCommonOrganizations_ParentID_cursor INTO @mjBizAppsCommonOrganizations_ParentIDID, @mjBizAppsCommonOrganizations_ParentID_Name, @mjBizAppsCommonOrganizations_ParentID_LegalName, @mjBizAppsCommonOrganizations_ParentID_OrganizationTypeID, @mjBizAppsCommonOrganizations_ParentID_ParentID, @mjBizAppsCommonOrganizations_ParentID_Website, @mjBizAppsCommonOrganizations_ParentID_LogoURL, @mjBizAppsCommonOrganizations_ParentID_Description, @mjBizAppsCommonOrganizations_ParentID_Email, @mjBizAppsCommonOrganizations_ParentID_Phone, @mjBizAppsCommonOrganizations_ParentID_FoundedDate, @mjBizAppsCommonOrganizations_ParentID_TaxID, @mjBizAppsCommonOrganizations_ParentID_Status

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Set the FK field to NULL
        SET @mjBizAppsCommonOrganizations_ParentID_ParentID = NULL

        -- Call the update SP for the related entity
        EXEC [${flyway:defaultSchema}].[spUpdateOrganization] @ID = @mjBizAppsCommonOrganizations_ParentIDID, @Name = @mjBizAppsCommonOrganizations_ParentID_Name, @LegalName = @mjBizAppsCommonOrganizations_ParentID_LegalName, @OrganizationTypeID = @mjBizAppsCommonOrganizations_ParentID_OrganizationTypeID, @ParentID_Clear = 1, @ParentID = @mjBizAppsCommonOrganizations_ParentID_ParentID, @Website = @mjBizAppsCommonOrganizations_ParentID_Website, @LogoURL = @mjBizAppsCommonOrganizations_ParentID_LogoURL, @Description = @mjBizAppsCommonOrganizations_ParentID_Description, @Email = @mjBizAppsCommonOrganizations_ParentID_Email, @Phone = @mjBizAppsCommonOrganizations_ParentID_Phone, @FoundedDate = @mjBizAppsCommonOrganizations_ParentID_FoundedDate, @TaxID = @mjBizAppsCommonOrganizations_ParentID_TaxID, @Status = @mjBizAppsCommonOrganizations_ParentID_Status

        FETCH NEXT FROM cascade_update_mjBizAppsCommonOrganizations_ParentID_cursor INTO @mjBizAppsCommonOrganizations_ParentIDID, @mjBizAppsCommonOrganizations_ParentID_Name, @mjBizAppsCommonOrganizations_ParentID_LegalName, @mjBizAppsCommonOrganizations_ParentID_OrganizationTypeID, @mjBizAppsCommonOrganizations_ParentID_ParentID, @mjBizAppsCommonOrganizations_ParentID_Website, @mjBizAppsCommonOrganizations_ParentID_LogoURL, @mjBizAppsCommonOrganizations_ParentID_Description, @mjBizAppsCommonOrganizations_ParentID_Email, @mjBizAppsCommonOrganizations_ParentID_Phone, @mjBizAppsCommonOrganizations_ParentID_FoundedDate, @mjBizAppsCommonOrganizations_ParentID_TaxID, @mjBizAppsCommonOrganizations_ParentID_Status
    END

    CLOSE cascade_update_mjBizAppsCommonOrganizations_ParentID_cursor
    DEALLOCATE cascade_update_mjBizAppsCommonOrganizations_ParentID_cursor
    
    -- Cascade update on Relationship using cursor to call spUpdateRelationship
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationIDID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_RelationshipTypeID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_FromPersonID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_FromOrganizationID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_ToPersonID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_ToOrganizationID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_Title nvarchar(255)
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_StartDate date
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_EndDate date
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_Status nvarchar(50)
    DECLARE @mjBizAppsCommonRelationships_FromOrganizationID_Notes nvarchar(MAX)
    DECLARE cascade_update_mjBizAppsCommonRelationships_FromOrganizationID_cursor CURSOR FOR
        SELECT [ID], [RelationshipTypeID], [FromPersonID], [FromOrganizationID], [ToPersonID], [ToOrganizationID], [Title], [StartDate], [EndDate], [Status], [Notes]
        FROM [${flyway:defaultSchema}].[Relationship]
        WHERE [FromOrganizationID] = @ID

    OPEN cascade_update_mjBizAppsCommonRelationships_FromOrganizationID_cursor
    FETCH NEXT FROM cascade_update_mjBizAppsCommonRelationships_FromOrganizationID_cursor INTO @mjBizAppsCommonRelationships_FromOrganizationIDID, @mjBizAppsCommonRelationships_FromOrganizationID_RelationshipTypeID, @mjBizAppsCommonRelationships_FromOrganizationID_FromPersonID, @mjBizAppsCommonRelationships_FromOrganizationID_FromOrganizationID, @mjBizAppsCommonRelationships_FromOrganizationID_ToPersonID, @mjBizAppsCommonRelationships_FromOrganizationID_ToOrganizationID, @mjBizAppsCommonRelationships_FromOrganizationID_Title, @mjBizAppsCommonRelationships_FromOrganizationID_StartDate, @mjBizAppsCommonRelationships_FromOrganizationID_EndDate, @mjBizAppsCommonRelationships_FromOrganizationID_Status, @mjBizAppsCommonRelationships_FromOrganizationID_Notes

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Set the FK field to NULL
        SET @mjBizAppsCommonRelationships_FromOrganizationID_FromOrganizationID = NULL

        -- Call the update SP for the related entity
        EXEC [${flyway:defaultSchema}].[spUpdateRelationship] @ID = @mjBizAppsCommonRelationships_FromOrganizationIDID, @RelationshipTypeID = @mjBizAppsCommonRelationships_FromOrganizationID_RelationshipTypeID, @FromPersonID = @mjBizAppsCommonRelationships_FromOrganizationID_FromPersonID, @FromOrganizationID_Clear = 1, @FromOrganizationID = @mjBizAppsCommonRelationships_FromOrganizationID_FromOrganizationID, @ToPersonID = @mjBizAppsCommonRelationships_FromOrganizationID_ToPersonID, @ToOrganizationID = @mjBizAppsCommonRelationships_FromOrganizationID_ToOrganizationID, @Title = @mjBizAppsCommonRelationships_FromOrganizationID_Title, @StartDate = @mjBizAppsCommonRelationships_FromOrganizationID_StartDate, @EndDate = @mjBizAppsCommonRelationships_FromOrganizationID_EndDate, @Status = @mjBizAppsCommonRelationships_FromOrganizationID_Status, @Notes = @mjBizAppsCommonRelationships_FromOrganizationID_Notes

        FETCH NEXT FROM cascade_update_mjBizAppsCommonRelationships_FromOrganizationID_cursor INTO @mjBizAppsCommonRelationships_FromOrganizationIDID, @mjBizAppsCommonRelationships_FromOrganizationID_RelationshipTypeID, @mjBizAppsCommonRelationships_FromOrganizationID_FromPersonID, @mjBizAppsCommonRelationships_FromOrganizationID_FromOrganizationID, @mjBizAppsCommonRelationships_FromOrganizationID_ToPersonID, @mjBizAppsCommonRelationships_FromOrganizationID_ToOrganizationID, @mjBizAppsCommonRelationships_FromOrganizationID_Title, @mjBizAppsCommonRelationships_FromOrganizationID_StartDate, @mjBizAppsCommonRelationships_FromOrganizationID_EndDate, @mjBizAppsCommonRelationships_FromOrganizationID_Status, @mjBizAppsCommonRelationships_FromOrganizationID_Notes
    END

    CLOSE cascade_update_mjBizAppsCommonRelationships_FromOrganizationID_cursor
    DEALLOCATE cascade_update_mjBizAppsCommonRelationships_FromOrganizationID_cursor
    
    -- Cascade update on Relationship using cursor to call spUpdateRelationship
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationIDID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_RelationshipTypeID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_FromPersonID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_FromOrganizationID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_ToPersonID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_ToOrganizationID uniqueidentifier
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_Title nvarchar(255)
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_StartDate date
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_EndDate date
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_Status nvarchar(50)
    DECLARE @mjBizAppsCommonRelationships_ToOrganizationID_Notes nvarchar(MAX)
    DECLARE cascade_update_mjBizAppsCommonRelationships_ToOrganizationID_cursor CURSOR FOR
        SELECT [ID], [RelationshipTypeID], [FromPersonID], [FromOrganizationID], [ToPersonID], [ToOrganizationID], [Title], [StartDate], [EndDate], [Status], [Notes]
        FROM [${flyway:defaultSchema}].[Relationship]
        WHERE [ToOrganizationID] = @ID

    OPEN cascade_update_mjBizAppsCommonRelationships_ToOrganizationID_cursor
    FETCH NEXT FROM cascade_update_mjBizAppsCommonRelationships_ToOrganizationID_cursor INTO @mjBizAppsCommonRelationships_ToOrganizationIDID, @mjBizAppsCommonRelationships_ToOrganizationID_RelationshipTypeID, @mjBizAppsCommonRelationships_ToOrganizationID_FromPersonID, @mjBizAppsCommonRelationships_ToOrganizationID_FromOrganizationID, @mjBizAppsCommonRelationships_ToOrganizationID_ToPersonID, @mjBizAppsCommonRelationships_ToOrganizationID_ToOrganizationID, @mjBizAppsCommonRelationships_ToOrganizationID_Title, @mjBizAppsCommonRelationships_ToOrganizationID_StartDate, @mjBizAppsCommonRelationships_ToOrganizationID_EndDate, @mjBizAppsCommonRelationships_ToOrganizationID_Status, @mjBizAppsCommonRelationships_ToOrganizationID_Notes

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Set the FK field to NULL
        SET @mjBizAppsCommonRelationships_ToOrganizationID_ToOrganizationID = NULL

        -- Call the update SP for the related entity
        EXEC [${flyway:defaultSchema}].[spUpdateRelationship] @ID = @mjBizAppsCommonRelationships_ToOrganizationIDID, @RelationshipTypeID = @mjBizAppsCommonRelationships_ToOrganizationID_RelationshipTypeID, @FromPersonID = @mjBizAppsCommonRelationships_ToOrganizationID_FromPersonID, @FromOrganizationID = @mjBizAppsCommonRelationships_ToOrganizationID_FromOrganizationID, @ToPersonID = @mjBizAppsCommonRelationships_ToOrganizationID_ToPersonID, @ToOrganizationID_Clear = 1, @ToOrganizationID = @mjBizAppsCommonRelationships_ToOrganizationID_ToOrganizationID, @Title = @mjBizAppsCommonRelationships_ToOrganizationID_Title, @StartDate = @mjBizAppsCommonRelationships_ToOrganizationID_StartDate, @EndDate = @mjBizAppsCommonRelationships_ToOrganizationID_EndDate, @Status = @mjBizAppsCommonRelationships_ToOrganizationID_Status, @Notes = @mjBizAppsCommonRelationships_ToOrganizationID_Notes

        FETCH NEXT FROM cascade_update_mjBizAppsCommonRelationships_ToOrganizationID_cursor INTO @mjBizAppsCommonRelationships_ToOrganizationIDID, @mjBizAppsCommonRelationships_ToOrganizationID_RelationshipTypeID, @mjBizAppsCommonRelationships_ToOrganizationID_FromPersonID, @mjBizAppsCommonRelationships_ToOrganizationID_FromOrganizationID, @mjBizAppsCommonRelationships_ToOrganizationID_ToPersonID, @mjBizAppsCommonRelationships_ToOrganizationID_ToOrganizationID, @mjBizAppsCommonRelationships_ToOrganizationID_Title, @mjBizAppsCommonRelationships_ToOrganizationID_StartDate, @mjBizAppsCommonRelationships_ToOrganizationID_EndDate, @mjBizAppsCommonRelationships_ToOrganizationID_Status, @mjBizAppsCommonRelationships_ToOrganizationID_Notes
    END

    CLOSE cascade_update_mjBizAppsCommonRelationships_ToOrganizationID_cursor
    DEALLOCATE cascade_update_mjBizAppsCommonRelationships_ToOrganizationID_cursor
    

    DELETE FROM
        [${flyway:defaultSchema}].[Organization]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteOrganization] TO [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Common: Organizations */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteOrganization] TO [cdp_Integration];

/* SQL text to delete unneeded entity fields (3 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='32C45078-D33B-4760-9BE5-0DF7F483F591,F2FC2E85-B210-43A9-8565-290AD9D0C6E7,709CA9DA-B124-4155-BE39-E857EF672D82';

/* SQL text to update existing entity fields from schema (3 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='32C45078-D33B-4760-9BE5-0DF7F483F591,F2FC2E85-B210-43A9-8565-290AD9D0C6E7,709CA9DA-B124-4155-BE39-E857EF672D82';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

