-- =====================================================================
-- v5.29 Metadata Sync
-- =====================================================================
--
-- Replays the metadata-folder state into __mj.Entity, __mj.EntityField,
-- __mj.SchemaInfo, and BAC's seed-data tables (Address Types, Contact
-- Types, Organization Types, Relationship Types).
--
-- Generated by `mj sync push` from BAC's metadata/ directory against
-- a freshly-migrated DB. Mirrors BCSaaS's
-- V202602251500__v1.0.x_Metadata_Sync.sql pattern.
--
-- =====================================================================

-- SQL Logging Session
-- Session ID: 13a9308d-41cd-4ee8-b7b7-10b95a0b35c7
-- Started: 2026-05-14T07:27:11.937Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Schema Info (core SP call only)
DECLARE @SchemaName_c8e046e9 NVARCHAR(50),
@EntityIDMin_c8e046e9 INT,
@EntityIDMax_c8e046e9 INT,
@Comments_c8e046e9 NVARCHAR(MAX),
@Description_c8e046e9 NVARCHAR(MAX),
@EntityNamePrefix_c8e046e9 NVARCHAR(25),
@EntityNameSuffix_c8e046e9 NVARCHAR(25),
@ID_c8e046e9 UNIQUEIDENTIFIER
SET
  @SchemaName_c8e046e9 = N'__mj_BizAppsCommon'
SET
  @EntityIDMin_c8e046e9 = 1
SET
  @EntityIDMax_c8e046e9 = 1000000
SET
  @Description_c8e046e9 = N'MemberJunction: Common Business App Data'
SET
  @EntityNamePrefix_c8e046e9 = N'MJ_BizApps_Common: '
SET
  @ID_c8e046e9 = '0A9F0FDD-CD4D-4892-BA45-85722B982032' EXEC [__mj].spUpdateSchemaInfo @SchemaName = @SchemaName_c8e046e9,
  @EntityIDMin = @EntityIDMin_c8e046e9,
  @EntityIDMax = @EntityIDMax_c8e046e9,
  @Comments = @Comments_c8e046e9,
  @Comments_Clear = 1,
  @Description = @Description_c8e046e9,
  @EntityNamePrefix = @EntityNamePrefix_c8e046e9,
  @EntityNameSuffix = @EntityNameSuffix_c8e046e9,
  @EntityNameSuffix_Clear = 1,
  @ID = @ID_c8e046e9;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_2d46e8b4 UNIQUEIDENTIFIER,
@Name_2d46e8b4 NVARCHAR(100),
@Description_2d46e8b4 NVARCHAR(MAX),
@IconClass_2d46e8b4 NVARCHAR(100),
@DefaultRank_2d46e8b4 INT,
@IsActive_2d46e8b4 BIT
SET
  @ID_2d46e8b4 = '49183F91-F101-48F6-B2BE-AEC550B2CA0E'
SET
  @Name_2d46e8b4 = N'Home'
SET
  @Description_2d46e8b4 = N'Primary residential address'
SET
  @IconClass_2d46e8b4 = N'fa-solid fa-house'
SET
  @DefaultRank_2d46e8b4 = 10
SET
  @IsActive_2d46e8b4 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_2d46e8b4,
  @Name = @Name_2d46e8b4,
  @Description = @Description_2d46e8b4,
  @IconClass = @IconClass_2d46e8b4,
  @DefaultRank = @DefaultRank_2d46e8b4,
  @IsActive = @IsActive_2d46e8b4;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_55359ec1 UNIQUEIDENTIFIER,
@Name_55359ec1 NVARCHAR(100),
@Description_55359ec1 NVARCHAR(MAX),
@IconClass_55359ec1 NVARCHAR(100),
@DefaultRank_55359ec1 INT,
@IsActive_55359ec1 BIT
SET
  @ID_55359ec1 = '0EFFA181-179B-4B68-ACC8-A57D55C4D73D'
SET
  @Name_55359ec1 = N'Work'
SET
  @Description_55359ec1 = N'Business or office address'
SET
  @IconClass_55359ec1 = N'fa-solid fa-building'
SET
  @DefaultRank_55359ec1 = 20
SET
  @IsActive_55359ec1 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_55359ec1,
  @Name = @Name_55359ec1,
  @Description = @Description_55359ec1,
  @IconClass = @IconClass_55359ec1,
  @DefaultRank = @DefaultRank_55359ec1,
  @IsActive = @IsActive_55359ec1;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_d5546c1b UNIQUEIDENTIFIER,
@Name_d5546c1b NVARCHAR(100),
@Description_d5546c1b NVARCHAR(MAX),
@IconClass_d5546c1b NVARCHAR(100),
@DefaultRank_d5546c1b INT,
@IsActive_d5546c1b BIT
SET
  @ID_d5546c1b = '964C05C1-C947-467B-97B9-A7495BDDB7B0'
SET
  @Name_d5546c1b = N'Mailing'
SET
  @Description_d5546c1b = N'Preferred address for receiving mail and correspondence'
SET
  @IconClass_d5546c1b = N'fa-solid fa-mailbox'
SET
  @DefaultRank_d5546c1b = 30
SET
  @IsActive_d5546c1b = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_d5546c1b,
  @Name = @Name_d5546c1b,
  @Description = @Description_d5546c1b,
  @IconClass = @IconClass_d5546c1b,
  @DefaultRank = @DefaultRank_d5546c1b,
  @IsActive = @IsActive_d5546c1b;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_faf47a9d UNIQUEIDENTIFIER,
@Name_faf47a9d NVARCHAR(100),
@Description_faf47a9d NVARCHAR(MAX),
@IconClass_faf47a9d NVARCHAR(100),
@DefaultRank_faf47a9d INT,
@IsActive_faf47a9d BIT
SET
  @ID_faf47a9d = 'E2C28836-F2C2-4590-A519-BCAB0E864974'
SET
  @Name_faf47a9d = N'Billing'
SET
  @Description_faf47a9d = N'Address used for invoices and financial correspondence'
SET
  @IconClass_faf47a9d = N'fa-solid fa-file-invoice-dollar'
SET
  @DefaultRank_faf47a9d = 40
SET
  @IsActive_faf47a9d = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_faf47a9d,
  @Name = @Name_faf47a9d,
  @Description = @Description_faf47a9d,
  @IconClass = @IconClass_faf47a9d,
  @DefaultRank = @DefaultRank_faf47a9d,
  @IsActive = @IsActive_faf47a9d;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_f325a028 UNIQUEIDENTIFIER,
@Name_f325a028 NVARCHAR(100),
@Description_f325a028 NVARCHAR(MAX),
@IconClass_f325a028 NVARCHAR(100),
@DefaultRank_f325a028 INT,
@IsActive_f325a028 BIT
SET
  @ID_f325a028 = 'C466C5B0-35AE-46D6-B95E-88823E2E7EE5'
SET
  @Name_f325a028 = N'Shipping'
SET
  @Description_f325a028 = N'Address for physical deliveries'
SET
  @IconClass_f325a028 = N'fa-solid fa-truck'
SET
  @DefaultRank_f325a028 = 50
SET
  @IsActive_f325a028 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_f325a028,
  @Name = @Name_f325a028,
  @Description = @Description_f325a028,
  @IconClass = @IconClass_f325a028,
  @DefaultRank = @DefaultRank_f325a028,
  @IsActive = @IsActive_f325a028;

GO

-- Save MJ_BizApps_Common: Address Types (core SP call only)
DECLARE @ID_52c6bbd7 UNIQUEIDENTIFIER,
@Name_52c6bbd7 NVARCHAR(100),
@Description_52c6bbd7 NVARCHAR(MAX),
@IconClass_52c6bbd7 NVARCHAR(100),
@DefaultRank_52c6bbd7 INT,
@IsActive_52c6bbd7 BIT
SET
  @ID_52c6bbd7 = '4D1E1A1A-1CD1-4069-BF1E-198F838A0DFF'
SET
  @Name_52c6bbd7 = N'Legal'
SET
  @Description_52c6bbd7 = N'Registered legal or statutory address'
SET
  @IconClass_52c6bbd7 = N'fa-solid fa-scale-balanced'
SET
  @DefaultRank_52c6bbd7 = 60
SET
  @IsActive_52c6bbd7 = 1
EXEC [__mj_BizAppsCommon].spCreateAddressType @ID = @ID_52c6bbd7,
  @Name = @Name_52c6bbd7,
  @Description = @Description_52c6bbd7,
  @IconClass = @IconClass_52c6bbd7,
  @DefaultRank = @DefaultRank_52c6bbd7,
  @IsActive = @IsActive_52c6bbd7;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_4d41a7c2 UNIQUEIDENTIFIER,
@Name_4d41a7c2 NVARCHAR(100),
@Description_4d41a7c2 NVARCHAR(MAX),
@IconClass_4d41a7c2 NVARCHAR(100),
@DisplayRank_4d41a7c2 INT,
@IsActive_4d41a7c2 BIT
SET
  @ID_4d41a7c2 = 'FB4D3737-8479-44E5-AF91-2DB63311D293'
SET
  @Name_4d41a7c2 = N'Email'
SET
  @Description_4d41a7c2 = N'Email address'
SET
  @IconClass_4d41a7c2 = N'fa-solid fa-envelope'
SET
  @DisplayRank_4d41a7c2 = 10
SET
  @IsActive_4d41a7c2 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_4d41a7c2,
  @Name = @Name_4d41a7c2,
  @Description = @Description_4d41a7c2,
  @IconClass = @IconClass_4d41a7c2,
  @DisplayRank = @DisplayRank_4d41a7c2,
  @IsActive = @IsActive_4d41a7c2;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_2b60e8bf UNIQUEIDENTIFIER,
@Name_2b60e8bf NVARCHAR(100),
@Description_2b60e8bf NVARCHAR(MAX),
@IconClass_2b60e8bf NVARCHAR(100),
@DisplayRank_2b60e8bf INT,
@IsActive_2b60e8bf BIT
SET
  @ID_2b60e8bf = '96421246-0F8F-4CDB-A5C5-BA6B190C1AFE'
SET
  @Name_2b60e8bf = N'Mobile Phone'
SET
  @Description_2b60e8bf = N'Mobile or cell phone number'
SET
  @IconClass_2b60e8bf = N'fa-solid fa-mobile-screen'
SET
  @DisplayRank_2b60e8bf = 20
SET
  @IsActive_2b60e8bf = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_2b60e8bf,
  @Name = @Name_2b60e8bf,
  @Description = @Description_2b60e8bf,
  @IconClass = @IconClass_2b60e8bf,
  @DisplayRank = @DisplayRank_2b60e8bf,
  @IsActive = @IsActive_2b60e8bf;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_9b847212 UNIQUEIDENTIFIER,
@Name_9b847212 NVARCHAR(100),
@Description_9b847212 NVARCHAR(MAX),
@IconClass_9b847212 NVARCHAR(100),
@DisplayRank_9b847212 INT,
@IsActive_9b847212 BIT
SET
  @ID_9b847212 = 'BCDA98AC-06A4-40FC-A1CC-E44BB783FBC9'
SET
  @Name_9b847212 = N'Work Phone'
SET
  @Description_9b847212 = N'Business or office phone number'
SET
  @IconClass_9b847212 = N'fa-solid fa-phone-office'
SET
  @DisplayRank_9b847212 = 30
SET
  @IsActive_9b847212 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_9b847212,
  @Name = @Name_9b847212,
  @Description = @Description_9b847212,
  @IconClass = @IconClass_9b847212,
  @DisplayRank = @DisplayRank_9b847212,
  @IsActive = @IsActive_9b847212;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_b735d393 UNIQUEIDENTIFIER,
@Name_b735d393 NVARCHAR(100),
@Description_b735d393 NVARCHAR(MAX),
@IconClass_b735d393 NVARCHAR(100),
@DisplayRank_b735d393 INT,
@IsActive_b735d393 BIT
SET
  @ID_b735d393 = 'C3BA9432-8D05-4AFE-BF6D-61F976A466E6'
SET
  @Name_b735d393 = N'Home Phone'
SET
  @Description_b735d393 = N'Residential phone number'
SET
  @IconClass_b735d393 = N'fa-solid fa-phone'
SET
  @DisplayRank_b735d393 = 40
SET
  @IsActive_b735d393 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_b735d393,
  @Name = @Name_b735d393,
  @Description = @Description_b735d393,
  @IconClass = @IconClass_b735d393,
  @DisplayRank = @DisplayRank_b735d393,
  @IsActive = @IsActive_b735d393;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_3cdf7ff9 UNIQUEIDENTIFIER,
@Name_3cdf7ff9 NVARCHAR(100),
@Description_3cdf7ff9 NVARCHAR(MAX),
@IconClass_3cdf7ff9 NVARCHAR(100),
@DisplayRank_3cdf7ff9 INT,
@IsActive_3cdf7ff9 BIT
SET
  @ID_3cdf7ff9 = 'FDBFF502-CE06-456B-BCC3-8A2C23D16D45'
SET
  @Name_3cdf7ff9 = N'LinkedIn'
SET
  @Description_3cdf7ff9 = N'LinkedIn profile URL'
SET
  @IconClass_3cdf7ff9 = N'fa-brands fa-linkedin'
SET
  @DisplayRank_3cdf7ff9 = 50
SET
  @IsActive_3cdf7ff9 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_3cdf7ff9,
  @Name = @Name_3cdf7ff9,
  @Description = @Description_3cdf7ff9,
  @IconClass = @IconClass_3cdf7ff9,
  @DisplayRank = @DisplayRank_3cdf7ff9,
  @IsActive = @IsActive_3cdf7ff9;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_ed82d97b UNIQUEIDENTIFIER,
@Name_ed82d97b NVARCHAR(100),
@Description_ed82d97b NVARCHAR(MAX),
@IconClass_ed82d97b NVARCHAR(100),
@DisplayRank_ed82d97b INT,
@IsActive_ed82d97b BIT
SET
  @ID_ed82d97b = '02A126F9-ED1B-4BBF-8479-8B10CC916150'
SET
  @Name_ed82d97b = N'Twitter / X'
SET
  @Description_ed82d97b = N'Twitter / X profile URL or handle'
SET
  @IconClass_ed82d97b = N'fa-brands fa-x-twitter'
SET
  @DisplayRank_ed82d97b = 60
SET
  @IsActive_ed82d97b = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_ed82d97b,
  @Name = @Name_ed82d97b,
  @Description = @Description_ed82d97b,
  @IconClass = @IconClass_ed82d97b,
  @DisplayRank = @DisplayRank_ed82d97b,
  @IsActive = @IsActive_ed82d97b;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_44e6946b UNIQUEIDENTIFIER,
@Name_44e6946b NVARCHAR(100),
@Description_44e6946b NVARCHAR(MAX),
@IconClass_44e6946b NVARCHAR(100),
@DisplayRank_44e6946b INT,
@IsActive_44e6946b BIT
SET
  @ID_44e6946b = 'F2DBF3EA-7ACF-4725-92D3-AB630B613293'
SET
  @Name_44e6946b = N'Website'
SET
  @Description_44e6946b = N'Personal or professional website URL'
SET
  @IconClass_44e6946b = N'fa-solid fa-globe'
SET
  @DisplayRank_44e6946b = 70
SET
  @IsActive_44e6946b = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_44e6946b,
  @Name = @Name_44e6946b,
  @Description = @Description_44e6946b,
  @IconClass = @IconClass_44e6946b,
  @DisplayRank = @DisplayRank_44e6946b,
  @IsActive = @IsActive_44e6946b;

GO

-- Save MJ_BizApps_Common: Contact Types (core SP call only)
DECLARE @ID_e9e1d773 UNIQUEIDENTIFIER,
@Name_e9e1d773 NVARCHAR(100),
@Description_e9e1d773 NVARCHAR(MAX),
@IconClass_e9e1d773 NVARCHAR(100),
@DisplayRank_e9e1d773 INT,
@IsActive_e9e1d773 BIT
SET
  @ID_e9e1d773 = 'A33D19DB-27FD-400C-A9C9-F3D3C4A12E8F'
SET
  @Name_e9e1d773 = N'Fax'
SET
  @Description_e9e1d773 = N'Fax number'
SET
  @IconClass_e9e1d773 = N'fa-solid fa-fax'
SET
  @DisplayRank_e9e1d773 = 80
SET
  @IsActive_e9e1d773 = 1
EXEC [__mj_BizAppsCommon].spCreateContactType @ID = @ID_e9e1d773,
  @Name = @Name_e9e1d773,
  @Description = @Description_e9e1d773,
  @IconClass = @IconClass_e9e1d773,
  @DisplayRank = @DisplayRank_e9e1d773,
  @IsActive = @IsActive_e9e1d773;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_35bc6efb UNIQUEIDENTIFIER,
@Name_35bc6efb NVARCHAR(100),
@Description_35bc6efb NVARCHAR(MAX),
@IconClass_35bc6efb NVARCHAR(100),
@DisplayRank_35bc6efb INT,
@IsActive_35bc6efb BIT
SET
  @ID_35bc6efb = 'A8DB7343-DCC9-44D1-B99F-9E21024C3C2E'
SET
  @Name_35bc6efb = N'Corporation'
SET
  @Description_35bc6efb = N'Incorporated business entity (C-Corp, S-Corp)'
SET
  @IconClass_35bc6efb = N'fa-solid fa-building'
SET
  @DisplayRank_35bc6efb = 10
SET
  @IsActive_35bc6efb = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_35bc6efb,
  @Name = @Name_35bc6efb,
  @Description = @Description_35bc6efb,
  @IconClass = @IconClass_35bc6efb,
  @DisplayRank = @DisplayRank_35bc6efb,
  @IsActive = @IsActive_35bc6efb;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_25bb4b80 UNIQUEIDENTIFIER,
@Name_25bb4b80 NVARCHAR(100),
@Description_25bb4b80 NVARCHAR(MAX),
@IconClass_25bb4b80 NVARCHAR(100),
@DisplayRank_25bb4b80 INT,
@IsActive_25bb4b80 BIT
SET
  @ID_25bb4b80 = '288B017D-60A4-48A7-A845-EF30B99BDBEF'
SET
  @Name_25bb4b80 = N'LLC'
SET
  @Description_25bb4b80 = N'Limited liability company'
SET
  @IconClass_25bb4b80 = N'fa-solid fa-briefcase'
SET
  @DisplayRank_25bb4b80 = 20
SET
  @IsActive_25bb4b80 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_25bb4b80,
  @Name = @Name_25bb4b80,
  @Description = @Description_25bb4b80,
  @IconClass = @IconClass_25bb4b80,
  @DisplayRank = @DisplayRank_25bb4b80,
  @IsActive = @IsActive_25bb4b80;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_3da30fd8 UNIQUEIDENTIFIER,
@Name_3da30fd8 NVARCHAR(100),
@Description_3da30fd8 NVARCHAR(MAX),
@IconClass_3da30fd8 NVARCHAR(100),
@DisplayRank_3da30fd8 INT,
@IsActive_3da30fd8 BIT
SET
  @ID_3da30fd8 = 'BAAA53F4-A8AA-4EAA-B04E-1BA6F964B341'
SET
  @Name_3da30fd8 = N'Non-Profit'
SET
  @Description_3da30fd8 = N'Tax-exempt non-profit organization (501(c)(3), etc.)'
SET
  @IconClass_3da30fd8 = N'fa-solid fa-hand-holding-heart'
SET
  @DisplayRank_3da30fd8 = 30
SET
  @IsActive_3da30fd8 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_3da30fd8,
  @Name = @Name_3da30fd8,
  @Description = @Description_3da30fd8,
  @IconClass = @IconClass_3da30fd8,
  @DisplayRank = @DisplayRank_3da30fd8,
  @IsActive = @IsActive_3da30fd8;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_e2cb289a UNIQUEIDENTIFIER,
@Name_e2cb289a NVARCHAR(100),
@Description_e2cb289a NVARCHAR(MAX),
@IconClass_e2cb289a NVARCHAR(100),
@DisplayRank_e2cb289a INT,
@IsActive_e2cb289a BIT
SET
  @ID_e2cb289a = '1E61230B-0F48-458A-811B-66C9CF6B688E'
SET
  @Name_e2cb289a = N'Government'
SET
  @Description_e2cb289a = N'Government agency or department'
SET
  @IconClass_e2cb289a = N'fa-solid fa-landmark'
SET
  @DisplayRank_e2cb289a = 40
SET
  @IsActive_e2cb289a = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_e2cb289a,
  @Name = @Name_e2cb289a,
  @Description = @Description_e2cb289a,
  @IconClass = @IconClass_e2cb289a,
  @DisplayRank = @DisplayRank_e2cb289a,
  @IsActive = @IsActive_e2cb289a;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_6fb36472 UNIQUEIDENTIFIER,
@Name_6fb36472 NVARCHAR(100),
@Description_6fb36472 NVARCHAR(MAX),
@IconClass_6fb36472 NVARCHAR(100),
@DisplayRank_6fb36472 INT,
@IsActive_6fb36472 BIT
SET
  @ID_6fb36472 = '5CAB6265-CB87-4269-A321-2473160BD625'
SET
  @Name_6fb36472 = N'Partnership'
SET
  @Description_6fb36472 = N'General or limited partnership'
SET
  @IconClass_6fb36472 = N'fa-solid fa-handshake'
SET
  @DisplayRank_6fb36472 = 50
SET
  @IsActive_6fb36472 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_6fb36472,
  @Name = @Name_6fb36472,
  @Description = @Description_6fb36472,
  @IconClass = @IconClass_6fb36472,
  @DisplayRank = @DisplayRank_6fb36472,
  @IsActive = @IsActive_6fb36472;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_31f38e89 UNIQUEIDENTIFIER,
@Name_31f38e89 NVARCHAR(100),
@Description_31f38e89 NVARCHAR(MAX),
@IconClass_31f38e89 NVARCHAR(100),
@DisplayRank_31f38e89 INT,
@IsActive_31f38e89 BIT
SET
  @ID_31f38e89 = '042C63AF-93EB-4BB4-A469-F3C209F8936E'
SET
  @Name_31f38e89 = N'Sole Proprietorship'
SET
  @Description_31f38e89 = N'Unincorporated business owned by a single individual'
SET
  @IconClass_31f38e89 = N'fa-solid fa-user-tie'
SET
  @DisplayRank_31f38e89 = 60
SET
  @IsActive_31f38e89 = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_31f38e89,
  @Name = @Name_31f38e89,
  @Description = @Description_31f38e89,
  @IconClass = @IconClass_31f38e89,
  @DisplayRank = @DisplayRank_31f38e89,
  @IsActive = @IsActive_31f38e89;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_49ab7b5d UNIQUEIDENTIFIER,
@Name_49ab7b5d NVARCHAR(100),
@Description_49ab7b5d NVARCHAR(MAX),
@IconClass_49ab7b5d NVARCHAR(100),
@DisplayRank_49ab7b5d INT,
@IsActive_49ab7b5d BIT
SET
  @ID_49ab7b5d = '7D6D1763-3198-42B2-A23C-F0FF76DAD8D2'
SET
  @Name_49ab7b5d = N'Association'
SET
  @Description_49ab7b5d = N'Professional or trade association'
SET
  @IconClass_49ab7b5d = N'fa-solid fa-people-group'
SET
  @DisplayRank_49ab7b5d = 70
SET
  @IsActive_49ab7b5d = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_49ab7b5d,
  @Name = @Name_49ab7b5d,
  @Description = @Description_49ab7b5d,
  @IconClass = @IconClass_49ab7b5d,
  @DisplayRank = @DisplayRank_49ab7b5d,
  @IsActive = @IsActive_49ab7b5d;

GO

-- Save MJ_BizApps_Common: Organization Types (core SP call only)
DECLARE @ID_96966abf UNIQUEIDENTIFIER,
@Name_96966abf NVARCHAR(100),
@Description_96966abf NVARCHAR(MAX),
@IconClass_96966abf NVARCHAR(100),
@DisplayRank_96966abf INT,
@IsActive_96966abf BIT
SET
  @ID_96966abf = '4BE0D87B-EFCB-447D-9410-FEF8EED23BC8'
SET
  @Name_96966abf = N'Educational Institution'
SET
  @Description_96966abf = N'School, college, university, or training organization'
SET
  @IconClass_96966abf = N'fa-solid fa-graduation-cap'
SET
  @DisplayRank_96966abf = 80
SET
  @IsActive_96966abf = 1
EXEC [__mj_BizAppsCommon].spCreateOrganizationType @ID = @ID_96966abf,
  @Name = @Name_96966abf,
  @Description = @Description_96966abf,
  @IconClass = @IconClass_96966abf,
  @DisplayRank = @DisplayRank_96966abf,
  @IsActive = @IsActive_96966abf;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_0e687057 UNIQUEIDENTIFIER,
@Name_0e687057 NVARCHAR(100),
@Description_0e687057 NVARCHAR(MAX),
@Category_0e687057 NVARCHAR(50),
@IsDirectional_0e687057 BIT,
@ForwardLabel_0e687057 NVARCHAR(100),
@ReverseLabel_0e687057 NVARCHAR(100),
@IsActive_0e687057 BIT
SET
  @ID_0e687057 = 'FEB33819-FC85-4309-B1EC-A54EEA91DACF'
SET
  @Name_0e687057 = N'Spouse'
SET
  @Description_0e687057 = N'Married or domestic partner relationship'
SET
  @Category_0e687057 = N'PersonToPerson'
SET
  @IsDirectional_0e687057 = 0
SET
  @ForwardLabel_0e687057 = N'is spouse of'
SET
  @ReverseLabel_0e687057 = N'is spouse of'
SET
  @IsActive_0e687057 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_0e687057,
  @Name = @Name_0e687057,
  @Description = @Description_0e687057,
  @Category = @Category_0e687057,
  @IsDirectional = @IsDirectional_0e687057,
  @ForwardLabel = @ForwardLabel_0e687057,
  @ReverseLabel = @ReverseLabel_0e687057,
  @IsActive = @IsActive_0e687057;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_a36c43e1 UNIQUEIDENTIFIER,
@Name_a36c43e1 NVARCHAR(100),
@Description_a36c43e1 NVARCHAR(MAX),
@Category_a36c43e1 NVARCHAR(50),
@IsDirectional_a36c43e1 BIT,
@ForwardLabel_a36c43e1 NVARCHAR(100),
@ReverseLabel_a36c43e1 NVARCHAR(100),
@IsActive_a36c43e1 BIT
SET
  @ID_a36c43e1 = '431DBAF3-AC1D-47E6-B91E-264E8C76FC57'
SET
  @Name_a36c43e1 = N'Parent / Child'
SET
  @Description_a36c43e1 = N'Parent-child family relationship'
SET
  @Category_a36c43e1 = N'PersonToPerson'
SET
  @IsDirectional_a36c43e1 = 1
SET
  @ForwardLabel_a36c43e1 = N'is parent of'
SET
  @ReverseLabel_a36c43e1 = N'is child of'
SET
  @IsActive_a36c43e1 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_a36c43e1,
  @Name = @Name_a36c43e1,
  @Description = @Description_a36c43e1,
  @Category = @Category_a36c43e1,
  @IsDirectional = @IsDirectional_a36c43e1,
  @ForwardLabel = @ForwardLabel_a36c43e1,
  @ReverseLabel = @ReverseLabel_a36c43e1,
  @IsActive = @IsActive_a36c43e1;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_3855082d UNIQUEIDENTIFIER,
@Name_3855082d NVARCHAR(100),
@Description_3855082d NVARCHAR(MAX),
@Category_3855082d NVARCHAR(50),
@IsDirectional_3855082d BIT,
@ForwardLabel_3855082d NVARCHAR(100),
@ReverseLabel_3855082d NVARCHAR(100),
@IsActive_3855082d BIT
SET
  @ID_3855082d = 'D471B007-0717-493E-AC0D-2F102A32BCC2'
SET
  @Name_3855082d = N'Sibling'
SET
  @Description_3855082d = N'Brother or sister relationship'
SET
  @Category_3855082d = N'PersonToPerson'
SET
  @IsDirectional_3855082d = 0
SET
  @ForwardLabel_3855082d = N'is sibling of'
SET
  @ReverseLabel_3855082d = N'is sibling of'
SET
  @IsActive_3855082d = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_3855082d,
  @Name = @Name_3855082d,
  @Description = @Description_3855082d,
  @Category = @Category_3855082d,
  @IsDirectional = @IsDirectional_3855082d,
  @ForwardLabel = @ForwardLabel_3855082d,
  @ReverseLabel = @ReverseLabel_3855082d,
  @IsActive = @IsActive_3855082d;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_9aa2155b UNIQUEIDENTIFIER,
@Name_9aa2155b NVARCHAR(100),
@Description_9aa2155b NVARCHAR(MAX),
@Category_9aa2155b NVARCHAR(50),
@IsDirectional_9aa2155b BIT,
@ForwardLabel_9aa2155b NVARCHAR(100),
@ReverseLabel_9aa2155b NVARCHAR(100),
@IsActive_9aa2155b BIT
SET
  @ID_9aa2155b = '6A17A929-8B23-4D73-9DF9-A368E7C1C1B9'
SET
  @Name_9aa2155b = N'Friend'
SET
  @Description_9aa2155b = N'Personal friendship'
SET
  @Category_9aa2155b = N'PersonToPerson'
SET
  @IsDirectional_9aa2155b = 0
SET
  @ForwardLabel_9aa2155b = N'is friend of'
SET
  @ReverseLabel_9aa2155b = N'is friend of'
SET
  @IsActive_9aa2155b = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_9aa2155b,
  @Name = @Name_9aa2155b,
  @Description = @Description_9aa2155b,
  @Category = @Category_9aa2155b,
  @IsDirectional = @IsDirectional_9aa2155b,
  @ForwardLabel = @ForwardLabel_9aa2155b,
  @ReverseLabel = @ReverseLabel_9aa2155b,
  @IsActive = @IsActive_9aa2155b;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_91f9e188 UNIQUEIDENTIFIER,
@Name_91f9e188 NVARCHAR(100),
@Description_91f9e188 NVARCHAR(MAX),
@Category_91f9e188 NVARCHAR(50),
@IsDirectional_91f9e188 BIT,
@ForwardLabel_91f9e188 NVARCHAR(100),
@ReverseLabel_91f9e188 NVARCHAR(100),
@IsActive_91f9e188 BIT
SET
  @ID_91f9e188 = '27CFD031-5663-4000-A7AB-8AC87DB88C1D'
SET
  @Name_91f9e188 = N'Employee'
SET
  @Description_91f9e188 = N'Employment relationship between a person and an organization'
SET
  @Category_91f9e188 = N'PersonToOrganization'
SET
  @IsDirectional_91f9e188 = 1
SET
  @ForwardLabel_91f9e188 = N'is employee of'
SET
  @ReverseLabel_91f9e188 = N'employs'
SET
  @IsActive_91f9e188 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_91f9e188,
  @Name = @Name_91f9e188,
  @Description = @Description_91f9e188,
  @Category = @Category_91f9e188,
  @IsDirectional = @IsDirectional_91f9e188,
  @ForwardLabel = @ForwardLabel_91f9e188,
  @ReverseLabel = @ReverseLabel_91f9e188,
  @IsActive = @IsActive_91f9e188;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_de37b617 UNIQUEIDENTIFIER,
@Name_de37b617 NVARCHAR(100),
@Description_de37b617 NVARCHAR(MAX),
@Category_de37b617 NVARCHAR(50),
@IsDirectional_de37b617 BIT,
@ForwardLabel_de37b617 NVARCHAR(100),
@ReverseLabel_de37b617 NVARCHAR(100),
@IsActive_de37b617 BIT
SET
  @ID_de37b617 = '2FE33D05-5FD0-4076-8EF2-A30A640651B4'
SET
  @Name_de37b617 = N'Board Member'
SET
  @Description_de37b617 = N'Person serves on the board of directors of an organization'
SET
  @Category_de37b617 = N'PersonToOrganization'
SET
  @IsDirectional_de37b617 = 1
SET
  @ForwardLabel_de37b617 = N'is board member of'
SET
  @ReverseLabel_de37b617 = N'has board member'
SET
  @IsActive_de37b617 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_de37b617,
  @Name = @Name_de37b617,
  @Description = @Description_de37b617,
  @Category = @Category_de37b617,
  @IsDirectional = @IsDirectional_de37b617,
  @ForwardLabel = @ForwardLabel_de37b617,
  @ReverseLabel = @ReverseLabel_de37b617,
  @IsActive = @IsActive_de37b617;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_c9ee50bc UNIQUEIDENTIFIER,
@Name_c9ee50bc NVARCHAR(100),
@Description_c9ee50bc NVARCHAR(MAX),
@Category_c9ee50bc NVARCHAR(50),
@IsDirectional_c9ee50bc BIT,
@ForwardLabel_c9ee50bc NVARCHAR(100),
@ReverseLabel_c9ee50bc NVARCHAR(100),
@IsActive_c9ee50bc BIT
SET
  @ID_c9ee50bc = '5B8C871C-025B-410A-9D44-4D30C76534C7'
SET
  @Name_c9ee50bc = N'Member'
SET
  @Description_c9ee50bc = N'Person is a member of an organization or association'
SET
  @Category_c9ee50bc = N'PersonToOrganization'
SET
  @IsDirectional_c9ee50bc = 1
SET
  @ForwardLabel_c9ee50bc = N'is member of'
SET
  @ReverseLabel_c9ee50bc = N'has member'
SET
  @IsActive_c9ee50bc = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_c9ee50bc,
  @Name = @Name_c9ee50bc,
  @Description = @Description_c9ee50bc,
  @Category = @Category_c9ee50bc,
  @IsDirectional = @IsDirectional_c9ee50bc,
  @ForwardLabel = @ForwardLabel_c9ee50bc,
  @ReverseLabel = @ReverseLabel_c9ee50bc,
  @IsActive = @IsActive_c9ee50bc;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_c677c49e UNIQUEIDENTIFIER,
@Name_c677c49e NVARCHAR(100),
@Description_c677c49e NVARCHAR(MAX),
@Category_c677c49e NVARCHAR(50),
@IsDirectional_c677c49e BIT,
@ForwardLabel_c677c49e NVARCHAR(100),
@ReverseLabel_c677c49e NVARCHAR(100),
@IsActive_c677c49e BIT
SET
  @ID_c677c49e = 'DF72DDBB-A829-41AC-8698-01FCCD21FEEF'
SET
  @Name_c677c49e = N'Volunteer'
SET
  @Description_c677c49e = N'Person volunteers for an organization'
SET
  @Category_c677c49e = N'PersonToOrganization'
SET
  @IsDirectional_c677c49e = 1
SET
  @ForwardLabel_c677c49e = N'volunteers for'
SET
  @ReverseLabel_c677c49e = N'has volunteer'
SET
  @IsActive_c677c49e = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_c677c49e,
  @Name = @Name_c677c49e,
  @Description = @Description_c677c49e,
  @Category = @Category_c677c49e,
  @IsDirectional = @IsDirectional_c677c49e,
  @ForwardLabel = @ForwardLabel_c677c49e,
  @ReverseLabel = @ReverseLabel_c677c49e,
  @IsActive = @IsActive_c677c49e;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_2dca99a6 UNIQUEIDENTIFIER,
@Name_2dca99a6 NVARCHAR(100),
@Description_2dca99a6 NVARCHAR(MAX),
@Category_2dca99a6 NVARCHAR(50),
@IsDirectional_2dca99a6 BIT,
@ForwardLabel_2dca99a6 NVARCHAR(100),
@ReverseLabel_2dca99a6 NVARCHAR(100),
@IsActive_2dca99a6 BIT
SET
  @ID_2dca99a6 = 'DC06CB0C-A6CE-437C-A19E-F615F949BC51'
SET
  @Name_2dca99a6 = N'Customer'
SET
  @Description_2dca99a6 = N'Person is a customer or client of an organization'
SET
  @Category_2dca99a6 = N'PersonToOrganization'
SET
  @IsDirectional_2dca99a6 = 1
SET
  @ForwardLabel_2dca99a6 = N'is customer of'
SET
  @ReverseLabel_2dca99a6 = N'has customer'
SET
  @IsActive_2dca99a6 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_2dca99a6,
  @Name = @Name_2dca99a6,
  @Description = @Description_2dca99a6,
  @Category = @Category_2dca99a6,
  @IsDirectional = @IsDirectional_2dca99a6,
  @ForwardLabel = @ForwardLabel_2dca99a6,
  @ReverseLabel = @ReverseLabel_2dca99a6,
  @IsActive = @IsActive_2dca99a6;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_ffaa0af5 UNIQUEIDENTIFIER,
@Name_ffaa0af5 NVARCHAR(100),
@Description_ffaa0af5 NVARCHAR(MAX),
@Category_ffaa0af5 NVARCHAR(50),
@IsDirectional_ffaa0af5 BIT,
@ForwardLabel_ffaa0af5 NVARCHAR(100),
@ReverseLabel_ffaa0af5 NVARCHAR(100),
@IsActive_ffaa0af5 BIT
SET
  @ID_ffaa0af5 = '6BF6959D-18B4-4615-AFCE-643963A87C1B'
SET
  @Name_ffaa0af5 = N'Consultant'
SET
  @Description_ffaa0af5 = N'Person provides consulting services to an organization'
SET
  @Category_ffaa0af5 = N'PersonToOrganization'
SET
  @IsDirectional_ffaa0af5 = 1
SET
  @ForwardLabel_ffaa0af5 = N'consults for'
SET
  @ReverseLabel_ffaa0af5 = N'has consultant'
SET
  @IsActive_ffaa0af5 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_ffaa0af5,
  @Name = @Name_ffaa0af5,
  @Description = @Description_ffaa0af5,
  @Category = @Category_ffaa0af5,
  @IsDirectional = @IsDirectional_ffaa0af5,
  @ForwardLabel = @ForwardLabel_ffaa0af5,
  @ReverseLabel = @ReverseLabel_ffaa0af5,
  @IsActive = @IsActive_ffaa0af5;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_b9318095 UNIQUEIDENTIFIER,
@Name_b9318095 NVARCHAR(100),
@Description_b9318095 NVARCHAR(MAX),
@Category_b9318095 NVARCHAR(50),
@IsDirectional_b9318095 BIT,
@ForwardLabel_b9318095 NVARCHAR(100),
@ReverseLabel_b9318095 NVARCHAR(100),
@IsActive_b9318095 BIT
SET
  @ID_b9318095 = '39373681-5C70-4845-896B-4BFE4343751F'
SET
  @Name_b9318095 = N'Subsidiary'
SET
  @Description_b9318095 = N'One organization is a subsidiary or division of another'
SET
  @Category_b9318095 = N'OrganizationToOrganization'
SET
  @IsDirectional_b9318095 = 1
SET
  @ForwardLabel_b9318095 = N'is subsidiary of'
SET
  @ReverseLabel_b9318095 = N'has subsidiary'
SET
  @IsActive_b9318095 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_b9318095,
  @Name = @Name_b9318095,
  @Description = @Description_b9318095,
  @Category = @Category_b9318095,
  @IsDirectional = @IsDirectional_b9318095,
  @ForwardLabel = @ForwardLabel_b9318095,
  @ReverseLabel = @ReverseLabel_b9318095,
  @IsActive = @IsActive_b9318095;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_aa0771a2 UNIQUEIDENTIFIER,
@Name_aa0771a2 NVARCHAR(100),
@Description_aa0771a2 NVARCHAR(MAX),
@Category_aa0771a2 NVARCHAR(50),
@IsDirectional_aa0771a2 BIT,
@ForwardLabel_aa0771a2 NVARCHAR(100),
@ReverseLabel_aa0771a2 NVARCHAR(100),
@IsActive_aa0771a2 BIT
SET
  @ID_aa0771a2 = 'CA9BBDBE-3595-4C3F-80FF-DA78D3389EA7'
SET
  @Name_aa0771a2 = N'Partner'
SET
  @Description_aa0771a2 = N'Strategic or business partnership between organizations'
SET
  @Category_aa0771a2 = N'OrganizationToOrganization'
SET
  @IsDirectional_aa0771a2 = 0
SET
  @ForwardLabel_aa0771a2 = N'is partner of'
SET
  @ReverseLabel_aa0771a2 = N'is partner of'
SET
  @IsActive_aa0771a2 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_aa0771a2,
  @Name = @Name_aa0771a2,
  @Description = @Description_aa0771a2,
  @Category = @Category_aa0771a2,
  @IsDirectional = @IsDirectional_aa0771a2,
  @ForwardLabel = @ForwardLabel_aa0771a2,
  @ReverseLabel = @ReverseLabel_aa0771a2,
  @IsActive = @IsActive_aa0771a2;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_89118943 UNIQUEIDENTIFIER,
@Name_89118943 NVARCHAR(100),
@Description_89118943 NVARCHAR(MAX),
@Category_89118943 NVARCHAR(50),
@IsDirectional_89118943 BIT,
@ForwardLabel_89118943 NVARCHAR(100),
@ReverseLabel_89118943 NVARCHAR(100),
@IsActive_89118943 BIT
SET
  @ID_89118943 = '190A8BBF-771E-4631-980A-84918311E5EC'
SET
  @Name_89118943 = N'Vendor'
SET
  @Description_89118943 = N'One organization supplies goods or services to another'
SET
  @Category_89118943 = N'OrganizationToOrganization'
SET
  @IsDirectional_89118943 = 1
SET
  @ForwardLabel_89118943 = N'is vendor to'
SET
  @ReverseLabel_89118943 = N'has vendor'
SET
  @IsActive_89118943 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_89118943,
  @Name = @Name_89118943,
  @Description = @Description_89118943,
  @Category = @Category_89118943,
  @IsDirectional = @IsDirectional_89118943,
  @ForwardLabel = @ForwardLabel_89118943,
  @ReverseLabel = @ReverseLabel_89118943,
  @IsActive = @IsActive_89118943;

GO

-- Save MJ_BizApps_Common: Relationship Types (core SP call only)
DECLARE @ID_6464d1d0 UNIQUEIDENTIFIER,
@Name_6464d1d0 NVARCHAR(100),
@Description_6464d1d0 NVARCHAR(MAX),
@Category_6464d1d0 NVARCHAR(50),
@IsDirectional_6464d1d0 BIT,
@ForwardLabel_6464d1d0 NVARCHAR(100),
@ReverseLabel_6464d1d0 NVARCHAR(100),
@IsActive_6464d1d0 BIT
SET
  @ID_6464d1d0 = '2DBA78A6-DF6F-4A7E-B126-AE038BD3B6BA'
SET
  @Name_6464d1d0 = N'Affiliate'
SET
  @Description_6464d1d0 = N'Formal affiliation between two organizations'
SET
  @Category_6464d1d0 = N'OrganizationToOrganization'
SET
  @IsDirectional_6464d1d0 = 0
SET
  @ForwardLabel_6464d1d0 = N'is affiliate of'
SET
  @ReverseLabel_6464d1d0 = N'is affiliate of'
SET
  @IsActive_6464d1d0 = 1
EXEC [__mj_BizAppsCommon].spCreateRelationshipType @ID = @ID_6464d1d0,
  @Name = @Name_6464d1d0,
  @Description = @Description_6464d1d0,
  @Category = @Category_6464d1d0,
  @IsDirectional = @IsDirectional_6464d1d0,
  @ForwardLabel = @ForwardLabel_6464d1d0,
  @ReverseLabel = @ReverseLabel_6464d1d0,
  @IsActive = @IsActive_6464d1d0;

GO

-- Save MJ: Entities (core SP call only)
DECLARE @ParentID_c202feb6 UNIQUEIDENTIFIER,
@Name_c202feb6 NVARCHAR(255),
@NameSuffix_c202feb6 NVARCHAR(255),
@Description_c202feb6 NVARCHAR(MAX),
@AutoUpdateDescription_c202feb6 BIT,
@BaseView_c202feb6 NVARCHAR(255),
@BaseViewGenerated_c202feb6 BIT,
@VirtualEntity_c202feb6 BIT,
@TrackRecordChanges_c202feb6 BIT,
@AuditRecordAccess_c202feb6 BIT,
@AuditViewRuns_c202feb6 BIT,
@IncludeInAPI_c202feb6 BIT,
@AllowAllRowsAPI_c202feb6 BIT,
@AllowUpdateAPI_c202feb6 BIT,
@AllowCreateAPI_c202feb6 BIT,
@AllowDeleteAPI_c202feb6 BIT,
@CustomResolverAPI_c202feb6 BIT,
@AllowUserSearchAPI_c202feb6 BIT,
@FullTextSearchEnabled_c202feb6 BIT,
@FullTextCatalog_c202feb6 NVARCHAR(255),
@FullTextCatalogGenerated_c202feb6 BIT,
@FullTextIndex_c202feb6 NVARCHAR(255),
@FullTextIndexGenerated_c202feb6 BIT,
@FullTextSearchFunction_c202feb6 NVARCHAR(255),
@FullTextSearchFunctionGenerated_c202feb6 BIT,
@UserViewMaxRows_c202feb6 INT,
@spCreate_c202feb6 NVARCHAR(255),
@spUpdate_c202feb6 NVARCHAR(255),
@spDelete_c202feb6 NVARCHAR(255),
@spCreateGenerated_c202feb6 BIT,
@spUpdateGenerated_c202feb6 BIT,
@spDeleteGenerated_c202feb6 BIT,
@CascadeDeletes_c202feb6 BIT,
@DeleteType_c202feb6 NVARCHAR(10),
@AllowRecordMerge_c202feb6 BIT,
@spMatch_c202feb6 NVARCHAR(255),
@RelationshipDefaultDisplayType_c202feb6 NVARCHAR(20),
@UserFormGenerated_c202feb6 BIT,
@EntityObjectSubclassName_c202feb6 NVARCHAR(255),
@EntityObjectSubclassImport_c202feb6 NVARCHAR(255),
@PreferredCommunicationField_c202feb6 NVARCHAR(255),
@Icon_c202feb6 NVARCHAR(500),
@ScopeDefault_c202feb6 NVARCHAR(100),
@RowsToPackWithSchema_c202feb6 NVARCHAR(20),
@RowsToPackSampleMethod_c202feb6 NVARCHAR(20),
@RowsToPackSampleCount_c202feb6 INT,
@RowsToPackSampleOrder_c202feb6 NVARCHAR(MAX),
@AutoRowCountFrequency_c202feb6 INT,
@RowCount_c202feb6 BIGINT,
@RowCountRunAt_c202feb6 DATETIMEOFFSET,
@Status_c202feb6 NVARCHAR(25),
@DisplayName_c202feb6 NVARCHAR(255),
@AllowMultipleSubtypes_c202feb6 BIT,
@AutoUpdateFullTextSearch_c202feb6 BIT,
@AutoUpdateAllowUserSearchAPI_c202feb6 BIT,
@TrustServerCacheCompletely_c202feb6 BIT,
@SupportsGeoCoding_c202feb6 BIT,
@AutoUpdateSupportsGeoCoding_c202feb6 BIT,
@AllowCaching_c202feb6 BIT,
@DetectExternalChanges_c202feb6 BIT,
@ID_c202feb6 UNIQUEIDENTIFIER
SET
  @Name_c202feb6 = N'MJ_BizApps_Common: People'
SET
  @Description_c202feb6 = N'Individual people, optionally linked to MJ system user accounts'
SET
  @AutoUpdateDescription_c202feb6 = 1
SET
  @BaseView_c202feb6 = N'vwPeopleExtended'
SET
  @BaseViewGenerated_c202feb6 = 0
SET
  @VirtualEntity_c202feb6 = 0
SET
  @TrackRecordChanges_c202feb6 = 1
SET
  @AuditRecordAccess_c202feb6 = 0
SET
  @AuditViewRuns_c202feb6 = 0
SET
  @IncludeInAPI_c202feb6 = 1
SET
  @AllowAllRowsAPI_c202feb6 = 0
SET
  @AllowUpdateAPI_c202feb6 = 1
SET
  @AllowCreateAPI_c202feb6 = 1
SET
  @AllowDeleteAPI_c202feb6 = 1
SET
  @CustomResolverAPI_c202feb6 = 0
SET
  @AllowUserSearchAPI_c202feb6 = 0
SET
  @FullTextSearchEnabled_c202feb6 = 0
SET
  @FullTextCatalogGenerated_c202feb6 = 1
SET
  @FullTextIndexGenerated_c202feb6 = 1
SET
  @FullTextSearchFunctionGenerated_c202feb6 = 1
SET
  @UserViewMaxRows_c202feb6 = 1000
SET
  @spCreateGenerated_c202feb6 = 1
SET
  @spUpdateGenerated_c202feb6 = 1
SET
  @spDeleteGenerated_c202feb6 = 1
SET
  @CascadeDeletes_c202feb6 = 0
SET
  @DeleteType_c202feb6 = N'Hard'
SET
  @AllowRecordMerge_c202feb6 = 0
SET
  @RelationshipDefaultDisplayType_c202feb6 = N'Search'
SET
  @UserFormGenerated_c202feb6 = 1
SET
  @Icon_c202feb6 = N'fa fa-users'
SET
  @RowsToPackWithSchema_c202feb6 = N'None'
SET
  @RowsToPackSampleMethod_c202feb6 = N'random'
SET
  @RowsToPackSampleCount_c202feb6 = 0
SET
  @Status_c202feb6 = N'Active'
SET
  @DisplayName_c202feb6 = N'People'
SET
  @AllowMultipleSubtypes_c202feb6 = 0
SET
  @AutoUpdateFullTextSearch_c202feb6 = 1
SET
  @AutoUpdateAllowUserSearchAPI_c202feb6 = 1
SET
  @TrustServerCacheCompletely_c202feb6 = 1
SET
  @SupportsGeoCoding_c202feb6 = 0
SET
  @AutoUpdateSupportsGeoCoding_c202feb6 = 1
SET
  @AllowCaching_c202feb6 = 0
SET
  @DetectExternalChanges_c202feb6 = 0
SET
  @ID_c202feb6 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F' EXEC [__mj].spUpdateEntity @ParentID = @ParentID_c202feb6,
  @ParentID_Clear = 1,
  @Name = @Name_c202feb6,
  @NameSuffix = @NameSuffix_c202feb6,
  @NameSuffix_Clear = 1,
  @Description = @Description_c202feb6,
  @AutoUpdateDescription = @AutoUpdateDescription_c202feb6,
  @BaseView = @BaseView_c202feb6,
  @BaseViewGenerated = @BaseViewGenerated_c202feb6,
  @VirtualEntity = @VirtualEntity_c202feb6,
  @TrackRecordChanges = @TrackRecordChanges_c202feb6,
  @AuditRecordAccess = @AuditRecordAccess_c202feb6,
  @AuditViewRuns = @AuditViewRuns_c202feb6,
  @IncludeInAPI = @IncludeInAPI_c202feb6,
  @AllowAllRowsAPI = @AllowAllRowsAPI_c202feb6,
  @AllowUpdateAPI = @AllowUpdateAPI_c202feb6,
  @AllowCreateAPI = @AllowCreateAPI_c202feb6,
  @AllowDeleteAPI = @AllowDeleteAPI_c202feb6,
  @CustomResolverAPI = @CustomResolverAPI_c202feb6,
  @AllowUserSearchAPI = @AllowUserSearchAPI_c202feb6,
  @FullTextSearchEnabled = @FullTextSearchEnabled_c202feb6,
  @FullTextCatalog = @FullTextCatalog_c202feb6,
  @FullTextCatalog_Clear = 1,
  @FullTextCatalogGenerated = @FullTextCatalogGenerated_c202feb6,
  @FullTextIndex = @FullTextIndex_c202feb6,
  @FullTextIndex_Clear = 1,
  @FullTextIndexGenerated = @FullTextIndexGenerated_c202feb6,
  @FullTextSearchFunction = @FullTextSearchFunction_c202feb6,
  @FullTextSearchFunction_Clear = 1,
  @FullTextSearchFunctionGenerated = @FullTextSearchFunctionGenerated_c202feb6,
  @UserViewMaxRows = @UserViewMaxRows_c202feb6,
  @spCreate = @spCreate_c202feb6,
  @spCreate_Clear = 1,
  @spUpdate = @spUpdate_c202feb6,
  @spUpdate_Clear = 1,
  @spDelete = @spDelete_c202feb6,
  @spDelete_Clear = 1,
  @spCreateGenerated = @spCreateGenerated_c202feb6,
  @spUpdateGenerated = @spUpdateGenerated_c202feb6,
  @spDeleteGenerated = @spDeleteGenerated_c202feb6,
  @CascadeDeletes = @CascadeDeletes_c202feb6,
  @DeleteType = @DeleteType_c202feb6,
  @AllowRecordMerge = @AllowRecordMerge_c202feb6,
  @spMatch = @spMatch_c202feb6,
  @spMatch_Clear = 1,
  @RelationshipDefaultDisplayType = @RelationshipDefaultDisplayType_c202feb6,
  @UserFormGenerated = @UserFormGenerated_c202feb6,
  @EntityObjectSubclassName = @EntityObjectSubclassName_c202feb6,
  @EntityObjectSubclassName_Clear = 1,
  @EntityObjectSubclassImport = @EntityObjectSubclassImport_c202feb6,
  @EntityObjectSubclassImport_Clear = 1,
  @PreferredCommunicationField = @PreferredCommunicationField_c202feb6,
  @PreferredCommunicationField_Clear = 1,
  @Icon = @Icon_c202feb6,
  @ScopeDefault = @ScopeDefault_c202feb6,
  @ScopeDefault_Clear = 1,
  @RowsToPackWithSchema = @RowsToPackWithSchema_c202feb6,
  @RowsToPackSampleMethod = @RowsToPackSampleMethod_c202feb6,
  @RowsToPackSampleCount = @RowsToPackSampleCount_c202feb6,
  @RowsToPackSampleOrder = @RowsToPackSampleOrder_c202feb6,
  @RowsToPackSampleOrder_Clear = 1,
  @AutoRowCountFrequency = @AutoRowCountFrequency_c202feb6,
  @AutoRowCountFrequency_Clear = 1,
  @RowCount = @RowCount_c202feb6,
  @RowCount_Clear = 1,
  @RowCountRunAt = @RowCountRunAt_c202feb6,
  @RowCountRunAt_Clear = 1,
  @Status = @Status_c202feb6,
  @DisplayName = @DisplayName_c202feb6,
  @AllowMultipleSubtypes = @AllowMultipleSubtypes_c202feb6,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_c202feb6,
  @AutoUpdateAllowUserSearchAPI = @AutoUpdateAllowUserSearchAPI_c202feb6,
  @TrustServerCacheCompletely = @TrustServerCacheCompletely_c202feb6,
  @SupportsGeoCoding = @SupportsGeoCoding_c202feb6,
  @AutoUpdateSupportsGeoCoding = @AutoUpdateSupportsGeoCoding_c202feb6,
  @AllowCaching = @AllowCaching_c202feb6,
  @DetectExternalChanges = @DetectExternalChanges_c202feb6,
  @ID = @ID_c202feb6;

GO

-- Save MJ: Entities (core SP call only)
DECLARE @ParentID_08456450 UNIQUEIDENTIFIER,
@Name_08456450 NVARCHAR(255),
@NameSuffix_08456450 NVARCHAR(255),
@Description_08456450 NVARCHAR(MAX),
@AutoUpdateDescription_08456450 BIT,
@BaseView_08456450 NVARCHAR(255),
@BaseViewGenerated_08456450 BIT,
@VirtualEntity_08456450 BIT,
@TrackRecordChanges_08456450 BIT,
@AuditRecordAccess_08456450 BIT,
@AuditViewRuns_08456450 BIT,
@IncludeInAPI_08456450 BIT,
@AllowAllRowsAPI_08456450 BIT,
@AllowUpdateAPI_08456450 BIT,
@AllowCreateAPI_08456450 BIT,
@AllowDeleteAPI_08456450 BIT,
@CustomResolverAPI_08456450 BIT,
@AllowUserSearchAPI_08456450 BIT,
@FullTextSearchEnabled_08456450 BIT,
@FullTextCatalog_08456450 NVARCHAR(255),
@FullTextCatalogGenerated_08456450 BIT,
@FullTextIndex_08456450 NVARCHAR(255),
@FullTextIndexGenerated_08456450 BIT,
@FullTextSearchFunction_08456450 NVARCHAR(255),
@FullTextSearchFunctionGenerated_08456450 BIT,
@UserViewMaxRows_08456450 INT,
@spCreate_08456450 NVARCHAR(255),
@spUpdate_08456450 NVARCHAR(255),
@spDelete_08456450 NVARCHAR(255),
@spCreateGenerated_08456450 BIT,
@spUpdateGenerated_08456450 BIT,
@spDeleteGenerated_08456450 BIT,
@CascadeDeletes_08456450 BIT,
@DeleteType_08456450 NVARCHAR(10),
@AllowRecordMerge_08456450 BIT,
@spMatch_08456450 NVARCHAR(255),
@RelationshipDefaultDisplayType_08456450 NVARCHAR(20),
@UserFormGenerated_08456450 BIT,
@EntityObjectSubclassName_08456450 NVARCHAR(255),
@EntityObjectSubclassImport_08456450 NVARCHAR(255),
@PreferredCommunicationField_08456450 NVARCHAR(255),
@Icon_08456450 NVARCHAR(500),
@ScopeDefault_08456450 NVARCHAR(100),
@RowsToPackWithSchema_08456450 NVARCHAR(20),
@RowsToPackSampleMethod_08456450 NVARCHAR(20),
@RowsToPackSampleCount_08456450 INT,
@RowsToPackSampleOrder_08456450 NVARCHAR(MAX),
@AutoRowCountFrequency_08456450 INT,
@RowCount_08456450 BIGINT,
@RowCountRunAt_08456450 DATETIMEOFFSET,
@Status_08456450 NVARCHAR(25),
@DisplayName_08456450 NVARCHAR(255),
@AllowMultipleSubtypes_08456450 BIT,
@AutoUpdateFullTextSearch_08456450 BIT,
@AutoUpdateAllowUserSearchAPI_08456450 BIT,
@TrustServerCacheCompletely_08456450 BIT,
@SupportsGeoCoding_08456450 BIT,
@AutoUpdateSupportsGeoCoding_08456450 BIT,
@AllowCaching_08456450 BIT,
@DetectExternalChanges_08456450 BIT,
@ID_08456450 UNIQUEIDENTIFIER
SET
  @Name_08456450 = N'MJ_BizApps_Common: Organizations'
SET
  @Description_08456450 = N'Companies, associations, government bodies, and other organizations with hierarchy support'
SET
  @AutoUpdateDescription_08456450 = 1
SET
  @BaseView_08456450 = N'vwOrganizationsExtended'
SET
  @BaseViewGenerated_08456450 = 0
SET
  @VirtualEntity_08456450 = 0
SET
  @TrackRecordChanges_08456450 = 1
SET
  @AuditRecordAccess_08456450 = 0
SET
  @AuditViewRuns_08456450 = 0
SET
  @IncludeInAPI_08456450 = 1
SET
  @AllowAllRowsAPI_08456450 = 0
SET
  @AllowUpdateAPI_08456450 = 1
SET
  @AllowCreateAPI_08456450 = 1
SET
  @AllowDeleteAPI_08456450 = 1
SET
  @CustomResolverAPI_08456450 = 0
SET
  @AllowUserSearchAPI_08456450 = 0
SET
  @FullTextSearchEnabled_08456450 = 0
SET
  @FullTextCatalogGenerated_08456450 = 1
SET
  @FullTextIndexGenerated_08456450 = 1
SET
  @FullTextSearchFunctionGenerated_08456450 = 1
SET
  @UserViewMaxRows_08456450 = 1000
SET
  @spCreateGenerated_08456450 = 1
SET
  @spUpdateGenerated_08456450 = 1
SET
  @spDeleteGenerated_08456450 = 1
SET
  @CascadeDeletes_08456450 = 1
SET
  @DeleteType_08456450 = N'Hard'
SET
  @AllowRecordMerge_08456450 = 0
SET
  @RelationshipDefaultDisplayType_08456450 = N'Search'
SET
  @UserFormGenerated_08456450 = 1
SET
  @Icon_08456450 = N'fa fa-building'
SET
  @RowsToPackWithSchema_08456450 = N'None'
SET
  @RowsToPackSampleMethod_08456450 = N'random'
SET
  @RowsToPackSampleCount_08456450 = 0
SET
  @Status_08456450 = N'Active'
SET
  @DisplayName_08456450 = N'Organizations'
SET
  @AllowMultipleSubtypes_08456450 = 0
SET
  @AutoUpdateFullTextSearch_08456450 = 1
SET
  @AutoUpdateAllowUserSearchAPI_08456450 = 1
SET
  @TrustServerCacheCompletely_08456450 = 1
SET
  @SupportsGeoCoding_08456450 = 0
SET
  @AutoUpdateSupportsGeoCoding_08456450 = 1
SET
  @AllowCaching_08456450 = 0
SET
  @DetectExternalChanges_08456450 = 0
SET
  @ID_08456450 = 'C70448F9-9792-41D7-A82C-784B66429D54' EXEC [__mj].spUpdateEntity @ParentID = @ParentID_08456450,
  @ParentID_Clear = 1,
  @Name = @Name_08456450,
  @NameSuffix = @NameSuffix_08456450,
  @NameSuffix_Clear = 1,
  @Description = @Description_08456450,
  @AutoUpdateDescription = @AutoUpdateDescription_08456450,
  @BaseView = @BaseView_08456450,
  @BaseViewGenerated = @BaseViewGenerated_08456450,
  @VirtualEntity = @VirtualEntity_08456450,
  @TrackRecordChanges = @TrackRecordChanges_08456450,
  @AuditRecordAccess = @AuditRecordAccess_08456450,
  @AuditViewRuns = @AuditViewRuns_08456450,
  @IncludeInAPI = @IncludeInAPI_08456450,
  @AllowAllRowsAPI = @AllowAllRowsAPI_08456450,
  @AllowUpdateAPI = @AllowUpdateAPI_08456450,
  @AllowCreateAPI = @AllowCreateAPI_08456450,
  @AllowDeleteAPI = @AllowDeleteAPI_08456450,
  @CustomResolverAPI = @CustomResolverAPI_08456450,
  @AllowUserSearchAPI = @AllowUserSearchAPI_08456450,
  @FullTextSearchEnabled = @FullTextSearchEnabled_08456450,
  @FullTextCatalog = @FullTextCatalog_08456450,
  @FullTextCatalog_Clear = 1,
  @FullTextCatalogGenerated = @FullTextCatalogGenerated_08456450,
  @FullTextIndex = @FullTextIndex_08456450,
  @FullTextIndex_Clear = 1,
  @FullTextIndexGenerated = @FullTextIndexGenerated_08456450,
  @FullTextSearchFunction = @FullTextSearchFunction_08456450,
  @FullTextSearchFunction_Clear = 1,
  @FullTextSearchFunctionGenerated = @FullTextSearchFunctionGenerated_08456450,
  @UserViewMaxRows = @UserViewMaxRows_08456450,
  @spCreate = @spCreate_08456450,
  @spCreate_Clear = 1,
  @spUpdate = @spUpdate_08456450,
  @spUpdate_Clear = 1,
  @spDelete = @spDelete_08456450,
  @spDelete_Clear = 1,
  @spCreateGenerated = @spCreateGenerated_08456450,
  @spUpdateGenerated = @spUpdateGenerated_08456450,
  @spDeleteGenerated = @spDeleteGenerated_08456450,
  @CascadeDeletes = @CascadeDeletes_08456450,
  @DeleteType = @DeleteType_08456450,
  @AllowRecordMerge = @AllowRecordMerge_08456450,
  @spMatch = @spMatch_08456450,
  @spMatch_Clear = 1,
  @RelationshipDefaultDisplayType = @RelationshipDefaultDisplayType_08456450,
  @UserFormGenerated = @UserFormGenerated_08456450,
  @EntityObjectSubclassName = @EntityObjectSubclassName_08456450,
  @EntityObjectSubclassName_Clear = 1,
  @EntityObjectSubclassImport = @EntityObjectSubclassImport_08456450,
  @EntityObjectSubclassImport_Clear = 1,
  @PreferredCommunicationField = @PreferredCommunicationField_08456450,
  @PreferredCommunicationField_Clear = 1,
  @Icon = @Icon_08456450,
  @ScopeDefault = @ScopeDefault_08456450,
  @ScopeDefault_Clear = 1,
  @RowsToPackWithSchema = @RowsToPackWithSchema_08456450,
  @RowsToPackSampleMethod = @RowsToPackSampleMethod_08456450,
  @RowsToPackSampleCount = @RowsToPackSampleCount_08456450,
  @RowsToPackSampleOrder = @RowsToPackSampleOrder_08456450,
  @RowsToPackSampleOrder_Clear = 1,
  @AutoRowCountFrequency = @AutoRowCountFrequency_08456450,
  @AutoRowCountFrequency_Clear = 1,
  @RowCount = @RowCount_08456450,
  @RowCount_Clear = 1,
  @RowCountRunAt = @RowCountRunAt_08456450,
  @RowCountRunAt_Clear = 1,
  @Status = @Status_08456450,
  @DisplayName = @DisplayName_08456450,
  @AllowMultipleSubtypes = @AllowMultipleSubtypes_08456450,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_08456450,
  @AutoUpdateAllowUserSearchAPI = @AutoUpdateAllowUserSearchAPI_08456450,
  @TrustServerCacheCompletely = @TrustServerCacheCompletely_08456450,
  @SupportsGeoCoding = @SupportsGeoCoding_08456450,
  @AutoUpdateSupportsGeoCoding = @AutoUpdateSupportsGeoCoding_08456450,
  @AllowCaching = @AllowCaching_08456450,
  @DetectExternalChanges = @DetectExternalChanges_08456450,
  @ID = @ID_08456450;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_3da9a6d3 NVARCHAR(255),
@Description_3da9a6d3 NVARCHAR(MAX),
@AutoUpdateDescription_3da9a6d3 BIT,
@IsPrimaryKey_3da9a6d3 BIT,
@IsUnique_3da9a6d3 BIT,
@Category_3da9a6d3 NVARCHAR(255),
@ValueListType_3da9a6d3 NVARCHAR(20),
@ExtendedType_3da9a6d3 NVARCHAR(50),
@CodeType_3da9a6d3 NVARCHAR(50),
@DefaultInView_3da9a6d3 BIT,
@ViewCellTemplate_3da9a6d3 NVARCHAR(MAX),
@DefaultColumnWidth_3da9a6d3 INT,
@AllowUpdateAPI_3da9a6d3 BIT,
@AllowUpdateInView_3da9a6d3 BIT,
@IncludeInUserSearchAPI_3da9a6d3 BIT,
@FullTextSearchEnabled_3da9a6d3 BIT,
@UserSearchParamFormatAPI_3da9a6d3 NVARCHAR(500),
@IncludeInGeneratedForm_3da9a6d3 BIT,
@GeneratedFormSection_3da9a6d3 NVARCHAR(10),
@IsNameField_3da9a6d3 BIT,
@RelatedEntityID_3da9a6d3 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_3da9a6d3 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_3da9a6d3 BIT,
@RelatedEntityNameFieldMap_3da9a6d3 NVARCHAR(255),
@RelatedEntityDisplayType_3da9a6d3 NVARCHAR(20),
@EntityIDFieldName_3da9a6d3 NVARCHAR(100),
@ScopeDefault_3da9a6d3 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_3da9a6d3 BIT,
@ValuesToPackWithSchema_3da9a6d3 NVARCHAR(10),
@Status_3da9a6d3 NVARCHAR(25),
@AutoUpdateIsNameField_3da9a6d3 BIT,
@AutoUpdateDefaultInView_3da9a6d3 BIT,
@AutoUpdateCategory_3da9a6d3 BIT,
@AutoUpdateDisplayName_3da9a6d3 BIT,
@AutoUpdateIncludeInUserSearchAPI_3da9a6d3 BIT,
@Encrypt_3da9a6d3 BIT,
@EncryptionKeyID_3da9a6d3 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_3da9a6d3 BIT,
@SendEncryptedValue_3da9a6d3 BIT,
@IsSoftPrimaryKey_3da9a6d3 BIT,
@IsSoftForeignKey_3da9a6d3 BIT,
@RelatedEntityJoinFields_3da9a6d3 NVARCHAR(MAX),
@JSONType_3da9a6d3 NVARCHAR(255),
@JSONTypeIsArray_3da9a6d3 BIT,
@JSONTypeDefinition_3da9a6d3 NVARCHAR(MAX),
@UserSearchPredicateAPI_3da9a6d3 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_3da9a6d3 BIT,
@AutoUpdateFullTextSearch_3da9a6d3 BIT,
@AutoUpdateExtendedType_3da9a6d3 BIT,
@ID_3da9a6d3 UNIQUEIDENTIFIER
SET
  @DisplayName_3da9a6d3 = N'Display Name'
SET
  @AutoUpdateDescription_3da9a6d3 = 1
SET
  @IsPrimaryKey_3da9a6d3 = 0
SET
  @IsUnique_3da9a6d3 = 0
SET
  @ValueListType_3da9a6d3 = N'None'
SET
  @DefaultInView_3da9a6d3 = 0
SET
  @DefaultColumnWidth_3da9a6d3 = 150
SET
  @AllowUpdateAPI_3da9a6d3 = 0
SET
  @AllowUpdateInView_3da9a6d3 = 1
SET
  @IncludeInUserSearchAPI_3da9a6d3 = 0
SET
  @FullTextSearchEnabled_3da9a6d3 = 0
SET
  @IncludeInGeneratedForm_3da9a6d3 = 1
SET
  @GeneratedFormSection_3da9a6d3 = N'Details'
SET
  @IsNameField_3da9a6d3 = 1
SET
  @IncludeRelatedEntityNameFieldInBaseView_3da9a6d3 = 0
SET
  @RelatedEntityDisplayType_3da9a6d3 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_3da9a6d3 = 1
SET
  @ValuesToPackWithSchema_3da9a6d3 = N'Auto'
SET
  @Status_3da9a6d3 = N'Active'
SET
  @AutoUpdateIsNameField_3da9a6d3 = 0
SET
  @AutoUpdateDefaultInView_3da9a6d3 = 1
SET
  @AutoUpdateCategory_3da9a6d3 = 1
SET
  @AutoUpdateDisplayName_3da9a6d3 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_3da9a6d3 = 1
SET
  @Encrypt_3da9a6d3 = 0
SET
  @AllowDecryptInAPI_3da9a6d3 = 0
SET
  @SendEncryptedValue_3da9a6d3 = 0
SET
  @IsSoftPrimaryKey_3da9a6d3 = 0
SET
  @IsSoftForeignKey_3da9a6d3 = 0
SET
  @JSONTypeIsArray_3da9a6d3 = 0
SET
  @UserSearchPredicateAPI_3da9a6d3 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_3da9a6d3 = 1
SET
  @AutoUpdateFullTextSearch_3da9a6d3 = 1
SET
  @AutoUpdateExtendedType_3da9a6d3 = 1
SET
  @ID_3da9a6d3 = '76D49448-C586-4701-9FFF-63F390EC78C0' EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_3da9a6d3,
  @Description = @Description_3da9a6d3,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_3da9a6d3,
  @IsPrimaryKey = @IsPrimaryKey_3da9a6d3,
  @IsUnique = @IsUnique_3da9a6d3,
  @Category = @Category_3da9a6d3,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_3da9a6d3,
  @ExtendedType = @ExtendedType_3da9a6d3,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_3da9a6d3,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_3da9a6d3,
  @ViewCellTemplate = @ViewCellTemplate_3da9a6d3,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_3da9a6d3,
  @AllowUpdateAPI = @AllowUpdateAPI_3da9a6d3,
  @AllowUpdateInView = @AllowUpdateInView_3da9a6d3,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_3da9a6d3,
  @FullTextSearchEnabled = @FullTextSearchEnabled_3da9a6d3,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_3da9a6d3,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_3da9a6d3,
  @GeneratedFormSection = @GeneratedFormSection_3da9a6d3,
  @IsNameField = @IsNameField_3da9a6d3,
  @RelatedEntityID = @RelatedEntityID_3da9a6d3,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_3da9a6d3,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_3da9a6d3,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_3da9a6d3,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_3da9a6d3,
  @EntityIDFieldName = @EntityIDFieldName_3da9a6d3,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_3da9a6d3,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_3da9a6d3,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_3da9a6d3,
  @Status = @Status_3da9a6d3,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_3da9a6d3,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_3da9a6d3,
  @AutoUpdateCategory = @AutoUpdateCategory_3da9a6d3,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_3da9a6d3,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_3da9a6d3,
  @Encrypt = @Encrypt_3da9a6d3,
  @EncryptionKeyID = @EncryptionKeyID_3da9a6d3,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_3da9a6d3,
  @SendEncryptedValue = @SendEncryptedValue_3da9a6d3,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_3da9a6d3,
  @IsSoftForeignKey = @IsSoftForeignKey_3da9a6d3,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_3da9a6d3,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_3da9a6d3,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_3da9a6d3,
  @JSONTypeDefinition = @JSONTypeDefinition_3da9a6d3,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_3da9a6d3,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_3da9a6d3,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_3da9a6d3,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_3da9a6d3,
  @ID = @ID_3da9a6d3;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_6c271206 NVARCHAR(255),
@Description_6c271206 NVARCHAR(MAX),
@AutoUpdateDescription_6c271206 BIT,
@IsPrimaryKey_6c271206 BIT,
@IsUnique_6c271206 BIT,
@Category_6c271206 NVARCHAR(255),
@ValueListType_6c271206 NVARCHAR(20),
@ExtendedType_6c271206 NVARCHAR(50),
@CodeType_6c271206 NVARCHAR(50),
@DefaultInView_6c271206 BIT,
@ViewCellTemplate_6c271206 NVARCHAR(MAX),
@DefaultColumnWidth_6c271206 INT,
@AllowUpdateAPI_6c271206 BIT,
@AllowUpdateInView_6c271206 BIT,
@IncludeInUserSearchAPI_6c271206 BIT,
@FullTextSearchEnabled_6c271206 BIT,
@UserSearchParamFormatAPI_6c271206 NVARCHAR(500),
@IncludeInGeneratedForm_6c271206 BIT,
@GeneratedFormSection_6c271206 NVARCHAR(10),
@IsNameField_6c271206 BIT,
@RelatedEntityID_6c271206 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_6c271206 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_6c271206 BIT,
@RelatedEntityNameFieldMap_6c271206 NVARCHAR(255),
@RelatedEntityDisplayType_6c271206 NVARCHAR(20),
@EntityIDFieldName_6c271206 NVARCHAR(100),
@ScopeDefault_6c271206 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_6c271206 BIT,
@ValuesToPackWithSchema_6c271206 NVARCHAR(10),
@Status_6c271206 NVARCHAR(25),
@AutoUpdateIsNameField_6c271206 BIT,
@AutoUpdateDefaultInView_6c271206 BIT,
@AutoUpdateCategory_6c271206 BIT,
@AutoUpdateDisplayName_6c271206 BIT,
@AutoUpdateIncludeInUserSearchAPI_6c271206 BIT,
@Encrypt_6c271206 BIT,
@EncryptionKeyID_6c271206 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_6c271206 BIT,
@SendEncryptedValue_6c271206 BIT,
@IsSoftPrimaryKey_6c271206 BIT,
@IsSoftForeignKey_6c271206 BIT,
@RelatedEntityJoinFields_6c271206 NVARCHAR(MAX),
@JSONType_6c271206 NVARCHAR(255),
@JSONTypeIsArray_6c271206 BIT,
@JSONTypeDefinition_6c271206 NVARCHAR(MAX),
@UserSearchPredicateAPI_6c271206 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_6c271206 BIT,
@AutoUpdateFullTextSearch_6c271206 BIT,
@AutoUpdateExtendedType_6c271206 BIT,
@ID_6c271206 UNIQUEIDENTIFIER
SET
  @DisplayName_6c271206 = N'Last Name'
SET
  @Description_6c271206 = N'Last (family) name'
SET
  @AutoUpdateDescription_6c271206 = 1
SET
  @IsPrimaryKey_6c271206 = 0
SET
  @IsUnique_6c271206 = 0
SET
  @Category_6c271206 = N'Personal Identity'
SET
  @ValueListType_6c271206 = N'None'
SET
  @DefaultInView_6c271206 = 1
SET
  @DefaultColumnWidth_6c271206 = 150
SET
  @AllowUpdateAPI_6c271206 = 1
SET
  @AllowUpdateInView_6c271206 = 1
SET
  @IncludeInUserSearchAPI_6c271206 = 1
SET
  @FullTextSearchEnabled_6c271206 = 0
SET
  @IncludeInGeneratedForm_6c271206 = 1
SET
  @GeneratedFormSection_6c271206 = N'Category'
SET
  @IsNameField_6c271206 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_6c271206 = 0
SET
  @RelatedEntityDisplayType_6c271206 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_6c271206 = 1
SET
  @ValuesToPackWithSchema_6c271206 = N'Auto'
SET
  @Status_6c271206 = N'Active'
SET
  @AutoUpdateIsNameField_6c271206 = 0
SET
  @AutoUpdateDefaultInView_6c271206 = 1
SET
  @AutoUpdateCategory_6c271206 = 1
SET
  @AutoUpdateDisplayName_6c271206 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_6c271206 = 1
SET
  @Encrypt_6c271206 = 0
SET
  @AllowDecryptInAPI_6c271206 = 0
SET
  @SendEncryptedValue_6c271206 = 0
SET
  @IsSoftPrimaryKey_6c271206 = 0
SET
  @IsSoftForeignKey_6c271206 = 0
SET
  @JSONTypeIsArray_6c271206 = 0
SET
  @UserSearchPredicateAPI_6c271206 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_6c271206 = 1
SET
  @AutoUpdateFullTextSearch_6c271206 = 1
SET
  @AutoUpdateExtendedType_6c271206 = 1
SET
  @ID_6c271206 = '09AD91DA-42C7-44F4-AE71-5AC6E50D7657' EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_6c271206,
  @Description = @Description_6c271206,
  @AutoUpdateDescription = @AutoUpdateDescription_6c271206,
  @IsPrimaryKey = @IsPrimaryKey_6c271206,
  @IsUnique = @IsUnique_6c271206,
  @Category = @Category_6c271206,
  @ValueListType = @ValueListType_6c271206,
  @ExtendedType = @ExtendedType_6c271206,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_6c271206,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_6c271206,
  @ViewCellTemplate = @ViewCellTemplate_6c271206,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_6c271206,
  @AllowUpdateAPI = @AllowUpdateAPI_6c271206,
  @AllowUpdateInView = @AllowUpdateInView_6c271206,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_6c271206,
  @FullTextSearchEnabled = @FullTextSearchEnabled_6c271206,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_6c271206,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_6c271206,
  @GeneratedFormSection = @GeneratedFormSection_6c271206,
  @IsNameField = @IsNameField_6c271206,
  @RelatedEntityID = @RelatedEntityID_6c271206,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_6c271206,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_6c271206,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_6c271206,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_6c271206,
  @EntityIDFieldName = @EntityIDFieldName_6c271206,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_6c271206,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_6c271206,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_6c271206,
  @Status = @Status_6c271206,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_6c271206,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_6c271206,
  @AutoUpdateCategory = @AutoUpdateCategory_6c271206,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_6c271206,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_6c271206,
  @Encrypt = @Encrypt_6c271206,
  @EncryptionKeyID = @EncryptionKeyID_6c271206,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_6c271206,
  @SendEncryptedValue = @SendEncryptedValue_6c271206,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_6c271206,
  @IsSoftForeignKey = @IsSoftForeignKey_6c271206,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_6c271206,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_6c271206,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_6c271206,
  @JSONTypeDefinition = @JSONTypeDefinition_6c271206,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_6c271206,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_6c271206,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_6c271206,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_6c271206,
  @ID = @ID_6c271206;

GO


-- End of SQL Logging Session
-- Session ID: 13a9308d-41cd-4ee8-b7b7-10b95a0b35c7
-- Completed: 2026-05-14T07:27:13.231Z
-- Duration: 1294ms
-- Total Statements: 41
