-- SQL Logging Session
-- Session ID: 6c4530ad-c33a-4e0d-ac17-954550676b6e
-- Started: 2026-02-27T22:48:52.435Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction SQLServerDataProvider

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_d84c920f NVARCHAR(255),
@Description_d84c920f NVARCHAR(MAX),
@AutoUpdateDescription_d84c920f BIT,
@IsPrimaryKey_d84c920f BIT,
@IsUnique_d84c920f BIT,
@Category_d84c920f NVARCHAR(255),
@ValueListType_d84c920f NVARCHAR(20),
@ExtendedType_d84c920f NVARCHAR(50),
@CodeType_d84c920f NVARCHAR(50),
@DefaultInView_d84c920f BIT,
@ViewCellTemplate_d84c920f NVARCHAR(MAX),
@DefaultColumnWidth_d84c920f INT,
@AllowUpdateAPI_d84c920f BIT,
@AllowUpdateInView_d84c920f BIT,
@IncludeInUserSearchAPI_d84c920f BIT,
@FullTextSearchEnabled_d84c920f BIT,
@UserSearchParamFormatAPI_d84c920f NVARCHAR(500),
@IncludeInGeneratedForm_d84c920f BIT,
@GeneratedFormSection_d84c920f NVARCHAR(10),
@IsNameField_d84c920f BIT,
@RelatedEntityID_d84c920f UNIQUEIDENTIFIER,
@RelatedEntityFieldName_d84c920f NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_d84c920f BIT,
@RelatedEntityNameFieldMap_d84c920f NVARCHAR(255),
@RelatedEntityDisplayType_d84c920f NVARCHAR(20),
@EntityIDFieldName_d84c920f NVARCHAR(100),
@ScopeDefault_d84c920f NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_d84c920f BIT,
@ValuesToPackWithSchema_d84c920f NVARCHAR(10),
@Status_d84c920f NVARCHAR(25),
@AutoUpdateIsNameField_d84c920f BIT,
@AutoUpdateDefaultInView_d84c920f BIT,
@AutoUpdateCategory_d84c920f BIT,
@AutoUpdateDisplayName_d84c920f BIT,
@AutoUpdateIncludeInUserSearchAPI_d84c920f BIT,
@Encrypt_d84c920f BIT,
@EncryptionKeyID_d84c920f UNIQUEIDENTIFIER,
@AllowDecryptInAPI_d84c920f BIT,
@SendEncryptedValue_d84c920f BIT,
@IsSoftPrimaryKey_d84c920f BIT,
@IsSoftForeignKey_d84c920f BIT,
@RelatedEntityJoinFields_d84c920f NVARCHAR(MAX),
@ID_d84c920f UNIQUEIDENTIFIER
SET
  @DisplayName_d84c920f = N'Display Name'
SET
  @AutoUpdateDescription_d84c920f = 1
SET
  @IsPrimaryKey_d84c920f = 0
SET
  @IsUnique_d84c920f = 0
SET
  @Category_d84c920f = N'Personal Identity'
SET
  @ValueListType_d84c920f = N'None'
SET
  @DefaultInView_d84c920f = 1
SET
  @DefaultColumnWidth_d84c920f = 150
SET
  @AllowUpdateAPI_d84c920f = 0
SET
  @AllowUpdateInView_d84c920f = 1
SET
  @IncludeInUserSearchAPI_d84c920f = 1
SET
  @FullTextSearchEnabled_d84c920f = 0
SET
  @IncludeInGeneratedForm_d84c920f = 1
SET
  @GeneratedFormSection_d84c920f = N'Category'
SET
  @IsNameField_d84c920f = 1
SET
  @IncludeRelatedEntityNameFieldInBaseView_d84c920f = 0
SET
  @RelatedEntityDisplayType_d84c920f = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_d84c920f = 1
SET
  @ValuesToPackWithSchema_d84c920f = N'Auto'
SET
  @Status_d84c920f = N'Active'
SET
  @AutoUpdateIsNameField_d84c920f = 0
SET
  @AutoUpdateDefaultInView_d84c920f = 1
SET
  @AutoUpdateCategory_d84c920f = 1
SET
  @AutoUpdateDisplayName_d84c920f = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_d84c920f = 1
SET
  @Encrypt_d84c920f = 0
SET
  @AllowDecryptInAPI_d84c920f = 0
SET
  @SendEncryptedValue_d84c920f = 0
SET
  @IsSoftPrimaryKey_d84c920f = 0
SET
  @IsSoftForeignKey_d84c920f = 0
SET
  @ID_d84c920f = 'BA7B91FC-0564-44A0-83A7-8F193E345A86'
EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_d84c920f,
  @Description = @Description_d84c920f,
  @AutoUpdateDescription = @AutoUpdateDescription_d84c920f,
  @IsPrimaryKey = @IsPrimaryKey_d84c920f,
  @IsUnique = @IsUnique_d84c920f,
  @Category = @Category_d84c920f,
  @ValueListType = @ValueListType_d84c920f,
  @ExtendedType = @ExtendedType_d84c920f,
  @CodeType = @CodeType_d84c920f,
  @DefaultInView = @DefaultInView_d84c920f,
  @ViewCellTemplate = @ViewCellTemplate_d84c920f,
  @DefaultColumnWidth = @DefaultColumnWidth_d84c920f,
  @AllowUpdateAPI = @AllowUpdateAPI_d84c920f,
  @AllowUpdateInView = @AllowUpdateInView_d84c920f,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_d84c920f,
  @FullTextSearchEnabled = @FullTextSearchEnabled_d84c920f,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_d84c920f,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_d84c920f,
  @GeneratedFormSection = @GeneratedFormSection_d84c920f,
  @IsNameField = @IsNameField_d84c920f,
  @RelatedEntityID = @RelatedEntityID_d84c920f,
  @RelatedEntityFieldName = @RelatedEntityFieldName_d84c920f,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_d84c920f,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_d84c920f,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_d84c920f,
  @EntityIDFieldName = @EntityIDFieldName_d84c920f,
  @ScopeDefault = @ScopeDefault_d84c920f,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_d84c920f,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_d84c920f,
  @Status = @Status_d84c920f,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_d84c920f,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_d84c920f,
  @AutoUpdateCategory = @AutoUpdateCategory_d84c920f,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_d84c920f,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_d84c920f,
  @Encrypt = @Encrypt_d84c920f,
  @EncryptionKeyID = @EncryptionKeyID_d84c920f,
  @AllowDecryptInAPI = @AllowDecryptInAPI_d84c920f,
  @SendEncryptedValue = @SendEncryptedValue_d84c920f,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_d84c920f,
  @IsSoftForeignKey = @IsSoftForeignKey_d84c920f,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_d84c920f,
  @ID = @ID_d84c920f;

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_7ccbd8b5 NVARCHAR(255),
@Description_7ccbd8b5 NVARCHAR(MAX),
@AutoUpdateDescription_7ccbd8b5 BIT,
@IsPrimaryKey_7ccbd8b5 BIT,
@IsUnique_7ccbd8b5 BIT,
@Category_7ccbd8b5 NVARCHAR(255),
@ValueListType_7ccbd8b5 NVARCHAR(20),
@ExtendedType_7ccbd8b5 NVARCHAR(50),
@CodeType_7ccbd8b5 NVARCHAR(50),
@DefaultInView_7ccbd8b5 BIT,
@ViewCellTemplate_7ccbd8b5 NVARCHAR(MAX),
@DefaultColumnWidth_7ccbd8b5 INT,
@AllowUpdateAPI_7ccbd8b5 BIT,
@AllowUpdateInView_7ccbd8b5 BIT,
@IncludeInUserSearchAPI_7ccbd8b5 BIT,
@FullTextSearchEnabled_7ccbd8b5 BIT,
@UserSearchParamFormatAPI_7ccbd8b5 NVARCHAR(500),
@IncludeInGeneratedForm_7ccbd8b5 BIT,
@GeneratedFormSection_7ccbd8b5 NVARCHAR(10),
@IsNameField_7ccbd8b5 BIT,
@RelatedEntityID_7ccbd8b5 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_7ccbd8b5 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_7ccbd8b5 BIT,
@RelatedEntityNameFieldMap_7ccbd8b5 NVARCHAR(255),
@RelatedEntityDisplayType_7ccbd8b5 NVARCHAR(20),
@EntityIDFieldName_7ccbd8b5 NVARCHAR(100),
@ScopeDefault_7ccbd8b5 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_7ccbd8b5 BIT,
@ValuesToPackWithSchema_7ccbd8b5 NVARCHAR(10),
@Status_7ccbd8b5 NVARCHAR(25),
@AutoUpdateIsNameField_7ccbd8b5 BIT,
@AutoUpdateDefaultInView_7ccbd8b5 BIT,
@AutoUpdateCategory_7ccbd8b5 BIT,
@AutoUpdateDisplayName_7ccbd8b5 BIT,
@AutoUpdateIncludeInUserSearchAPI_7ccbd8b5 BIT,
@Encrypt_7ccbd8b5 BIT,
@EncryptionKeyID_7ccbd8b5 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_7ccbd8b5 BIT,
@SendEncryptedValue_7ccbd8b5 BIT,
@IsSoftPrimaryKey_7ccbd8b5 BIT,
@IsSoftForeignKey_7ccbd8b5 BIT,
@RelatedEntityJoinFields_7ccbd8b5 NVARCHAR(MAX),
@ID_7ccbd8b5 UNIQUEIDENTIFIER
SET
  @DisplayName_7ccbd8b5 = N'First Name'
SET
  @Description_7ccbd8b5 = N'First (given) name'
SET
  @AutoUpdateDescription_7ccbd8b5 = 1
SET
  @IsPrimaryKey_7ccbd8b5 = 0
SET
  @IsUnique_7ccbd8b5 = 0
SET
  @Category_7ccbd8b5 = N'Personal Identity'
SET
  @ValueListType_7ccbd8b5 = N'None'
SET
  @DefaultInView_7ccbd8b5 = 1
SET
  @DefaultColumnWidth_7ccbd8b5 = 150
SET
  @AllowUpdateAPI_7ccbd8b5 = 1
SET
  @AllowUpdateInView_7ccbd8b5 = 1
SET
  @IncludeInUserSearchAPI_7ccbd8b5 = 1
SET
  @FullTextSearchEnabled_7ccbd8b5 = 0
SET
  @IncludeInGeneratedForm_7ccbd8b5 = 1
SET
  @GeneratedFormSection_7ccbd8b5 = N'Category'
SET
  @IsNameField_7ccbd8b5 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_7ccbd8b5 = 0
SET
  @RelatedEntityDisplayType_7ccbd8b5 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_7ccbd8b5 = 1
SET
  @ValuesToPackWithSchema_7ccbd8b5 = N'Auto'
SET
  @Status_7ccbd8b5 = N'Active'
SET
  @AutoUpdateIsNameField_7ccbd8b5 = 0
SET
  @AutoUpdateDefaultInView_7ccbd8b5 = 1
SET
  @AutoUpdateCategory_7ccbd8b5 = 1
SET
  @AutoUpdateDisplayName_7ccbd8b5 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_7ccbd8b5 = 1
SET
  @Encrypt_7ccbd8b5 = 0
SET
  @AllowDecryptInAPI_7ccbd8b5 = 0
SET
  @SendEncryptedValue_7ccbd8b5 = 0
SET
  @IsSoftPrimaryKey_7ccbd8b5 = 0
SET
  @IsSoftForeignKey_7ccbd8b5 = 0
SET
  @ID_7ccbd8b5 = '4942CBCC-6D0B-44F5-BE38-9D697D02B463'
EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_7ccbd8b5,
  @Description = @Description_7ccbd8b5,
  @AutoUpdateDescription = @AutoUpdateDescription_7ccbd8b5,
  @IsPrimaryKey = @IsPrimaryKey_7ccbd8b5,
  @IsUnique = @IsUnique_7ccbd8b5,
  @Category = @Category_7ccbd8b5,
  @ValueListType = @ValueListType_7ccbd8b5,
  @ExtendedType = @ExtendedType_7ccbd8b5,
  @CodeType = @CodeType_7ccbd8b5,
  @DefaultInView = @DefaultInView_7ccbd8b5,
  @ViewCellTemplate = @ViewCellTemplate_7ccbd8b5,
  @DefaultColumnWidth = @DefaultColumnWidth_7ccbd8b5,
  @AllowUpdateAPI = @AllowUpdateAPI_7ccbd8b5,
  @AllowUpdateInView = @AllowUpdateInView_7ccbd8b5,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_7ccbd8b5,
  @FullTextSearchEnabled = @FullTextSearchEnabled_7ccbd8b5,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_7ccbd8b5,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_7ccbd8b5,
  @GeneratedFormSection = @GeneratedFormSection_7ccbd8b5,
  @IsNameField = @IsNameField_7ccbd8b5,
  @RelatedEntityID = @RelatedEntityID_7ccbd8b5,
  @RelatedEntityFieldName = @RelatedEntityFieldName_7ccbd8b5,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_7ccbd8b5,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_7ccbd8b5,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_7ccbd8b5,
  @EntityIDFieldName = @EntityIDFieldName_7ccbd8b5,
  @ScopeDefault = @ScopeDefault_7ccbd8b5,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_7ccbd8b5,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_7ccbd8b5,
  @Status = @Status_7ccbd8b5,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_7ccbd8b5,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_7ccbd8b5,
  @AutoUpdateCategory = @AutoUpdateCategory_7ccbd8b5,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_7ccbd8b5,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_7ccbd8b5,
  @Encrypt = @Encrypt_7ccbd8b5,
  @EncryptionKeyID = @EncryptionKeyID_7ccbd8b5,
  @AllowDecryptInAPI = @AllowDecryptInAPI_7ccbd8b5,
  @SendEncryptedValue = @SendEncryptedValue_7ccbd8b5,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_7ccbd8b5,
  @IsSoftForeignKey = @IsSoftForeignKey_7ccbd8b5,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_7ccbd8b5,
  @ID = @ID_7ccbd8b5;

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_95f986ef NVARCHAR(255),
@Description_95f986ef NVARCHAR(MAX),
@AutoUpdateDescription_95f986ef BIT,
@IsPrimaryKey_95f986ef BIT,
@IsUnique_95f986ef BIT,
@Category_95f986ef NVARCHAR(255),
@ValueListType_95f986ef NVARCHAR(20),
@ExtendedType_95f986ef NVARCHAR(50),
@CodeType_95f986ef NVARCHAR(50),
@DefaultInView_95f986ef BIT,
@ViewCellTemplate_95f986ef NVARCHAR(MAX),
@DefaultColumnWidth_95f986ef INT,
@AllowUpdateAPI_95f986ef BIT,
@AllowUpdateInView_95f986ef BIT,
@IncludeInUserSearchAPI_95f986ef BIT,
@FullTextSearchEnabled_95f986ef BIT,
@UserSearchParamFormatAPI_95f986ef NVARCHAR(500),
@IncludeInGeneratedForm_95f986ef BIT,
@GeneratedFormSection_95f986ef NVARCHAR(10),
@IsNameField_95f986ef BIT,
@RelatedEntityID_95f986ef UNIQUEIDENTIFIER,
@RelatedEntityFieldName_95f986ef NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_95f986ef BIT,
@RelatedEntityNameFieldMap_95f986ef NVARCHAR(255),
@RelatedEntityDisplayType_95f986ef NVARCHAR(20),
@EntityIDFieldName_95f986ef NVARCHAR(100),
@ScopeDefault_95f986ef NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_95f986ef BIT,
@ValuesToPackWithSchema_95f986ef NVARCHAR(10),
@Status_95f986ef NVARCHAR(25),
@AutoUpdateIsNameField_95f986ef BIT,
@AutoUpdateDefaultInView_95f986ef BIT,
@AutoUpdateCategory_95f986ef BIT,
@AutoUpdateDisplayName_95f986ef BIT,
@AutoUpdateIncludeInUserSearchAPI_95f986ef BIT,
@Encrypt_95f986ef BIT,
@EncryptionKeyID_95f986ef UNIQUEIDENTIFIER,
@AllowDecryptInAPI_95f986ef BIT,
@SendEncryptedValue_95f986ef BIT,
@IsSoftPrimaryKey_95f986ef BIT,
@IsSoftForeignKey_95f986ef BIT,
@RelatedEntityJoinFields_95f986ef NVARCHAR(MAX),
@ID_95f986ef UNIQUEIDENTIFIER
SET
  @DisplayName_95f986ef = N'Last Name'
SET
  @Description_95f986ef = N'Last (family) name'
SET
  @AutoUpdateDescription_95f986ef = 1
SET
  @IsPrimaryKey_95f986ef = 0
SET
  @IsUnique_95f986ef = 0
SET
  @Category_95f986ef = N'Personal Identity'
SET
  @ValueListType_95f986ef = N'None'
SET
  @DefaultInView_95f986ef = 1
SET
  @DefaultColumnWidth_95f986ef = 150
SET
  @AllowUpdateAPI_95f986ef = 1
SET
  @AllowUpdateInView_95f986ef = 1
SET
  @IncludeInUserSearchAPI_95f986ef = 1
SET
  @FullTextSearchEnabled_95f986ef = 0
SET
  @IncludeInGeneratedForm_95f986ef = 1
SET
  @GeneratedFormSection_95f986ef = N'Category'
SET
  @IsNameField_95f986ef = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_95f986ef = 0
SET
  @RelatedEntityDisplayType_95f986ef = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_95f986ef = 1
SET
  @ValuesToPackWithSchema_95f986ef = N'Auto'
SET
  @Status_95f986ef = N'Active'
SET
  @AutoUpdateIsNameField_95f986ef = 0
SET
  @AutoUpdateDefaultInView_95f986ef = 1
SET
  @AutoUpdateCategory_95f986ef = 1
SET
  @AutoUpdateDisplayName_95f986ef = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_95f986ef = 1
SET
  @Encrypt_95f986ef = 0
SET
  @AllowDecryptInAPI_95f986ef = 0
SET
  @SendEncryptedValue_95f986ef = 0
SET
  @IsSoftPrimaryKey_95f986ef = 0
SET
  @IsSoftForeignKey_95f986ef = 0
SET
  @ID_95f986ef = '09AD91DA-42C7-44F4-AE71-5AC6E50D7657'
EXEC [__mj].spUpdateEntityField @DisplayName = @DisplayName_95f986ef,
  @Description = @Description_95f986ef,
  @AutoUpdateDescription = @AutoUpdateDescription_95f986ef,
  @IsPrimaryKey = @IsPrimaryKey_95f986ef,
  @IsUnique = @IsUnique_95f986ef,
  @Category = @Category_95f986ef,
  @ValueListType = @ValueListType_95f986ef,
  @ExtendedType = @ExtendedType_95f986ef,
  @CodeType = @CodeType_95f986ef,
  @DefaultInView = @DefaultInView_95f986ef,
  @ViewCellTemplate = @ViewCellTemplate_95f986ef,
  @DefaultColumnWidth = @DefaultColumnWidth_95f986ef,
  @AllowUpdateAPI = @AllowUpdateAPI_95f986ef,
  @AllowUpdateInView = @AllowUpdateInView_95f986ef,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_95f986ef,
  @FullTextSearchEnabled = @FullTextSearchEnabled_95f986ef,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_95f986ef,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_95f986ef,
  @GeneratedFormSection = @GeneratedFormSection_95f986ef,
  @IsNameField = @IsNameField_95f986ef,
  @RelatedEntityID = @RelatedEntityID_95f986ef,
  @RelatedEntityFieldName = @RelatedEntityFieldName_95f986ef,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_95f986ef,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_95f986ef,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_95f986ef,
  @EntityIDFieldName = @EntityIDFieldName_95f986ef,
  @ScopeDefault = @ScopeDefault_95f986ef,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_95f986ef,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_95f986ef,
  @Status = @Status_95f986ef,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_95f986ef,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_95f986ef,
  @AutoUpdateCategory = @AutoUpdateCategory_95f986ef,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_95f986ef,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_95f986ef,
  @Encrypt = @Encrypt_95f986ef,
  @EncryptionKeyID = @EncryptionKeyID_95f986ef,
  @AllowDecryptInAPI = @AllowDecryptInAPI_95f986ef,
  @SendEncryptedValue = @SendEncryptedValue_95f986ef,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_95f986ef,
  @IsSoftForeignKey = @IsSoftForeignKey_95f986ef,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_95f986ef,
  @ID = @ID_95f986ef;


-- End of SQL Logging Session
-- Session ID: 6c4530ad-c33a-4e0d-ac17-954550676b6e
-- Completed: 2026-02-27T22:48:59.262Z
-- Duration: 6827ms
-- Total Statements: 3
