-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj_bizappscommon;
SET search_path TO __mj_bizappscommon, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- =====================================================================
-- v5.29 Metadata Sync
-- =====================================================================
--
-- Replays the metadata/ folder state into __mj."Entity", __mj."EntityField",
-- __mj."SchemaInfo", and BAC's seed-data tables (Address Types, Contact
-- Types, Organization Types, Relationship Types).
--
-- Two notable metadata changes ship here:
--   1. Person."DisplayName"."IsNameField" = TRUE (was: LastName)
--      Pairs with the new PERSISTED computed column DisplayName added
--      in V202605131929. Makes Person records display as "John Smith"
--      in dropdowns and FK tooltips instead of just "Smith".
--   2. Person."LastName"."IsNameField" = FALSE (un-set the previous auto-pick)
--
-- Generated by `mj sync push` against a freshly-migrated DB. Schema
-- references are literal `[__mj]` and `[__mj_bizappscommon]` (matches
-- BCSaaS's V202602251500__v1.0.x_Metadata_Sync.sql pattern).
--
-- =====================================================================

-- SQL Logging Session
-- Session ID: 134655f8-85d5-43c2-b18d-da8ba5f27c8a
-- Started: 2026-05-14T15:55:51.288Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Schema Info (core SP call only)
DO $mj$
DECLARE
  p_SchemaName_008fdd64 VARCHAR(50);
  p_EntityIDMin_008fdd64 INTEGER;
  p_EntityIDMax_008fdd64 INTEGER;
  p_Comments_008fdd64 TEXT;
  p_Description_008fdd64 TEXT;
  p_EntityNamePrefix_008fdd64 VARCHAR(25);
  p_EntityNameSuffix_008fdd64 VARCHAR(25);
  p_ID_008fdd64 UUID;
BEGIN
  p_SchemaName_008fdd64 := '__mj_bizappscommon';
  p_EntityIDMin_008fdd64 := 1;
  p_EntityIDMax_008fdd64 := 1000000;
  p_Description_008fdd64 := 'MemberJunction: Common Business App Data';
  p_EntityNamePrefix_008fdd64 := 'MJ_BizApps_Common: ';
  p_ID_008fdd64 := '0A9F0FDD-CD4D-4892-BA45-85722B982032';
  PERFORM __mj."spUpdateSchemaInfo"(p_SchemaName := p_SchemaName_008fdd64, p_EntityIDMin := p_EntityIDMin_008fdd64, p_EntityIDMax := p_EntityIDMax_008fdd64, p_Comments := p_Comments_008fdd64, p_Comments_Clear := TRUE, p_Description := p_Description_008fdd64, p_EntityNamePrefix := p_EntityNamePrefix_008fdd64, p_EntityNameSuffix := p_EntityNameSuffix_008fdd64, p_EntityNameSuffix_Clear := TRUE, p_ID := p_ID_008fdd64);
END $mj$;

-- Save MJ_BizApps_Common: Address Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."AddressType" ("ID", "Name", "Description", "IconClass", "DefaultRank", "IsActive")
VALUES ('49183F91-F101-48F6-B2BE-AEC550B2CA0E', 'Home', 'Primary residential address', 'fa-solid fa-house', 10, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Address Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."AddressType" ("ID", "Name", "Description", "IconClass", "DefaultRank", "IsActive")
VALUES ('0EFFA181-179B-4B68-ACC8-A57D55C4D73D', 'Work', 'Business or office address', 'fa-solid fa-building', 20, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Address Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."AddressType" ("ID", "Name", "Description", "IconClass", "DefaultRank", "IsActive")
VALUES ('964C05C1-C947-467B-97B9-A7495BDDB7B0', 'Mailing', 'Preferred address for receiving mail and correspondence', 'fa-solid fa-mailbox', 30, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Address Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."AddressType" ("ID", "Name", "Description", "IconClass", "DefaultRank", "IsActive")
VALUES ('E2C28836-F2C2-4590-A519-BCAB0E864974', 'Billing', 'Address used for invoices and financial correspondence', 'fa-solid fa-file-invoice-dollar', 40, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Address Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."AddressType" ("ID", "Name", "Description", "IconClass", "DefaultRank", "IsActive")
VALUES ('C466C5B0-35AE-46D6-B95E-88823E2E7EE5', 'Shipping', 'Address for physical deliveries', 'fa-solid fa-truck', 50, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Address Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."AddressType" ("ID", "Name", "Description", "IconClass", "DefaultRank", "IsActive")
VALUES ('4D1E1A1A-1CD1-4069-BF1E-198F838A0DFF', 'Legal', 'Registered legal or statutory address', 'fa-solid fa-scale-balanced', 60, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('FB4D3737-8479-44E5-AF91-2DB63311D293', 'Email', 'Email address', 'fa-solid fa-envelope', 10, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('96421246-0F8F-4CDB-A5C5-BA6B190C1AFE', 'Mobile Phone', 'Mobile or cell phone number', 'fa-solid fa-mobile-screen', 20, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('BCDA98AC-06A4-40FC-A1CC-E44BB783FBC9', 'Work Phone', 'Business or office phone number', 'fa-solid fa-phone-office', 30, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('C3BA9432-8D05-4AFE-BF6D-61F976A466E6', 'Home Phone', 'Residential phone number', 'fa-solid fa-phone', 40, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('FDBFF502-CE06-456B-BCC3-8A2C23D16D45', 'LinkedIn', 'LinkedIn profile URL', 'fa-brands fa-linkedin', 50, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('02A126F9-ED1B-4BBF-8479-8B10CC916150', 'Twitter / X', 'Twitter / X profile URL or handle', 'fa-brands fa-x-twitter', 60, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('F2DBF3EA-7ACF-4725-92D3-AB630B613293', 'Website', 'Personal or professional website URL', 'fa-solid fa-globe', 70, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Contact Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."ContactType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('A33D19DB-27FD-400C-A9C9-F3D3C4A12E8F', 'Fax', 'Fax number', 'fa-solid fa-fax', 80, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('A8DB7343-DCC9-44D1-B99F-9E21024C3C2E', 'Corporation', 'Incorporated business entity (C-Corp, S-Corp)', 'fa-solid fa-building', 10, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('288B017D-60A4-48A7-A845-EF30B99BDBEF', 'LLC', 'Limited liability company', 'fa-solid fa-briefcase', 20, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('BAAA53F4-A8AA-4EAA-B04E-1BA6F964B341', 'Non-Profit', 'Tax-exempt non-profit organization (501(c)(3), etc.)', 'fa-solid fa-hand-holding-heart', 30, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('1E61230B-0F48-458A-811B-66C9CF6B688E', 'Government', 'Government agency or department', 'fa-solid fa-landmark', 40, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('5CAB6265-CB87-4269-A321-2473160BD625', 'Partnership', 'General or limited partnership', 'fa-solid fa-handshake', 50, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('042C63AF-93EB-4BB4-A469-F3C209F8936E', 'Sole Proprietorship', 'Unincorporated business owned by a single individual', 'fa-solid fa-user-tie', 60, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('7D6D1763-3198-42B2-A23C-F0FF76DAD8D2', 'Association', 'Professional or trade association', 'fa-solid fa-people-group', 70, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Organization Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."OrganizationType" ("ID", "Name", "Description", "IconClass", "DisplayRank", "IsActive")
VALUES ('4BE0D87B-EFCB-447D-9410-FEF8EED23BC8', 'Educational Institution', 'School, college, university, or training organization', 'fa-solid fa-graduation-cap', 80, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('FEB33819-FC85-4309-B1EC-A54EEA91DACF', 'Spouse', 'Married or domestic partner relationship', 'PersonToPerson', FALSE, 'is spouse of', 'is spouse of', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('431DBAF3-AC1D-47E6-B91E-264E8C76FC57', 'Parent / Child', 'Parent-child family relationship', 'PersonToPerson', TRUE, 'is parent of', 'is child of', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('D471B007-0717-493E-AC0D-2F102A32BCC2', 'Sibling', 'Brother or sister relationship', 'PersonToPerson', FALSE, 'is sibling of', 'is sibling of', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('6A17A929-8B23-4D73-9DF9-A368E7C1C1B9', 'Friend', 'Personal friendship', 'PersonToPerson', FALSE, 'is friend of', 'is friend of', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('27CFD031-5663-4000-A7AB-8AC87DB88C1D', 'Employee', 'Employment relationship between a person and an organization', 'PersonToOrganization', TRUE, 'is employee of', 'employs', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('2FE33D05-5FD0-4076-8EF2-A30A640651B4', 'Board Member', 'Person serves on the board of directors of an organization', 'PersonToOrganization', TRUE, 'is board member of', 'has board member', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('5B8C871C-025B-410A-9D44-4D30C76534C7', 'Member', 'Person is a member of an organization or association', 'PersonToOrganization', TRUE, 'is member of', 'has member', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('DF72DDBB-A829-41AC-8698-01FCCD21FEEF', 'Volunteer', 'Person volunteers for an organization', 'PersonToOrganization', TRUE, 'volunteers for', 'has volunteer', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('DC06CB0C-A6CE-437C-A19E-F615F949BC51', 'Customer', 'Person is a customer or client of an organization', 'PersonToOrganization', TRUE, 'is customer of', 'has customer', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('6BF6959D-18B4-4615-AFCE-643963A87C1B', 'Consultant', 'Person provides consulting services to an organization', 'PersonToOrganization', TRUE, 'consults for', 'has consultant', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('39373681-5C70-4845-896B-4BFE4343751F', 'Subsidiary', 'One organization is a subsidiary or division of another', 'OrganizationToOrganization', TRUE, 'is subsidiary of', 'has subsidiary', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('CA9BBDBE-3595-4C3F-80FF-DA78D3389EA7', 'Partner', 'Strategic or business partnership between organizations', 'OrganizationToOrganization', FALSE, 'is partner of', 'is partner of', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('190A8BBF-771E-4631-980A-84918311E5EC', 'Vendor', 'One organization supplies goods or services to another', 'OrganizationToOrganization', TRUE, 'is vendor to', 'has vendor', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Common: Relationship Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappscommon."RelationshipType" ("ID", "Name", "Description", "Category", "IsDirectional", "ForwardLabel", "ReverseLabel", "IsActive")
VALUES ('2DBA78A6-DF6F-4A7E-B126-AE038BD3B6BA', 'Affiliate', 'Formal affiliation between two organizations', 'OrganizationToOrganization', FALSE, 'is affiliate of', 'is affiliate of', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ: Entity Fields (core SP call only)
DO $mj$
DECLARE
  p_DisplayName_ab3c9c28 VARCHAR(255);
  p_Description_ab3c9c28 TEXT;
  p_AutoUpdateDescription_ab3c9c28 BOOLEAN;
  p_IsPrimaryKey_ab3c9c28 BOOLEAN;
  p_IsUnique_ab3c9c28 BOOLEAN;
  p_Category_ab3c9c28 VARCHAR(255);
  p_ValueListType_ab3c9c28 VARCHAR(20);
  p_ExtendedType_ab3c9c28 VARCHAR(50);
  p_CodeType_ab3c9c28 VARCHAR(50);
  p_DefaultInView_ab3c9c28 BOOLEAN;
  p_ViewCellTemplate_ab3c9c28 TEXT;
  p_DefaultColumnWidth_ab3c9c28 INTEGER;
  p_AllowUpdateAPI_ab3c9c28 BOOLEAN;
  p_AllowUpdateInView_ab3c9c28 BOOLEAN;
  p_IncludeInUserSearchAPI_ab3c9c28 BOOLEAN;
  p_FullTextSearchEnabled_ab3c9c28 BOOLEAN;
  p_UserSearchParamFormatAPI_ab3c9c28 VARCHAR(500);
  p_IncludeInGeneratedForm_ab3c9c28 BOOLEAN;
  p_GeneratedFormSection_ab3c9c28 VARCHAR(10);
  p_IsNameField_ab3c9c28 BOOLEAN;
  p_RelatedEntityID_ab3c9c28 UUID;
  p_RelatedEntityFieldName_ab3c9c28 VARCHAR(255);
  p_IncludeRelatedEntityNameFieldInBaseView_ab3c9c28 BOOLEAN;
  p_RelatedEntityNameFieldMap_ab3c9c28 VARCHAR(255);
  p_RelatedEntityDisplayType_ab3c9c28 VARCHAR(20);
  p_EntityIDFieldName_ab3c9c28 VARCHAR(100);
  p_ScopeDefault_ab3c9c28 VARCHAR(100);
  p_AutoUpdateRelatedEntityInfo_ab3c9c28 BOOLEAN;
  p_ValuesToPackWithSchema_ab3c9c28 VARCHAR(10);
  p_Status_ab3c9c28 VARCHAR(25);
  p_AutoUpdateIsNameField_ab3c9c28 BOOLEAN;
  p_AutoUpdateDefaultInView_ab3c9c28 BOOLEAN;
  p_AutoUpdateCategory_ab3c9c28 BOOLEAN;
  p_AutoUpdateDisplayName_ab3c9c28 BOOLEAN;
  p_AutoUpdateIncludeInUserSearchAPI_ab3c9c28 BOOLEAN;
  p_Encrypt_ab3c9c28 BOOLEAN;
  p_EncryptionKeyID_ab3c9c28 UUID;
  p_AllowDecryptInAPI_ab3c9c28 BOOLEAN;
  p_SendEncryptedValue_ab3c9c28 BOOLEAN;
  p_IsSoftPrimaryKey_ab3c9c28 BOOLEAN;
  p_IsSoftForeignKey_ab3c9c28 BOOLEAN;
  p_RelatedEntityJoinFields_ab3c9c28 TEXT;
  p_JSONType_ab3c9c28 VARCHAR(255);
  p_JSONTypeIsArray_ab3c9c28 BOOLEAN;
  p_JSONTypeDefinition_ab3c9c28 TEXT;
  p_UserSearchPredicateAPI_ab3c9c28 VARCHAR(20);
  p_AutoUpdateUserSearchPredicate_ab3c9c28 BOOLEAN;
  p_AutoUpdateFullTextSearch_ab3c9c28 BOOLEAN;
  p_AutoUpdateExtendedType_ab3c9c28 BOOLEAN;
  p_ID_ab3c9c28 UUID;
BEGIN
  p_DisplayName_ab3c9c28 := 'Display Name';
  p_AutoUpdateDescription_ab3c9c28 := 1;
  p_IsPrimaryKey_ab3c9c28 := 0;
  p_IsUnique_ab3c9c28 := 0;
  p_ValueListType_ab3c9c28 := 'None';
  p_DefaultInView_ab3c9c28 := 0;
  p_DefaultColumnWidth_ab3c9c28 := 150;
  p_AllowUpdateAPI_ab3c9c28 := 0;
  p_AllowUpdateInView_ab3c9c28 := 1;
  p_IncludeInUserSearchAPI_ab3c9c28 := 0;
  p_FullTextSearchEnabled_ab3c9c28 := 0;
  p_IncludeInGeneratedForm_ab3c9c28 := 1;
  p_GeneratedFormSection_ab3c9c28 := 'Details';
  p_IsNameField_ab3c9c28 := 1;
  p_IncludeRelatedEntityNameFieldInBaseView_ab3c9c28 := 0;
  p_RelatedEntityDisplayType_ab3c9c28 := 'Search';
  p_AutoUpdateRelatedEntityInfo_ab3c9c28 := 1;
  p_ValuesToPackWithSchema_ab3c9c28 := 'Auto';
  p_Status_ab3c9c28 := 'Active';
  p_AutoUpdateIsNameField_ab3c9c28 := 0;
  p_AutoUpdateDefaultInView_ab3c9c28 := 1;
  p_AutoUpdateCategory_ab3c9c28 := 1;
  p_AutoUpdateDisplayName_ab3c9c28 := 1;
  p_AutoUpdateIncludeInUserSearchAPI_ab3c9c28 := 1;
  p_Encrypt_ab3c9c28 := 0;
  p_AllowDecryptInAPI_ab3c9c28 := 0;
  p_SendEncryptedValue_ab3c9c28 := 0;
  p_IsSoftPrimaryKey_ab3c9c28 := 0;
  p_IsSoftForeignKey_ab3c9c28 := 0;
  p_JSONTypeIsArray_ab3c9c28 := 0;
  p_UserSearchPredicateAPI_ab3c9c28 := 'Contains';
  p_AutoUpdateUserSearchPredicate_ab3c9c28 := 1;
  p_AutoUpdateFullTextSearch_ab3c9c28 := 1;
  p_AutoUpdateExtendedType_ab3c9c28 := 1;
  p_ID_ab3c9c28 := '76D49448-C586-4701-9FFF-63F390EC78C0';
  PERFORM __mj."spUpdateEntityField"(p_DisplayName := p_DisplayName_ab3c9c28, p_Description := p_Description_ab3c9c28, p_Description_Clear := TRUE, p_AutoUpdateDescription := p_AutoUpdateDescription_ab3c9c28, p_IsPrimaryKey := p_IsPrimaryKey_ab3c9c28, p_IsUnique := p_IsUnique_ab3c9c28, p_Category := p_Category_ab3c9c28, p_Category_Clear := TRUE, p_ValueListType := p_ValueListType_ab3c9c28, p_ExtendedType := p_ExtendedType_ab3c9c28, p_ExtendedType_Clear := TRUE, p_CodeType := p_CodeType_ab3c9c28, p_CodeType_Clear := TRUE, p_DefaultInView := p_DefaultInView_ab3c9c28, p_ViewCellTemplate := p_ViewCellTemplate_ab3c9c28, p_ViewCellTemplate_Clear := TRUE, p_DefaultColumnWidth := p_DefaultColumnWidth_ab3c9c28, p_AllowUpdateAPI := p_AllowUpdateAPI_ab3c9c28, p_AllowUpdateInView := p_AllowUpdateInView_ab3c9c28, p_IncludeInUserSearchAPI := p_IncludeInUserSearchAPI_ab3c9c28, p_FullTextSearchEnabled := p_FullTextSearchEnabled_ab3c9c28, p_UserSearchParamFormatAPI := p_UserSearchParamFormatAPI_ab3c9c28, p_UserSearchParamFormatAPI_Clear := TRUE, p_IncludeInGeneratedForm := p_IncludeInGeneratedForm_ab3c9c28, p_GeneratedFormSection := p_GeneratedFormSection_ab3c9c28, p_IsNameField := p_IsNameField_ab3c9c28, p_RelatedEntityID := p_RelatedEntityID_ab3c9c28, p_RelatedEntityID_Clear := TRUE, p_RelatedEntityFieldName := p_RelatedEntityFieldName_ab3c9c28, p_RelatedEntityFieldName_Clear := TRUE, p_IncludeRelatedEntityNameFieldInBaseView := p_IncludeRelatedEntityNameFieldInBaseView_ab3c9c28, p_RelatedEntityNameFieldMap := p_RelatedEntityNameFieldMap_ab3c9c28, p_RelatedEntityNameFieldMap_Clear := TRUE, p_RelatedEntityDisplayType := p_RelatedEntityDisplayType_ab3c9c28, p_EntityIDFieldName := p_EntityIDFieldName_ab3c9c28, p_EntityIDFieldName_Clear := TRUE, p_ScopeDefault := p_ScopeDefault_ab3c9c28, p_ScopeDefault_Clear := TRUE, p_AutoUpdateRelatedEntityInfo := p_AutoUpdateRelatedEntityInfo_ab3c9c28, p_ValuesToPackWithSchema := p_ValuesToPackWithSchema_ab3c9c28, p_Status := p_Status_ab3c9c28, p_AutoUpdateIsNameField := p_AutoUpdateIsNameField_ab3c9c28, p_AutoUpdateDefaultInView := p_AutoUpdateDefaultInView_ab3c9c28, p_AutoUpdateCategory := p_AutoUpdateCategory_ab3c9c28, p_AutoUpdateDisplayName := p_AutoUpdateDisplayName_ab3c9c28, p_AutoUpdateIncludeInUserSearchAPI := p_AutoUpdateIncludeInUserSearchAPI_ab3c9c28, p_Encrypt := p_Encrypt_ab3c9c28, p_EncryptionKeyID := p_EncryptionKeyID_ab3c9c28, p_EncryptionKeyID_Clear := TRUE, p_AllowDecryptInAPI := p_AllowDecryptInAPI_ab3c9c28, p_SendEncryptedValue := p_SendEncryptedValue_ab3c9c28, p_IsSoftPrimaryKey := p_IsSoftPrimaryKey_ab3c9c28, p_IsSoftForeignKey := p_IsSoftForeignKey_ab3c9c28, p_RelatedEntityJoinFields := p_RelatedEntityJoinFields_ab3c9c28, p_RelatedEntityJoinFields_Clear := TRUE, p_JSONType := p_JSONType_ab3c9c28, p_JSONType_Clear := TRUE, p_JSONTypeIsArray := p_JSONTypeIsArray_ab3c9c28, p_JSONTypeDefinition := p_JSONTypeDefinition_ab3c9c28, p_JSONTypeDefinition_Clear := TRUE, p_UserSearchPredicateAPI := p_UserSearchPredicateAPI_ab3c9c28, p_AutoUpdateUserSearchPredicate := p_AutoUpdateUserSearchPredicate_ab3c9c28, p_AutoUpdateFullTextSearch := p_AutoUpdateFullTextSearch_ab3c9c28, p_AutoUpdateExtendedType := p_AutoUpdateExtendedType_ab3c9c28, p_ID := p_ID_ab3c9c28);
END $mj$;

-- Save MJ: Entity Fields (core SP call only)
DO $mj$
DECLARE
  p_DisplayName_2bdbcdff VARCHAR(255);
  p_Description_2bdbcdff TEXT;
  p_AutoUpdateDescription_2bdbcdff BOOLEAN;
  p_IsPrimaryKey_2bdbcdff BOOLEAN;
  p_IsUnique_2bdbcdff BOOLEAN;
  p_Category_2bdbcdff VARCHAR(255);
  p_ValueListType_2bdbcdff VARCHAR(20);
  p_ExtendedType_2bdbcdff VARCHAR(50);
  p_CodeType_2bdbcdff VARCHAR(50);
  p_DefaultInView_2bdbcdff BOOLEAN;
  p_ViewCellTemplate_2bdbcdff TEXT;
  p_DefaultColumnWidth_2bdbcdff INTEGER;
  p_AllowUpdateAPI_2bdbcdff BOOLEAN;
  p_AllowUpdateInView_2bdbcdff BOOLEAN;
  p_IncludeInUserSearchAPI_2bdbcdff BOOLEAN;
  p_FullTextSearchEnabled_2bdbcdff BOOLEAN;
  p_UserSearchParamFormatAPI_2bdbcdff VARCHAR(500);
  p_IncludeInGeneratedForm_2bdbcdff BOOLEAN;
  p_GeneratedFormSection_2bdbcdff VARCHAR(10);
  p_IsNameField_2bdbcdff BOOLEAN;
  p_RelatedEntityID_2bdbcdff UUID;
  p_RelatedEntityFieldName_2bdbcdff VARCHAR(255);
  p_IncludeRelatedEntityNameFieldInBaseView_2bdbcdff BOOLEAN;
  p_RelatedEntityNameFieldMap_2bdbcdff VARCHAR(255);
  p_RelatedEntityDisplayType_2bdbcdff VARCHAR(20);
  p_EntityIDFieldName_2bdbcdff VARCHAR(100);
  p_ScopeDefault_2bdbcdff VARCHAR(100);
  p_AutoUpdateRelatedEntityInfo_2bdbcdff BOOLEAN;
  p_ValuesToPackWithSchema_2bdbcdff VARCHAR(10);
  p_Status_2bdbcdff VARCHAR(25);
  p_AutoUpdateIsNameField_2bdbcdff BOOLEAN;
  p_AutoUpdateDefaultInView_2bdbcdff BOOLEAN;
  p_AutoUpdateCategory_2bdbcdff BOOLEAN;
  p_AutoUpdateDisplayName_2bdbcdff BOOLEAN;
  p_AutoUpdateIncludeInUserSearchAPI_2bdbcdff BOOLEAN;
  p_Encrypt_2bdbcdff BOOLEAN;
  p_EncryptionKeyID_2bdbcdff UUID;
  p_AllowDecryptInAPI_2bdbcdff BOOLEAN;
  p_SendEncryptedValue_2bdbcdff BOOLEAN;
  p_IsSoftPrimaryKey_2bdbcdff BOOLEAN;
  p_IsSoftForeignKey_2bdbcdff BOOLEAN;
  p_RelatedEntityJoinFields_2bdbcdff TEXT;
  p_JSONType_2bdbcdff VARCHAR(255);
  p_JSONTypeIsArray_2bdbcdff BOOLEAN;
  p_JSONTypeDefinition_2bdbcdff TEXT;
  p_UserSearchPredicateAPI_2bdbcdff VARCHAR(20);
  p_AutoUpdateUserSearchPredicate_2bdbcdff BOOLEAN;
  p_AutoUpdateFullTextSearch_2bdbcdff BOOLEAN;
  p_AutoUpdateExtendedType_2bdbcdff BOOLEAN;
  p_ID_2bdbcdff UUID;
BEGIN
  p_DisplayName_2bdbcdff := 'Last Name';
  p_Description_2bdbcdff := 'Last (family) name';
  p_AutoUpdateDescription_2bdbcdff := 1;
  p_IsPrimaryKey_2bdbcdff := 0;
  p_IsUnique_2bdbcdff := 0;
  p_Category_2bdbcdff := 'Personal Identity';
  p_ValueListType_2bdbcdff := 'None';
  p_DefaultInView_2bdbcdff := 1;
  p_DefaultColumnWidth_2bdbcdff := 150;
  p_AllowUpdateAPI_2bdbcdff := 1;
  p_AllowUpdateInView_2bdbcdff := 1;
  p_IncludeInUserSearchAPI_2bdbcdff := 1;
  p_FullTextSearchEnabled_2bdbcdff := 0;
  p_IncludeInGeneratedForm_2bdbcdff := 1;
  p_GeneratedFormSection_2bdbcdff := 'Category';
  p_IsNameField_2bdbcdff := 0;
  p_IncludeRelatedEntityNameFieldInBaseView_2bdbcdff := 0;
  p_RelatedEntityDisplayType_2bdbcdff := 'Search';
  p_AutoUpdateRelatedEntityInfo_2bdbcdff := 1;
  p_ValuesToPackWithSchema_2bdbcdff := 'Auto';
  p_Status_2bdbcdff := 'Active';
  p_AutoUpdateIsNameField_2bdbcdff := 0;
  p_AutoUpdateDefaultInView_2bdbcdff := 1;
  p_AutoUpdateCategory_2bdbcdff := 1;
  p_AutoUpdateDisplayName_2bdbcdff := 1;
  p_AutoUpdateIncludeInUserSearchAPI_2bdbcdff := 1;
  p_Encrypt_2bdbcdff := 0;
  p_AllowDecryptInAPI_2bdbcdff := 0;
  p_SendEncryptedValue_2bdbcdff := 0;
  p_IsSoftPrimaryKey_2bdbcdff := 0;
  p_IsSoftForeignKey_2bdbcdff := 0;
  p_JSONTypeIsArray_2bdbcdff := 0;
  p_UserSearchPredicateAPI_2bdbcdff := 'Contains';
  p_AutoUpdateUserSearchPredicate_2bdbcdff := 1;
  p_AutoUpdateFullTextSearch_2bdbcdff := 1;
  p_AutoUpdateExtendedType_2bdbcdff := 1;
  p_ID_2bdbcdff := '09AD91DA-42C7-44F4-AE71-5AC6E50D7657';
  PERFORM __mj."spUpdateEntityField"(p_DisplayName := p_DisplayName_2bdbcdff, p_Description := p_Description_2bdbcdff, p_AutoUpdateDescription := p_AutoUpdateDescription_2bdbcdff, p_IsPrimaryKey := p_IsPrimaryKey_2bdbcdff, p_IsUnique := p_IsUnique_2bdbcdff, p_Category := p_Category_2bdbcdff, p_ValueListType := p_ValueListType_2bdbcdff, p_ExtendedType := p_ExtendedType_2bdbcdff, p_ExtendedType_Clear := TRUE, p_CodeType := p_CodeType_2bdbcdff, p_CodeType_Clear := TRUE, p_DefaultInView := p_DefaultInView_2bdbcdff, p_ViewCellTemplate := p_ViewCellTemplate_2bdbcdff, p_ViewCellTemplate_Clear := TRUE, p_DefaultColumnWidth := p_DefaultColumnWidth_2bdbcdff, p_AllowUpdateAPI := p_AllowUpdateAPI_2bdbcdff, p_AllowUpdateInView := p_AllowUpdateInView_2bdbcdff, p_IncludeInUserSearchAPI := p_IncludeInUserSearchAPI_2bdbcdff, p_FullTextSearchEnabled := p_FullTextSearchEnabled_2bdbcdff, p_UserSearchParamFormatAPI := p_UserSearchParamFormatAPI_2bdbcdff, p_UserSearchParamFormatAPI_Clear := TRUE, p_IncludeInGeneratedForm := p_IncludeInGeneratedForm_2bdbcdff, p_GeneratedFormSection := p_GeneratedFormSection_2bdbcdff, p_IsNameField := p_IsNameField_2bdbcdff, p_RelatedEntityID := p_RelatedEntityID_2bdbcdff, p_RelatedEntityID_Clear := TRUE, p_RelatedEntityFieldName := p_RelatedEntityFieldName_2bdbcdff, p_RelatedEntityFieldName_Clear := TRUE, p_IncludeRelatedEntityNameFieldInBaseView := p_IncludeRelatedEntityNameFieldInBaseView_2bdbcdff, p_RelatedEntityNameFieldMap := p_RelatedEntityNameFieldMap_2bdbcdff, p_RelatedEntityNameFieldMap_Clear := TRUE, p_RelatedEntityDisplayType := p_RelatedEntityDisplayType_2bdbcdff, p_EntityIDFieldName := p_EntityIDFieldName_2bdbcdff, p_EntityIDFieldName_Clear := TRUE, p_ScopeDefault := p_ScopeDefault_2bdbcdff, p_ScopeDefault_Clear := TRUE, p_AutoUpdateRelatedEntityInfo := p_AutoUpdateRelatedEntityInfo_2bdbcdff, p_ValuesToPackWithSchema := p_ValuesToPackWithSchema_2bdbcdff, p_Status := p_Status_2bdbcdff, p_AutoUpdateIsNameField := p_AutoUpdateIsNameField_2bdbcdff, p_AutoUpdateDefaultInView := p_AutoUpdateDefaultInView_2bdbcdff, p_AutoUpdateCategory := p_AutoUpdateCategory_2bdbcdff, p_AutoUpdateDisplayName := p_AutoUpdateDisplayName_2bdbcdff, p_AutoUpdateIncludeInUserSearchAPI := p_AutoUpdateIncludeInUserSearchAPI_2bdbcdff, p_Encrypt := p_Encrypt_2bdbcdff, p_EncryptionKeyID := p_EncryptionKeyID_2bdbcdff, p_EncryptionKeyID_Clear := TRUE, p_AllowDecryptInAPI := p_AllowDecryptInAPI_2bdbcdff, p_SendEncryptedValue := p_SendEncryptedValue_2bdbcdff, p_IsSoftPrimaryKey := p_IsSoftPrimaryKey_2bdbcdff, p_IsSoftForeignKey := p_IsSoftForeignKey_2bdbcdff, p_RelatedEntityJoinFields := p_RelatedEntityJoinFields_2bdbcdff, p_RelatedEntityJoinFields_Clear := TRUE, p_JSONType := p_JSONType_2bdbcdff, p_JSONType_Clear := TRUE, p_JSONTypeIsArray := p_JSONTypeIsArray_2bdbcdff, p_JSONTypeDefinition := p_JSONTypeDefinition_2bdbcdff, p_JSONTypeDefinition_Clear := TRUE, p_UserSearchPredicateAPI := p_UserSearchPredicateAPI_2bdbcdff, p_AutoUpdateUserSearchPredicate := p_AutoUpdateUserSearchPredicate_2bdbcdff, p_AutoUpdateFullTextSearch := p_AutoUpdateFullTextSearch_2bdbcdff, p_AutoUpdateExtendedType := p_AutoUpdateExtendedType_2bdbcdff, p_ID := p_ID_2bdbcdff);
END $mj$;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: 134655f8-85d5-43c2-b18d-da8ba5f27c8a
-- Completed: 2026-05-14T15:55:52.304Z
-- Duration: 1016ms
-- Total Statements: 39
